<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Trader account entity. 
 *
 * Generated from protobuf message <code>ProtoOACtidTraderAccount</code>
 */
class ProtoOACtidTraderAccount extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.cTrader platform. Different brokers might have different ids
     *
     * Generated from protobuf field <code>uint64 ctidTraderAccountId = 1;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * If TRUE then the account is belong to Live environment and live host must be used to authorize it
     *
     * Generated from protobuf field <code>bool isLive = 2;</code>
     */
    protected $isLive = false;
    /**
     * TraderLogin for a specific account. Value is displayed on Client App UI
     *
     * Generated from protobuf field <code>int64 traderLogin = 3;</code>
     */
    protected $traderLogin = 0;
    /**
     * The Unix time in milliseconds of the last ProtoOAClosePositionDetail happened to this account.
     *
     * Generated from protobuf field <code>int64 lastClosingDealTimestamp = 4;</code>
     */
    protected $lastClosingDealTimestamp = 0;
    /**
     * The Unix time in milliseconds of the last ProtoOADepositWithdraw happened to this account.
     *
     * Generated from protobuf field <code>int64 lastBalanceUpdateTimestamp = 5;</code>
     */
    protected $lastBalanceUpdateTimestamp = 0;
    /**
     * The name of the broker to which the account belongs to. Shortened to be displayed in the UI.
     *
     * Generated from protobuf field <code>string brokerTitleShort = 6;</code>
     */
    protected $brokerTitleShort = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.cTrader platform. Different brokers might have different ids
     *     @type bool $isLive
     *           If TRUE then the account is belong to Live environment and live host must be used to authorize it
     *     @type int|string $traderLogin
     *           TraderLogin for a specific account. Value is displayed on Client App UI
     *     @type int|string $lastClosingDealTimestamp
     *           The Unix time in milliseconds of the last ProtoOAClosePositionDetail happened to this account.
     *     @type int|string $lastBalanceUpdateTimestamp
     *           The Unix time in milliseconds of the last ProtoOADepositWithdraw happened to this account.
     *     @type string $brokerTitleShort
     *           The name of the broker to which the account belongs to. Shortened to be displayed in the UI.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.cTrader platform. Different brokers might have different ids
     *
     * Generated from protobuf field <code>uint64 ctidTraderAccountId = 1;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.cTrader platform. Different brokers might have different ids
     *
     * Generated from protobuf field <code>uint64 ctidTraderAccountId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkUint64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * If TRUE then the account is belong to Live environment and live host must be used to authorize it
     *
     * Generated from protobuf field <code>bool isLive = 2;</code>
     * @return bool
     */
    public function getIsLive()
    {
        return $this->isLive;
    }

    /**
     * If TRUE then the account is belong to Live environment and live host must be used to authorize it
     *
     * Generated from protobuf field <code>bool isLive = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLive($var)
    {
        GPBUtil::checkBool($var);
        $this->isLive = $var;

        return $this;
    }

    /**
     * TraderLogin for a specific account. Value is displayed on Client App UI
     *
     * Generated from protobuf field <code>int64 traderLogin = 3;</code>
     * @return int|string
     */
    public function getTraderLogin()
    {
        return $this->traderLogin;
    }

    /**
     * TraderLogin for a specific account. Value is displayed on Client App UI
     *
     * Generated from protobuf field <code>int64 traderLogin = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTraderLogin($var)
    {
        GPBUtil::checkInt64($var);
        $this->traderLogin = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds of the last ProtoOAClosePositionDetail happened to this account.
     *
     * Generated from protobuf field <code>int64 lastClosingDealTimestamp = 4;</code>
     * @return int|string
     */
    public function getLastClosingDealTimestamp()
    {
        return $this->lastClosingDealTimestamp;
    }

    /**
     * The Unix time in milliseconds of the last ProtoOAClosePositionDetail happened to this account.
     *
     * Generated from protobuf field <code>int64 lastClosingDealTimestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastClosingDealTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->lastClosingDealTimestamp = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds of the last ProtoOADepositWithdraw happened to this account.
     *
     * Generated from protobuf field <code>int64 lastBalanceUpdateTimestamp = 5;</code>
     * @return int|string
     */
    public function getLastBalanceUpdateTimestamp()
    {
        return $this->lastBalanceUpdateTimestamp;
    }

    /**
     * The Unix time in milliseconds of the last ProtoOADepositWithdraw happened to this account.
     *
     * Generated from protobuf field <code>int64 lastBalanceUpdateTimestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastBalanceUpdateTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->lastBalanceUpdateTimestamp = $var;

        return $this;
    }

    /**
     * The name of the broker to which the account belongs to. Shortened to be displayed in the UI.
     *
     * Generated from protobuf field <code>string brokerTitleShort = 6;</code>
     * @return string
     */
    public function getBrokerTitleShort()
    {
        return $this->brokerTitleShort;
    }

    /**
     * The name of the broker to which the account belongs to. Shortened to be displayed in the UI.
     *
     * Generated from protobuf field <code>string brokerTitleShort = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBrokerTitleShort($var)
    {
        GPBUtil::checkString($var, True);
        $this->brokerTitleShort = $var;

        return $this;
    }

}

