<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** The response to the ProtoOAReconcileReq request. 
 *
 * Generated from protobuf message <code>ProtoOAReconcileRes</code>
 */
class ProtoOAReconcileRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * The list of trader's account open positions.
     *
     * Generated from protobuf field <code>repeated .ProtoOAPosition position = 3;</code>
     */
    private $position;
    /**
     * The list of trader's account pending orders.
     *
     * Generated from protobuf field <code>repeated .ProtoOAOrder order = 4;</code>
     */
    private $order;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOAPosition[]|\Google\Protobuf\Internal\RepeatedField $position
     *           The list of trader's account open positions.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrder[]|\Google\Protobuf\Internal\RepeatedField $order
     *           The list of trader's account pending orders.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * The list of trader's account open positions.
     *
     * Generated from protobuf field <code>repeated .ProtoOAPosition position = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * The list of trader's account open positions.
     *
     * Generated from protobuf field <code>repeated .ProtoOAPosition position = 3;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOAPosition[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPosition($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPosition::class);
        $this->position = $arr;

        return $this;
    }

    /**
     * The list of trader's account pending orders.
     *
     * Generated from protobuf field <code>repeated .ProtoOAOrder order = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * The list of trader's account pending orders.
     *
     * Generated from protobuf field <code>repeated .ProtoOAOrder order = 4;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrder[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrder($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrder::class);
        $this->order = $arr;

        return $this;
    }

}

