<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** The response to the ProtoOAExpectedMarginReq request. 
 *
 * Generated from protobuf message <code>ProtoOAExpectedMarginRes</code>
 */
class ProtoOAExpectedMarginRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * The buy and sell margin estimate.
     *
     * Generated from protobuf field <code>repeated .ProtoOAExpectedMargin margin = 3;</code>
     */
    private $margin;
    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects margin.buyMargin, margin.sellMargin.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 4;</code>
     */
    protected $moneyDigits = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOAExpectedMargin[]|\Google\Protobuf\Internal\RepeatedField $margin
     *           The buy and sell margin estimate.
     *     @type int $moneyDigits
     *           Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects margin.buyMargin, margin.sellMargin.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * The buy and sell margin estimate.
     *
     * Generated from protobuf field <code>repeated .ProtoOAExpectedMargin margin = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMargin()
    {
        return $this->margin;
    }

    /**
     * The buy and sell margin estimate.
     *
     * Generated from protobuf field <code>repeated .ProtoOAExpectedMargin margin = 3;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOAExpectedMargin[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMargin($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOAExpectedMargin::class);
        $this->margin = $arr;

        return $this;
    }

    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects margin.buyMargin, margin.sellMargin.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 4;</code>
     * @return int
     */
    public function getMoneyDigits()
    {
        return $this->moneyDigits;
    }

    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects margin.buyMargin, margin.sellMargin.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMoneyDigits($var)
    {
        GPBUtil::checkUint32($var);
        $this->moneyDigits = $var;

        return $this;
    }

}

