<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Response for ProtoOADealOffsetListReq. 
 *
 * Generated from protobuf message <code>ProtoOADealOffsetListRes</code>
 */
class ProtoOADealOffsetListRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * Deals which closed the specified deal.
     *
     * Generated from protobuf field <code>repeated .ProtoOADealOffset offsetBy = 3;</code>
     */
    private $offsetBy;
    /**
     * Deals which were closed by the specified deal.
     *
     * Generated from protobuf field <code>repeated .ProtoOADealOffset offsetting = 4;</code>
     */
    private $offsetting;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOADealOffset[]|\Google\Protobuf\Internal\RepeatedField $offsetBy
     *           Deals which closed the specified deal.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOADealOffset[]|\Google\Protobuf\Internal\RepeatedField $offsetting
     *           Deals which were closed by the specified deal.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * Deals which closed the specified deal.
     *
     * Generated from protobuf field <code>repeated .ProtoOADealOffset offsetBy = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOffsetBy()
    {
        return $this->offsetBy;
    }

    /**
     * Deals which closed the specified deal.
     *
     * Generated from protobuf field <code>repeated .ProtoOADealOffset offsetBy = 3;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOADealOffset[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOffsetBy($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOADealOffset::class);
        $this->offsetBy = $arr;

        return $this;
    }

    /**
     * Deals which were closed by the specified deal.
     *
     * Generated from protobuf field <code>repeated .ProtoOADealOffset offsetting = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOffsetting()
    {
        return $this->offsetting;
    }

    /**
     * Deals which were closed by the specified deal.
     *
     * Generated from protobuf field <code>repeated .ProtoOADealOffset offsetting = 4;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOADealOffset[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOffsetting($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOADealOffset::class);
        $this->offsetting = $arr;

        return $this;
    }

}

