<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Response to the ProtoOADealListByPositionIdReq request. 
 *
 * Generated from protobuf message <code>ProtoOADealListByPositionIdRes</code>
 */
class ProtoOADealListByPositionIdRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * The list of deals.
     *
     * Generated from protobuf field <code>repeated .ProtoOADeal deal = 3;</code>
     */
    private $deal;
    /**
     * If TRUE then the number of records by filter is larger than chunkSize, the response contains the number of records that is equal to chunkSize.
     *
     * Generated from protobuf field <code>bool hasMore = 4;</code>
     */
    protected $hasMore = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOADeal[]|\Google\Protobuf\Internal\RepeatedField $deal
     *           The list of deals.
     *     @type bool $hasMore
     *           If TRUE then the number of records by filter is larger than chunkSize, the response contains the number of records that is equal to chunkSize.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * The list of deals.
     *
     * Generated from protobuf field <code>repeated .ProtoOADeal deal = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeal()
    {
        return $this->deal;
    }

    /**
     * The list of deals.
     *
     * Generated from protobuf field <code>repeated .ProtoOADeal deal = 3;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOADeal[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeal($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOADeal::class);
        $this->deal = $arr;

        return $this;
    }

    /**
     * If TRUE then the number of records by filter is larger than chunkSize, the response contains the number of records that is equal to chunkSize.
     *
     * Generated from protobuf field <code>bool hasMore = 4;</code>
     * @return bool
     */
    public function getHasMore()
    {
        return $this->hasMore;
    }

    /**
     * If TRUE then the number of records by filter is larger than chunkSize, the response contains the number of records that is equal to chunkSize.
     *
     * Generated from protobuf field <code>bool hasMore = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasMore($var)
    {
        GPBUtil::checkBool($var);
        $this->hasMore = $var;

        return $this;
    }

}

