<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Enum for specifying type of minimum trading commission. 
 *
 * Protobuf type <code>ProtoOAMinCommissionType</code>
 */
class ProtoOAMinCommissionType
{
    /**
     * Generated from protobuf enum <code>MIN_COMMISSION_TYPE_UNKNOWN = 0;</code>
     */
    const MIN_COMMISSION_TYPE_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>CURRENCY = 1;</code>
     */
    const CURRENCY = 1;
    /**
     * Generated from protobuf enum <code>QUOTE_CURRENCY = 2;</code>
     */
    const QUOTE_CURRENCY = 2;

    private static $valueToName = [
        self::MIN_COMMISSION_TYPE_UNKNOWN => 'MIN_COMMISSION_TYPE_UNKNOWN',
        self::CURRENCY => 'CURRENCY',
        self::QUOTE_CURRENCY => 'QUOTE_CURRENCY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

