<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Order status ENUM. 
 *
 * Protobuf type <code>ProtoOAOrderStatus</code>
 */
class ProtoOAOrderStatus
{
    /**
     * Generated from protobuf enum <code>ORDER_STATUS_UNKNOWN = 0;</code>
     */
    const ORDER_STATUS_UNKNOWN = 0;
    /**
     * Order request validated and accepted for execution.
     *
     * Generated from protobuf enum <code>ORDER_STATUS_ACCEPTED = 1;</code>
     */
    const ORDER_STATUS_ACCEPTED = 1;
    /**
     * Order is fully filled.
     *
     * Generated from protobuf enum <code>ORDER_STATUS_FILLED = 2;</code>
     */
    const ORDER_STATUS_FILLED = 2;
    /**
     * Order is rejected due to validation.
     *
     * Generated from protobuf enum <code>ORDER_STATUS_REJECTED = 3;</code>
     */
    const ORDER_STATUS_REJECTED = 3;
    /**
     * Order expired. Might be valid for orders with partially filled volume that were expired on LP.
     *
     * Generated from protobuf enum <code>ORDER_STATUS_EXPIRED = 4;</code>
     */
    const ORDER_STATUS_EXPIRED = 4;
    /**
     * Order is cancelled. Might be valid for orders with partially filled volume that were cancelled by LP.
     *
     * Generated from protobuf enum <code>ORDER_STATUS_CANCELLED = 5;</code>
     */
    const ORDER_STATUS_CANCELLED = 5;

    private static $valueToName = [
        self::ORDER_STATUS_UNKNOWN => 'ORDER_STATUS_UNKNOWN',
        self::ORDER_STATUS_ACCEPTED => 'ORDER_STATUS_ACCEPTED',
        self::ORDER_STATUS_FILLED => 'ORDER_STATUS_FILLED',
        self::ORDER_STATUS_REJECTED => 'ORDER_STATUS_REJECTED',
        self::ORDER_STATUS_EXPIRED => 'ORDER_STATUS_EXPIRED',
        self::ORDER_STATUS_CANCELLED => 'ORDER_STATUS_CANCELLED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

