<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Execution entity. 
 *
 * Generated from protobuf message <code>ProtoOADeal</code>
 */
class ProtoOADeal extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique ID of the execution deal.
     *
     * Generated from protobuf field <code>int64 dealId = 1;</code>
     */
    protected $dealId = 0;
    /**
     * Source order of the deal.
     *
     * Generated from protobuf field <code>int64 orderId = 2;</code>
     */
    protected $orderId = 0;
    /**
     * Source position of the deal.
     *
     * Generated from protobuf field <code>int64 positionId = 3;</code>
     */
    protected $positionId = 0;
    /**
     * Volume sent for execution, in cents.
     *
     * Generated from protobuf field <code>int64 volume = 4;</code>
     */
    protected $volume = 0;
    /**
     * Filled volume, in cents.
     *
     * Generated from protobuf field <code>int64 filledVolume = 5;</code>
     */
    protected $filledVolume = 0;
    /**
     * The unique identifier of the symbol in specific server environment within cTrader platform. Different servers have different IDs.
     *
     * Generated from protobuf field <code>int64 symbolId = 6;</code>
     */
    protected $symbolId = 0;
    /**
     * The Unix time in milliseconds when the deal was sent for execution.
     *
     * Generated from protobuf field <code>int64 createTimestamp = 7;</code>
     */
    protected $createTimestamp = 0;
    /**
     * The Unix time in milliseconds when the deal was executed.
     *
     * Generated from protobuf field <code>int64 executionTimestamp = 8;</code>
     */
    protected $executionTimestamp = 0;
    /**
     * The Unix time in milliseconds when the deal was created, executed or rejected.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 9;</code>
     */
    protected $utcLastUpdateTimestamp = 0;
    /**
     * Execution price.
     *
     * Generated from protobuf field <code>double executionPrice = 10;</code>
     */
    protected $executionPrice = 0.0;
    /**
     * Buy/Sell.
     *
     * Generated from protobuf field <code>.ProtoOATradeSide tradeSide = 11;</code>
     */
    protected $tradeSide = 0;
    /**
     * Status of the deal.
     *
     * Generated from protobuf field <code>.ProtoOADealStatus dealStatus = 12;</code>
     */
    protected $dealStatus = 0;
    /**
     * Rate for used margin computation. Represented as Base/Deposit.
     *
     * Generated from protobuf field <code>double marginRate = 13;</code>
     */
    protected $marginRate = 0.0;
    /**
     * Amount of trading commission associated with the deal.
     *
     * Generated from protobuf field <code>int64 commission = 14;</code>
     */
    protected $commission = 0;
    /**
     * Base to USD conversion rate on the time of deal execution.
     *
     * Generated from protobuf field <code>double baseToUsdConversionRate = 15;</code>
     */
    protected $baseToUsdConversionRate = 0.0;
    /**
     * Closing position detail. Valid only for closing deal.
     *
     * Generated from protobuf field <code>.ProtoOAClosePositionDetail closePositionDetail = 16;</code>
     */
    protected $closePositionDetail = null;
    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects commission.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 17;</code>
     */
    protected $moneyDigits = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $dealId
     *           The unique ID of the execution deal.
     *     @type int|string $orderId
     *           Source order of the deal.
     *     @type int|string $positionId
     *           Source position of the deal.
     *     @type int|string $volume
     *           Volume sent for execution, in cents.
     *     @type int|string $filledVolume
     *           Filled volume, in cents.
     *     @type int|string $symbolId
     *           The unique identifier of the symbol in specific server environment within cTrader platform. Different servers have different IDs.
     *     @type int|string $createTimestamp
     *           The Unix time in milliseconds when the deal was sent for execution.
     *     @type int|string $executionTimestamp
     *           The Unix time in milliseconds when the deal was executed.
     *     @type int|string $utcLastUpdateTimestamp
     *           The Unix time in milliseconds when the deal was created, executed or rejected.
     *     @type float $executionPrice
     *           Execution price.
     *     @type int $tradeSide
     *           Buy/Sell.
     *     @type int $dealStatus
     *           Status of the deal.
     *     @type float $marginRate
     *           Rate for used margin computation. Represented as Base/Deposit.
     *     @type int|string $commission
     *           Amount of trading commission associated with the deal.
     *     @type float $baseToUsdConversionRate
     *           Base to USD conversion rate on the time of deal execution.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOAClosePositionDetail $closePositionDetail
     *           Closing position detail. Valid only for closing deal.
     *     @type int $moneyDigits
     *           Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects commission.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique ID of the execution deal.
     *
     * Generated from protobuf field <code>int64 dealId = 1;</code>
     * @return int|string
     */
    public function getDealId()
    {
        return $this->dealId;
    }

    /**
     * The unique ID of the execution deal.
     *
     * Generated from protobuf field <code>int64 dealId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDealId($var)
    {
        GPBUtil::checkInt64($var);
        $this->dealId = $var;

        return $this;
    }

    /**
     * Source order of the deal.
     *
     * Generated from protobuf field <code>int64 orderId = 2;</code>
     * @return int|string
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * Source order of the deal.
     *
     * Generated from protobuf field <code>int64 orderId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt64($var);
        $this->orderId = $var;

        return $this;
    }

    /**
     * Source position of the deal.
     *
     * Generated from protobuf field <code>int64 positionId = 3;</code>
     * @return int|string
     */
    public function getPositionId()
    {
        return $this->positionId;
    }

    /**
     * Source position of the deal.
     *
     * Generated from protobuf field <code>int64 positionId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPositionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->positionId = $var;

        return $this;
    }

    /**
     * Volume sent for execution, in cents.
     *
     * Generated from protobuf field <code>int64 volume = 4;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Volume sent for execution, in cents.
     *
     * Generated from protobuf field <code>int64 volume = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkInt64($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * Filled volume, in cents.
     *
     * Generated from protobuf field <code>int64 filledVolume = 5;</code>
     * @return int|string
     */
    public function getFilledVolume()
    {
        return $this->filledVolume;
    }

    /**
     * Filled volume, in cents.
     *
     * Generated from protobuf field <code>int64 filledVolume = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFilledVolume($var)
    {
        GPBUtil::checkInt64($var);
        $this->filledVolume = $var;

        return $this;
    }

    /**
     * The unique identifier of the symbol in specific server environment within cTrader platform. Different servers have different IDs.
     *
     * Generated from protobuf field <code>int64 symbolId = 6;</code>
     * @return int|string
     */
    public function getSymbolId()
    {
        return $this->symbolId;
    }

    /**
     * The unique identifier of the symbol in specific server environment within cTrader platform. Different servers have different IDs.
     *
     * Generated from protobuf field <code>int64 symbolId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSymbolId($var)
    {
        GPBUtil::checkInt64($var);
        $this->symbolId = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds when the deal was sent for execution.
     *
     * Generated from protobuf field <code>int64 createTimestamp = 7;</code>
     * @return int|string
     */
    public function getCreateTimestamp()
    {
        return $this->createTimestamp;
    }

    /**
     * The Unix time in milliseconds when the deal was sent for execution.
     *
     * Generated from protobuf field <code>int64 createTimestamp = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->createTimestamp = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds when the deal was executed.
     *
     * Generated from protobuf field <code>int64 executionTimestamp = 8;</code>
     * @return int|string
     */
    public function getExecutionTimestamp()
    {
        return $this->executionTimestamp;
    }

    /**
     * The Unix time in milliseconds when the deal was executed.
     *
     * Generated from protobuf field <code>int64 executionTimestamp = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExecutionTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->executionTimestamp = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds when the deal was created, executed or rejected.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 9;</code>
     * @return int|string
     */
    public function getUtcLastUpdateTimestamp()
    {
        return $this->utcLastUpdateTimestamp;
    }

    /**
     * The Unix time in milliseconds when the deal was created, executed or rejected.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUtcLastUpdateTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->utcLastUpdateTimestamp = $var;

        return $this;
    }

    /**
     * Execution price.
     *
     * Generated from protobuf field <code>double executionPrice = 10;</code>
     * @return float
     */
    public function getExecutionPrice()
    {
        return $this->executionPrice;
    }

    /**
     * Execution price.
     *
     * Generated from protobuf field <code>double executionPrice = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setExecutionPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->executionPrice = $var;

        return $this;
    }

    /**
     * Buy/Sell.
     *
     * Generated from protobuf field <code>.ProtoOATradeSide tradeSide = 11;</code>
     * @return int
     */
    public function getTradeSide()
    {
        return $this->tradeSide;
    }

    /**
     * Buy/Sell.
     *
     * Generated from protobuf field <code>.ProtoOATradeSide tradeSide = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setTradeSide($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOATradeSide::class);
        $this->tradeSide = $var;

        return $this;
    }

    /**
     * Status of the deal.
     *
     * Generated from protobuf field <code>.ProtoOADealStatus dealStatus = 12;</code>
     * @return int
     */
    public function getDealStatus()
    {
        return $this->dealStatus;
    }

    /**
     * Status of the deal.
     *
     * Generated from protobuf field <code>.ProtoOADealStatus dealStatus = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setDealStatus($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOADealStatus::class);
        $this->dealStatus = $var;

        return $this;
    }

    /**
     * Rate for used margin computation. Represented as Base/Deposit.
     *
     * Generated from protobuf field <code>double marginRate = 13;</code>
     * @return float
     */
    public function getMarginRate()
    {
        return $this->marginRate;
    }

    /**
     * Rate for used margin computation. Represented as Base/Deposit.
     *
     * Generated from protobuf field <code>double marginRate = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setMarginRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->marginRate = $var;

        return $this;
    }

    /**
     * Amount of trading commission associated with the deal.
     *
     * Generated from protobuf field <code>int64 commission = 14;</code>
     * @return int|string
     */
    public function getCommission()
    {
        return $this->commission;
    }

    /**
     * Amount of trading commission associated with the deal.
     *
     * Generated from protobuf field <code>int64 commission = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCommission($var)
    {
        GPBUtil::checkInt64($var);
        $this->commission = $var;

        return $this;
    }

    /**
     * Base to USD conversion rate on the time of deal execution.
     *
     * Generated from protobuf field <code>double baseToUsdConversionRate = 15;</code>
     * @return float
     */
    public function getBaseToUsdConversionRate()
    {
        return $this->baseToUsdConversionRate;
    }

    /**
     * Base to USD conversion rate on the time of deal execution.
     *
     * Generated from protobuf field <code>double baseToUsdConversionRate = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setBaseToUsdConversionRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->baseToUsdConversionRate = $var;

        return $this;
    }

    /**
     * Closing position detail. Valid only for closing deal.
     *
     * Generated from protobuf field <code>.ProtoOAClosePositionDetail closePositionDetail = 16;</code>
     * @return \SocialiteProviders\Ctrader\Protobuf\ProtoOAClosePositionDetail
     */
    public function getClosePositionDetail()
    {
        return $this->closePositionDetail;
    }

    /**
     * Closing position detail. Valid only for closing deal.
     *
     * Generated from protobuf field <code>.ProtoOAClosePositionDetail closePositionDetail = 16;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOAClosePositionDetail $var
     * @return $this
     */
    public function setClosePositionDetail($var)
    {
        GPBUtil::checkMessage($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAClosePositionDetail::class);
        $this->closePositionDetail = $var;

        return $this;
    }

    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects commission.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 17;</code>
     * @return int
     */
    public function getMoneyDigits()
    {
        return $this->moneyDigits;
    }

    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects commission.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setMoneyDigits($var)
    {
        GPBUtil::checkUint32($var);
        $this->moneyDigits = $var;

        return $this;
    }

}

