<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Response to the ProtoOAGetTrendbarsReq request. 
 *
 * Generated from protobuf message <code>ProtoOAGetTrendbarsRes</code>
 */
class ProtoOAGetTrendbarsRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * Specifies period of trend bar series (e.g. M1, M10, etc.).
     *
     * Generated from protobuf field <code>.ProtoOATrendbarPeriod period = 3;</code>
     */
    protected $period = 0;
    /**
     * Simply don't use this field, as your original request already contains toTimestamp.
     *
     * Generated from protobuf field <code>int64 timestamp = 4;</code>
     */
    protected $timestamp = 0;
    /**
     * The list of trend bars.
     *
     * Generated from protobuf field <code>repeated .ProtoOATrendbar trendbar = 5;</code>
     */
    private $trendbar;
    /**
     * Unique identifier of the Symbol in cTrader platform.
     *
     * Generated from protobuf field <code>int64 symbolId = 6;</code>
     */
    protected $symbolId = 0;
    /**
     * If TRUE then the number of records by filter is larger than chunkSize, the response contains the number of records that is equal to chunkSize.
     *
     * Generated from protobuf field <code>bool hasMore = 7;</code>
     */
    protected $hasMore = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type int $period
     *           Specifies period of trend bar series (e.g. M1, M10, etc.).
     *     @type int|string $timestamp
     *           Simply don't use this field, as your original request already contains toTimestamp.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOATrendbar[]|\Google\Protobuf\Internal\RepeatedField $trendbar
     *           The list of trend bars.
     *     @type int|string $symbolId
     *           Unique identifier of the Symbol in cTrader platform.
     *     @type bool $hasMore
     *           If TRUE then the number of records by filter is larger than chunkSize, the response contains the number of records that is equal to chunkSize.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * Specifies period of trend bar series (e.g. M1, M10, etc.).
     *
     * Generated from protobuf field <code>.ProtoOATrendbarPeriod period = 3;</code>
     * @return int
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     * Specifies period of trend bar series (e.g. M1, M10, etc.).
     *
     * Generated from protobuf field <code>.ProtoOATrendbarPeriod period = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPeriod($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOATrendbarPeriod::class);
        $this->period = $var;

        return $this;
    }

    /**
     * Simply don't use this field, as your original request already contains toTimestamp.
     *
     * Generated from protobuf field <code>int64 timestamp = 4;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Simply don't use this field, as your original request already contains toTimestamp.
     *
     * Generated from protobuf field <code>int64 timestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * The list of trend bars.
     *
     * Generated from protobuf field <code>repeated .ProtoOATrendbar trendbar = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTrendbar()
    {
        return $this->trendbar;
    }

    /**
     * The list of trend bars.
     *
     * Generated from protobuf field <code>repeated .ProtoOATrendbar trendbar = 5;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOATrendbar[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTrendbar($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOATrendbar::class);
        $this->trendbar = $arr;

        return $this;
    }

    /**
     * Unique identifier of the Symbol in cTrader platform.
     *
     * Generated from protobuf field <code>int64 symbolId = 6;</code>
     * @return int|string
     */
    public function getSymbolId()
    {
        return $this->symbolId;
    }

    /**
     * Unique identifier of the Symbol in cTrader platform.
     *
     * Generated from protobuf field <code>int64 symbolId = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSymbolId($var)
    {
        GPBUtil::checkInt64($var);
        $this->symbolId = $var;

        return $this;
    }

    /**
     * If TRUE then the number of records by filter is larger than chunkSize, the response contains the number of records that is equal to chunkSize.
     *
     * Generated from protobuf field <code>bool hasMore = 7;</code>
     * @return bool
     */
    public function getHasMore()
    {
        return $this->hasMore;
    }

    /**
     * If TRUE then the number of records by filter is larger than chunkSize, the response contains the number of records that is equal to chunkSize.
     *
     * Generated from protobuf field <code>bool hasMore = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasMore($var)
    {
        GPBUtil::checkBool($var);
        $this->hasMore = $var;

        return $this;
    }

}

