<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Position status ENUM. 
 *
 * Protobuf type <code>ProtoOAPositionStatus</code>
 */
class ProtoOAPositionStatus
{
    /**
     * Generated from protobuf enum <code>POSITION_STATUS_UNKNOWN = 0;</code>
     */
    const POSITION_STATUS_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>POSITION_STATUS_OPEN = 1;</code>
     */
    const POSITION_STATUS_OPEN = 1;
    /**
     * Generated from protobuf enum <code>POSITION_STATUS_CLOSED = 2;</code>
     */
    const POSITION_STATUS_CLOSED = 2;
    /**
     * Empty position is created for pending order.
     *
     * Generated from protobuf enum <code>POSITION_STATUS_CREATED = 3;</code>
     */
    const POSITION_STATUS_CREATED = 3;
    /**
     * Generated from protobuf enum <code>POSITION_STATUS_ERROR = 4;</code>
     */
    const POSITION_STATUS_ERROR = 4;

    private static $valueToName = [
        self::POSITION_STATUS_UNKNOWN => 'POSITION_STATUS_UNKNOWN',
        self::POSITION_STATUS_OPEN => 'POSITION_STATUS_OPEN',
        self::POSITION_STATUS_CLOSED => 'POSITION_STATUS_CLOSED',
        self::POSITION_STATUS_CREATED => 'POSITION_STATUS_CREATED',
        self::POSITION_STATUS_ERROR => 'POSITION_STATUS_ERROR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

