<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Trade position entity. 
 *
 * Generated from protobuf message <code>ProtoOAPosition</code>
 */
class ProtoOAPosition extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique ID of the position. Note: trader might have two positions with the same id if positions are taken from accounts from different brokers.
     *
     * Generated from protobuf field <code>int64 positionId = 1;</code>
     */
    protected $positionId = 0;
    /**
     * Position details. See ProtoOATradeData for details.
     *
     * Generated from protobuf field <code>.ProtoOATradeData tradeData = 2;</code>
     */
    protected $tradeData = null;
    /**
     * Current status of the position.
     *
     * Generated from protobuf field <code>.ProtoOAPositionStatus positionStatus = 3;</code>
     */
    protected $positionStatus = 0;
    /**
     * Total amount of charged swap on open position.
     *
     * Generated from protobuf field <code>int64 swap = 4;</code>
     */
    protected $swap = 0;
    /**
     * VWAP price of the position based on all executions (orders) linked to the position.
     *
     * Generated from protobuf field <code>double price = 5;</code>
     */
    protected $price = 0.0;
    /**
     * Current stop loss price.
     *
     * Generated from protobuf field <code>double stopLoss = 6;</code>
     */
    protected $stopLoss = 0.0;
    /**
     * Current take profit price.
     *
     * Generated from protobuf field <code>double takeProfit = 7;</code>
     */
    protected $takeProfit = 0.0;
    /**
     * The Unix time in milliseconds of the last change of the position, including amend SL/TP of the position, execution of related order, cancel or related order, etc.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 8;</code>
     */
    protected $utcLastUpdateTimestamp = 0;
    /**
     * Current unrealized commission related to the position.
     *
     * Generated from protobuf field <code>int64 commission = 9;</code>
     */
    protected $commission = 0;
    /**
     * Rate for used margin computation. Represented as Base/Deposit.
     *
     * Generated from protobuf field <code>double marginRate = 10;</code>
     */
    protected $marginRate = 0.0;
    /**
     * Amount of unrealized commission related to following of strategy provider.
     *
     * Generated from protobuf field <code>int64 mirroringCommission = 11;</code>
     */
    protected $mirroringCommission = 0;
    /**
     * If TRUE then position's stop loss is guaranteedStopLoss.
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 12;</code>
     */
    protected $guaranteedStopLoss = false;
    /**
     * Amount of margin used for the position in deposit currency.
     *
     * Generated from protobuf field <code>uint64 usedMargin = 13;</code>
     */
    protected $usedMargin = 0;
    /**
     * Stop trigger method for SL/TP of the position.
     *
     * Generated from protobuf field <code>.ProtoOAOrderTriggerMethod stopLossTriggerMethod = 14;</code>
     */
    protected $stopLossTriggerMethod = 0;
    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects swap, commission, mirroringCommission, usedMargin.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 15;</code>
     */
    protected $moneyDigits = 0;
    /**
     *If TRUE then the Trailing Stop Loss is applied.
     *
     * Generated from protobuf field <code>bool trailingStopLoss = 16;</code>
     */
    protected $trailingStopLoss = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $positionId
     *           The unique ID of the position. Note: trader might have two positions with the same id if positions are taken from accounts from different brokers.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOATradeData $tradeData
     *           Position details. See ProtoOATradeData for details.
     *     @type int $positionStatus
     *           Current status of the position.
     *     @type int|string $swap
     *           Total amount of charged swap on open position.
     *     @type float $price
     *           VWAP price of the position based on all executions (orders) linked to the position.
     *     @type float $stopLoss
     *           Current stop loss price.
     *     @type float $takeProfit
     *           Current take profit price.
     *     @type int|string $utcLastUpdateTimestamp
     *           The Unix time in milliseconds of the last change of the position, including amend SL/TP of the position, execution of related order, cancel or related order, etc.
     *     @type int|string $commission
     *           Current unrealized commission related to the position.
     *     @type float $marginRate
     *           Rate for used margin computation. Represented as Base/Deposit.
     *     @type int|string $mirroringCommission
     *           Amount of unrealized commission related to following of strategy provider.
     *     @type bool $guaranteedStopLoss
     *           If TRUE then position's stop loss is guaranteedStopLoss.
     *     @type int|string $usedMargin
     *           Amount of margin used for the position in deposit currency.
     *     @type int $stopLossTriggerMethod
     *           Stop trigger method for SL/TP of the position.
     *     @type int $moneyDigits
     *           Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects swap, commission, mirroringCommission, usedMargin.
     *     @type bool $trailingStopLoss
     *          If TRUE then the Trailing Stop Loss is applied.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique ID of the position. Note: trader might have two positions with the same id if positions are taken from accounts from different brokers.
     *
     * Generated from protobuf field <code>int64 positionId = 1;</code>
     * @return int|string
     */
    public function getPositionId()
    {
        return $this->positionId;
    }

    /**
     * The unique ID of the position. Note: trader might have two positions with the same id if positions are taken from accounts from different brokers.
     *
     * Generated from protobuf field <code>int64 positionId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPositionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->positionId = $var;

        return $this;
    }

    /**
     * Position details. See ProtoOATradeData for details.
     *
     * Generated from protobuf field <code>.ProtoOATradeData tradeData = 2;</code>
     * @return \SocialiteProviders\Ctrader\Protobuf\ProtoOATradeData
     */
    public function getTradeData()
    {
        return $this->tradeData;
    }

    /**
     * Position details. See ProtoOATradeData for details.
     *
     * Generated from protobuf field <code>.ProtoOATradeData tradeData = 2;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOATradeData $var
     * @return $this
     */
    public function setTradeData($var)
    {
        GPBUtil::checkMessage($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOATradeData::class);
        $this->tradeData = $var;

        return $this;
    }

    /**
     * Current status of the position.
     *
     * Generated from protobuf field <code>.ProtoOAPositionStatus positionStatus = 3;</code>
     * @return int
     */
    public function getPositionStatus()
    {
        return $this->positionStatus;
    }

    /**
     * Current status of the position.
     *
     * Generated from protobuf field <code>.ProtoOAPositionStatus positionStatus = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPositionStatus($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPositionStatus::class);
        $this->positionStatus = $var;

        return $this;
    }

    /**
     * Total amount of charged swap on open position.
     *
     * Generated from protobuf field <code>int64 swap = 4;</code>
     * @return int|string
     */
    public function getSwap()
    {
        return $this->swap;
    }

    /**
     * Total amount of charged swap on open position.
     *
     * Generated from protobuf field <code>int64 swap = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSwap($var)
    {
        GPBUtil::checkInt64($var);
        $this->swap = $var;

        return $this;
    }

    /**
     * VWAP price of the position based on all executions (orders) linked to the position.
     *
     * Generated from protobuf field <code>double price = 5;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * VWAP price of the position based on all executions (orders) linked to the position.
     *
     * Generated from protobuf field <code>double price = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->price = $var;

        return $this;
    }

    /**
     * Current stop loss price.
     *
     * Generated from protobuf field <code>double stopLoss = 6;</code>
     * @return float
     */
    public function getStopLoss()
    {
        return $this->stopLoss;
    }

    /**
     * Current stop loss price.
     *
     * Generated from protobuf field <code>double stopLoss = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setStopLoss($var)
    {
        GPBUtil::checkDouble($var);
        $this->stopLoss = $var;

        return $this;
    }

    /**
     * Current take profit price.
     *
     * Generated from protobuf field <code>double takeProfit = 7;</code>
     * @return float
     */
    public function getTakeProfit()
    {
        return $this->takeProfit;
    }

    /**
     * Current take profit price.
     *
     * Generated from protobuf field <code>double takeProfit = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setTakeProfit($var)
    {
        GPBUtil::checkDouble($var);
        $this->takeProfit = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds of the last change of the position, including amend SL/TP of the position, execution of related order, cancel or related order, etc.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 8;</code>
     * @return int|string
     */
    public function getUtcLastUpdateTimestamp()
    {
        return $this->utcLastUpdateTimestamp;
    }

    /**
     * The Unix time in milliseconds of the last change of the position, including amend SL/TP of the position, execution of related order, cancel or related order, etc.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUtcLastUpdateTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->utcLastUpdateTimestamp = $var;

        return $this;
    }

    /**
     * Current unrealized commission related to the position.
     *
     * Generated from protobuf field <code>int64 commission = 9;</code>
     * @return int|string
     */
    public function getCommission()
    {
        return $this->commission;
    }

    /**
     * Current unrealized commission related to the position.
     *
     * Generated from protobuf field <code>int64 commission = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCommission($var)
    {
        GPBUtil::checkInt64($var);
        $this->commission = $var;

        return $this;
    }

    /**
     * Rate for used margin computation. Represented as Base/Deposit.
     *
     * Generated from protobuf field <code>double marginRate = 10;</code>
     * @return float
     */
    public function getMarginRate()
    {
        return $this->marginRate;
    }

    /**
     * Rate for used margin computation. Represented as Base/Deposit.
     *
     * Generated from protobuf field <code>double marginRate = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setMarginRate($var)
    {
        GPBUtil::checkDouble($var);
        $this->marginRate = $var;

        return $this;
    }

    /**
     * Amount of unrealized commission related to following of strategy provider.
     *
     * Generated from protobuf field <code>int64 mirroringCommission = 11;</code>
     * @return int|string
     */
    public function getMirroringCommission()
    {
        return $this->mirroringCommission;
    }

    /**
     * Amount of unrealized commission related to following of strategy provider.
     *
     * Generated from protobuf field <code>int64 mirroringCommission = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMirroringCommission($var)
    {
        GPBUtil::checkInt64($var);
        $this->mirroringCommission = $var;

        return $this;
    }

    /**
     * If TRUE then position's stop loss is guaranteedStopLoss.
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 12;</code>
     * @return bool
     */
    public function getGuaranteedStopLoss()
    {
        return $this->guaranteedStopLoss;
    }

    /**
     * If TRUE then position's stop loss is guaranteedStopLoss.
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setGuaranteedStopLoss($var)
    {
        GPBUtil::checkBool($var);
        $this->guaranteedStopLoss = $var;

        return $this;
    }

    /**
     * Amount of margin used for the position in deposit currency.
     *
     * Generated from protobuf field <code>uint64 usedMargin = 13;</code>
     * @return int|string
     */
    public function getUsedMargin()
    {
        return $this->usedMargin;
    }

    /**
     * Amount of margin used for the position in deposit currency.
     *
     * Generated from protobuf field <code>uint64 usedMargin = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUsedMargin($var)
    {
        GPBUtil::checkUint64($var);
        $this->usedMargin = $var;

        return $this;
    }

    /**
     * Stop trigger method for SL/TP of the position.
     *
     * Generated from protobuf field <code>.ProtoOAOrderTriggerMethod stopLossTriggerMethod = 14;</code>
     * @return int
     */
    public function getStopLossTriggerMethod()
    {
        return $this->stopLossTriggerMethod;
    }

    /**
     * Stop trigger method for SL/TP of the position.
     *
     * Generated from protobuf field <code>.ProtoOAOrderTriggerMethod stopLossTriggerMethod = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setStopLossTriggerMethod($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrderTriggerMethod::class);
        $this->stopLossTriggerMethod = $var;

        return $this;
    }

    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects swap, commission, mirroringCommission, usedMargin.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 15;</code>
     * @return int
     */
    public function getMoneyDigits()
    {
        return $this->moneyDigits;
    }

    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects swap, commission, mirroringCommission, usedMargin.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setMoneyDigits($var)
    {
        GPBUtil::checkUint32($var);
        $this->moneyDigits = $var;

        return $this;
    }

    /**
     *If TRUE then the Trailing Stop Loss is applied.
     *
     * Generated from protobuf field <code>bool trailingStopLoss = 16;</code>
     * @return bool
     */
    public function getTrailingStopLoss()
    {
        return $this->trailingStopLoss;
    }

    /**
     *If TRUE then the Trailing Stop Loss is applied.
     *
     * Generated from protobuf field <code>bool trailingStopLoss = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setTrailingStopLoss($var)
    {
        GPBUtil::checkBool($var);
        $this->trailingStopLoss = $var;

        return $this;
    }

}

