<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Bonus deposit/withdrawal entity. 
 *
 * Generated from protobuf message <code>ProtoOABonusDepositWithdraw</code>
 */
class ProtoOABonusDepositWithdraw extends \Google\Protobuf\Internal\Message
{
    /**
     * Type of the operation. Deposit/Withdrawal.
     *
     * Generated from protobuf field <code>.ProtoOAChangeBonusType operationType = 1;</code>
     */
    protected $operationType = 0;
    /**
     * The unique ID of the bonus deposit/withdrawal operation.
     *
     * Generated from protobuf field <code>int64 bonusHistoryId = 2;</code>
     */
    protected $bonusHistoryId = 0;
    /**
     * Total amount of broker's bonus after the operation.
     *
     * Generated from protobuf field <code>int64 managerBonus = 3;</code>
     */
    protected $managerBonus = 0;
    /**
     * Amount of bonus deposited/withdrew by manager.
     *
     * Generated from protobuf field <code>int64 managerDelta = 4;</code>
     */
    protected $managerDelta = 0;
    /**
     * Total amount of introducing broker's bonus after the operation.
     *
     * Generated from protobuf field <code>int64 ibBonus = 5;</code>
     */
    protected $ibBonus = 0;
    /**
     * Amount of bonus deposited/withdrew by introducing broker.
     *
     * Generated from protobuf field <code>int64 ibDelta = 6;</code>
     */
    protected $ibDelta = 0;
    /**
     * The Unix time in milliseconds when the bonus operation was executed.
     *
     * Generated from protobuf field <code>int64 changeBonusTimestamp = 7;</code>
     */
    protected $changeBonusTimestamp = 0;
    /**
     * Note added to operation. Visible to the trader.
     *
     * Generated from protobuf field <code>string externalNote = 8;</code>
     */
    protected $externalNote = '';
    /**
     * ID of introducing broker who deposited/withdrew bonus.
     *
     * Generated from protobuf field <code>int64 introducingBrokerId = 9;</code>
     */
    protected $introducingBrokerId = 0;
    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects managerBonus, managerDelta, ibBonus, ibDelta.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 10;</code>
     */
    protected $moneyDigits = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $operationType
     *           Type of the operation. Deposit/Withdrawal.
     *     @type int|string $bonusHistoryId
     *           The unique ID of the bonus deposit/withdrawal operation.
     *     @type int|string $managerBonus
     *           Total amount of broker's bonus after the operation.
     *     @type int|string $managerDelta
     *           Amount of bonus deposited/withdrew by manager.
     *     @type int|string $ibBonus
     *           Total amount of introducing broker's bonus after the operation.
     *     @type int|string $ibDelta
     *           Amount of bonus deposited/withdrew by introducing broker.
     *     @type int|string $changeBonusTimestamp
     *           The Unix time in milliseconds when the bonus operation was executed.
     *     @type string $externalNote
     *           Note added to operation. Visible to the trader.
     *     @type int|string $introducingBrokerId
     *           ID of introducing broker who deposited/withdrew bonus.
     *     @type int $moneyDigits
     *           Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects managerBonus, managerDelta, ibBonus, ibDelta.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Type of the operation. Deposit/Withdrawal.
     *
     * Generated from protobuf field <code>.ProtoOAChangeBonusType operationType = 1;</code>
     * @return int
     */
    public function getOperationType()
    {
        return $this->operationType;
    }

    /**
     * Type of the operation. Deposit/Withdrawal.
     *
     * Generated from protobuf field <code>.ProtoOAChangeBonusType operationType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setOperationType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAChangeBonusType::class);
        $this->operationType = $var;

        return $this;
    }

    /**
     * The unique ID of the bonus deposit/withdrawal operation.
     *
     * Generated from protobuf field <code>int64 bonusHistoryId = 2;</code>
     * @return int|string
     */
    public function getBonusHistoryId()
    {
        return $this->bonusHistoryId;
    }

    /**
     * The unique ID of the bonus deposit/withdrawal operation.
     *
     * Generated from protobuf field <code>int64 bonusHistoryId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBonusHistoryId($var)
    {
        GPBUtil::checkInt64($var);
        $this->bonusHistoryId = $var;

        return $this;
    }

    /**
     * Total amount of broker's bonus after the operation.
     *
     * Generated from protobuf field <code>int64 managerBonus = 3;</code>
     * @return int|string
     */
    public function getManagerBonus()
    {
        return $this->managerBonus;
    }

    /**
     * Total amount of broker's bonus after the operation.
     *
     * Generated from protobuf field <code>int64 managerBonus = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setManagerBonus($var)
    {
        GPBUtil::checkInt64($var);
        $this->managerBonus = $var;

        return $this;
    }

    /**
     * Amount of bonus deposited/withdrew by manager.
     *
     * Generated from protobuf field <code>int64 managerDelta = 4;</code>
     * @return int|string
     */
    public function getManagerDelta()
    {
        return $this->managerDelta;
    }

    /**
     * Amount of bonus deposited/withdrew by manager.
     *
     * Generated from protobuf field <code>int64 managerDelta = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setManagerDelta($var)
    {
        GPBUtil::checkInt64($var);
        $this->managerDelta = $var;

        return $this;
    }

    /**
     * Total amount of introducing broker's bonus after the operation.
     *
     * Generated from protobuf field <code>int64 ibBonus = 5;</code>
     * @return int|string
     */
    public function getIbBonus()
    {
        return $this->ibBonus;
    }

    /**
     * Total amount of introducing broker's bonus after the operation.
     *
     * Generated from protobuf field <code>int64 ibBonus = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIbBonus($var)
    {
        GPBUtil::checkInt64($var);
        $this->ibBonus = $var;

        return $this;
    }

    /**
     * Amount of bonus deposited/withdrew by introducing broker.
     *
     * Generated from protobuf field <code>int64 ibDelta = 6;</code>
     * @return int|string
     */
    public function getIbDelta()
    {
        return $this->ibDelta;
    }

    /**
     * Amount of bonus deposited/withdrew by introducing broker.
     *
     * Generated from protobuf field <code>int64 ibDelta = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIbDelta($var)
    {
        GPBUtil::checkInt64($var);
        $this->ibDelta = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds when the bonus operation was executed.
     *
     * Generated from protobuf field <code>int64 changeBonusTimestamp = 7;</code>
     * @return int|string
     */
    public function getChangeBonusTimestamp()
    {
        return $this->changeBonusTimestamp;
    }

    /**
     * The Unix time in milliseconds when the bonus operation was executed.
     *
     * Generated from protobuf field <code>int64 changeBonusTimestamp = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setChangeBonusTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->changeBonusTimestamp = $var;

        return $this;
    }

    /**
     * Note added to operation. Visible to the trader.
     *
     * Generated from protobuf field <code>string externalNote = 8;</code>
     * @return string
     */
    public function getExternalNote()
    {
        return $this->externalNote;
    }

    /**
     * Note added to operation. Visible to the trader.
     *
     * Generated from protobuf field <code>string externalNote = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setExternalNote($var)
    {
        GPBUtil::checkString($var, True);
        $this->externalNote = $var;

        return $this;
    }

    /**
     * ID of introducing broker who deposited/withdrew bonus.
     *
     * Generated from protobuf field <code>int64 introducingBrokerId = 9;</code>
     * @return int|string
     */
    public function getIntroducingBrokerId()
    {
        return $this->introducingBrokerId;
    }

    /**
     * ID of introducing broker who deposited/withdrew bonus.
     *
     * Generated from protobuf field <code>int64 introducingBrokerId = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntroducingBrokerId($var)
    {
        GPBUtil::checkInt64($var);
        $this->introducingBrokerId = $var;

        return $this;
    }

    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects managerBonus, managerDelta, ibBonus, ibDelta.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 10;</code>
     * @return int
     */
    public function getMoneyDigits()
    {
        return $this->moneyDigits;
    }

    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects managerBonus, managerDelta, ibBonus, ibDelta.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setMoneyDigits($var)
    {
        GPBUtil::checkUint32($var);
        $this->moneyDigits = $var;

        return $this;
    }

}

