<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Request for getting the margin estimate according to leverage profiles. Can be used before sending a new order request. This doesn't consider ACCORDING_TO_GSL margin calculation type, as this calculation is trivial: usedMargin = (VWAP price of the position - GSL price) * volume * Quote2Deposit. 
 *
 * Generated from protobuf message <code>ProtoOAExpectedMarginReq</code>
 */
class ProtoOAExpectedMarginReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * Unique identifier of the Symbol in cTrader platform.
     *
     * Generated from protobuf field <code>int64 symbolId = 3;</code>
     */
    protected $symbolId = 0;
    /**
     * Volume represented in 0.01 of a unit (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>repeated int64 volume = 4;</code>
     */
    private $volume;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type int|string $symbolId
     *           Unique identifier of the Symbol in cTrader platform.
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $volume
     *           Volume represented in 0.01 of a unit (e.g. 1000 in protocol means 10.00 units).
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * Unique identifier of the Symbol in cTrader platform.
     *
     * Generated from protobuf field <code>int64 symbolId = 3;</code>
     * @return int|string
     */
    public function getSymbolId()
    {
        return $this->symbolId;
    }

    /**
     * Unique identifier of the Symbol in cTrader platform.
     *
     * Generated from protobuf field <code>int64 symbolId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSymbolId($var)
    {
        GPBUtil::checkInt64($var);
        $this->symbolId = $var;

        return $this;
    }

    /**
     * Volume represented in 0.01 of a unit (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>repeated int64 volume = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Volume represented in 0.01 of a unit (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>repeated int64 volume = 4;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVolume($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->volume = $arr;

        return $this;
    }

}

