<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Balance operation entity. Covers all cash movement operations related to account, trading, IB operations, mirroring, etc. 
 *
 * Protobuf type <code>ProtoOAChangeBalanceType</code>
 */
class ProtoOAChangeBalanceType
{
    /**
     * Cash deposit.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT = 0;</code>
     */
    const BALANCE_DEPOSIT = 0;
    /**
     * Cash withdrawal.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW = 1;</code>
     */
    const BALANCE_WITHDRAW = 1;
    /**
     * Received mirroring commission.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_STRATEGY_COMMISSION_INNER = 3;</code>
     */
    const BALANCE_DEPOSIT_STRATEGY_COMMISSION_INNER = 3;
    /**
     * Paid mirroring commission.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_STRATEGY_COMMISSION_INNER = 4;</code>
     */
    const BALANCE_WITHDRAW_STRATEGY_COMMISSION_INNER = 4;
    /**
     * For IB account. Commissions paid by trader.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_IB_COMMISSIONS = 5;</code>
     */
    const BALANCE_DEPOSIT_IB_COMMISSIONS = 5;
    /**
     * For IB account. Withdrawal of commissions shared with broker.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE = 6;</code>
     */
    const BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE = 6;
    /**
     * For IB account. Commissions paid by sub-ibs.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_SUB_IB = 7;</code>
     */
    const BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_SUB_IB = 7;
    /**
     * For IB account. Commissions paid by broker.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_BROKER = 8;</code>
     */
    const BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_BROKER = 8;
    /**
     * Deposit rebate for trading volume for period.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_REBATE = 9;</code>
     */
    const BALANCE_DEPOSIT_REBATE = 9;
    /**
     * Withdrawal of rebate.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_REBATE = 10;</code>
     */
    const BALANCE_WITHDRAW_REBATE = 10;
    /**
     * Mirroring commission.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_STRATEGY_COMMISSION_OUTER = 11;</code>
     */
    const BALANCE_DEPOSIT_STRATEGY_COMMISSION_OUTER = 11;
    /**
     * Mirroring commission.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_STRATEGY_COMMISSION_OUTER = 12;</code>
     */
    const BALANCE_WITHDRAW_STRATEGY_COMMISSION_OUTER = 12;
    /**
     * For IB account. Share commission with the Broker.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_BONUS_COMPENSATION = 13;</code>
     */
    const BALANCE_WITHDRAW_BONUS_COMPENSATION = 13;
    /**
     * IB commissions.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE_TO_BROKER = 14;</code>
     */
    const BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE_TO_BROKER = 14;
    /**
     * Deposit dividends payments.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_DIVIDENDS = 15;</code>
     */
    const BALANCE_DEPOSIT_DIVIDENDS = 15;
    /**
     * Negative dividend charge for short position.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_DIVIDENDS = 16;</code>
     */
    const BALANCE_WITHDRAW_DIVIDENDS = 16;
    /**
     * Charge for guaranteedStopLoss.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_GSL_CHARGE = 17;</code>
     */
    const BALANCE_WITHDRAW_GSL_CHARGE = 17;
    /**
     * Charge of rollover fee for Shariah compliant accounts.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_ROLLOVER = 18;</code>
     */
    const BALANCE_WITHDRAW_ROLLOVER = 18;
    /**
     * Broker's operation to deposit bonus.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_NONWITHDRAWABLE_BONUS = 19;</code>
     */
    const BALANCE_DEPOSIT_NONWITHDRAWABLE_BONUS = 19;
    /**
     * Broker's operation to withdrawal bonus.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_NONWITHDRAWABLE_BONUS = 20;</code>
     */
    const BALANCE_WITHDRAW_NONWITHDRAWABLE_BONUS = 20;
    /**
     * Deposits of negative SWAP.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_SWAP = 21;</code>
     */
    const BALANCE_DEPOSIT_SWAP = 21;
    /**
     * SWAP charges.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_SWAP = 22;</code>
     */
    const BALANCE_WITHDRAW_SWAP = 22;
    /**
     * Mirroring commission.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_MANAGEMENT_FEE = 27;</code>
     */
    const BALANCE_DEPOSIT_MANAGEMENT_FEE = 27;
    /**
     * Mirroring commission. Deprecated since 7.1 in favor of BALANCE_WITHDRAW_COPY_FEE (34).
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_MANAGEMENT_FEE = 28;</code>
     */
    const BALANCE_WITHDRAW_MANAGEMENT_FEE = 28;
    /**
     * Mirroring commission.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_PERFORMANCE_FEE = 29;</code>
     */
    const BALANCE_DEPOSIT_PERFORMANCE_FEE = 29;
    /**
     * Withdraw for subaccount creation (cTrader Copy).
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_FOR_SUBACCOUNT = 30;</code>
     */
    const BALANCE_WITHDRAW_FOR_SUBACCOUNT = 30;
    /**
     * Deposit to subaccount on creation (cTrader Copy).
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_TO_SUBACCOUNT = 31;</code>
     */
    const BALANCE_DEPOSIT_TO_SUBACCOUNT = 31;
    /**
     * Manual user's withdraw from subaccount (cTrader Copy), to parent account.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_FROM_SUBACCOUNT = 32;</code>
     */
    const BALANCE_WITHDRAW_FROM_SUBACCOUNT = 32;
    /**
     * Manual user's deposit to subaccount (cTrader Copy), from parent account.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_FROM_SUBACCOUNT = 33;</code>
     */
    const BALANCE_DEPOSIT_FROM_SUBACCOUNT = 33;
    /**
     * Withdrawal fees to Strategy Provider.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_COPY_FEE = 34;</code>
     */
    const BALANCE_WITHDRAW_COPY_FEE = 34;
    /**
     * Withdraw of inactivity fee from the balance.
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_INACTIVITY_FEE = 35;</code>
     */
    const BALANCE_WITHDRAW_INACTIVITY_FEE = 35;
    /**
     * Deposit within the same server (from another account).
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_TRANSFER = 36;</code>
     */
    const BALANCE_DEPOSIT_TRANSFER = 36;
    /**
     * Withdraw within the same server (to another account).
     *
     * Generated from protobuf enum <code>BALANCE_WITHDRAW_TRANSFER = 37;</code>
     */
    const BALANCE_WITHDRAW_TRANSFER = 37;
    /**
     * Bonus being converted from virtual bonus to real deposit.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_CONVERTED_BONUS = 38;</code>
     */
    const BALANCE_DEPOSIT_CONVERTED_BONUS = 38;
    /**
     * Applies if negative balance protection is configured by broker, should make balance = 0.
     *
     * Generated from protobuf enum <code>BALANCE_DEPOSIT_NEGATIVE_BALANCE_PROTECTION = 39;</code>
     */
    const BALANCE_DEPOSIT_NEGATIVE_BALANCE_PROTECTION = 39;

    private static $valueToName = [
        self::BALANCE_DEPOSIT => 'BALANCE_DEPOSIT',
        self::BALANCE_WITHDRAW => 'BALANCE_WITHDRAW',
        self::BALANCE_DEPOSIT_STRATEGY_COMMISSION_INNER => 'BALANCE_DEPOSIT_STRATEGY_COMMISSION_INNER',
        self::BALANCE_WITHDRAW_STRATEGY_COMMISSION_INNER => 'BALANCE_WITHDRAW_STRATEGY_COMMISSION_INNER',
        self::BALANCE_DEPOSIT_IB_COMMISSIONS => 'BALANCE_DEPOSIT_IB_COMMISSIONS',
        self::BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE => 'BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE',
        self::BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_SUB_IB => 'BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_SUB_IB',
        self::BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_BROKER => 'BALANCE_DEPOSIT_IB_SHARED_PERCENTAGE_FROM_BROKER',
        self::BALANCE_DEPOSIT_REBATE => 'BALANCE_DEPOSIT_REBATE',
        self::BALANCE_WITHDRAW_REBATE => 'BALANCE_WITHDRAW_REBATE',
        self::BALANCE_DEPOSIT_STRATEGY_COMMISSION_OUTER => 'BALANCE_DEPOSIT_STRATEGY_COMMISSION_OUTER',
        self::BALANCE_WITHDRAW_STRATEGY_COMMISSION_OUTER => 'BALANCE_WITHDRAW_STRATEGY_COMMISSION_OUTER',
        self::BALANCE_WITHDRAW_BONUS_COMPENSATION => 'BALANCE_WITHDRAW_BONUS_COMPENSATION',
        self::BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE_TO_BROKER => 'BALANCE_WITHDRAW_IB_SHARED_PERCENTAGE_TO_BROKER',
        self::BALANCE_DEPOSIT_DIVIDENDS => 'BALANCE_DEPOSIT_DIVIDENDS',
        self::BALANCE_WITHDRAW_DIVIDENDS => 'BALANCE_WITHDRAW_DIVIDENDS',
        self::BALANCE_WITHDRAW_GSL_CHARGE => 'BALANCE_WITHDRAW_GSL_CHARGE',
        self::BALANCE_WITHDRAW_ROLLOVER => 'BALANCE_WITHDRAW_ROLLOVER',
        self::BALANCE_DEPOSIT_NONWITHDRAWABLE_BONUS => 'BALANCE_DEPOSIT_NONWITHDRAWABLE_BONUS',
        self::BALANCE_WITHDRAW_NONWITHDRAWABLE_BONUS => 'BALANCE_WITHDRAW_NONWITHDRAWABLE_BONUS',
        self::BALANCE_DEPOSIT_SWAP => 'BALANCE_DEPOSIT_SWAP',
        self::BALANCE_WITHDRAW_SWAP => 'BALANCE_WITHDRAW_SWAP',
        self::BALANCE_DEPOSIT_MANAGEMENT_FEE => 'BALANCE_DEPOSIT_MANAGEMENT_FEE',
        self::BALANCE_WITHDRAW_MANAGEMENT_FEE => 'BALANCE_WITHDRAW_MANAGEMENT_FEE',
        self::BALANCE_DEPOSIT_PERFORMANCE_FEE => 'BALANCE_DEPOSIT_PERFORMANCE_FEE',
        self::BALANCE_WITHDRAW_FOR_SUBACCOUNT => 'BALANCE_WITHDRAW_FOR_SUBACCOUNT',
        self::BALANCE_DEPOSIT_TO_SUBACCOUNT => 'BALANCE_DEPOSIT_TO_SUBACCOUNT',
        self::BALANCE_WITHDRAW_FROM_SUBACCOUNT => 'BALANCE_WITHDRAW_FROM_SUBACCOUNT',
        self::BALANCE_DEPOSIT_FROM_SUBACCOUNT => 'BALANCE_DEPOSIT_FROM_SUBACCOUNT',
        self::BALANCE_WITHDRAW_COPY_FEE => 'BALANCE_WITHDRAW_COPY_FEE',
        self::BALANCE_WITHDRAW_INACTIVITY_FEE => 'BALANCE_WITHDRAW_INACTIVITY_FEE',
        self::BALANCE_DEPOSIT_TRANSFER => 'BALANCE_DEPOSIT_TRANSFER',
        self::BALANCE_WITHDRAW_TRANSFER => 'BALANCE_WITHDRAW_TRANSFER',
        self::BALANCE_DEPOSIT_CONVERTED_BONUS => 'BALANCE_DEPOSIT_CONVERTED_BONUS',
        self::BALANCE_DEPOSIT_NEGATIVE_BALANCE_PROTECTION => 'BALANCE_DEPOSIT_NEGATIVE_BALANCE_PROTECTION',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

