<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiCommonModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 * --- INTENSIVE COMMANDS 1 - 49
 * --- COMMON API 50 - 69
 *
 * Protobuf type <code>ProtoPayloadType</code>
 */
class ProtoPayloadType
{
    /**
     * Generated from protobuf enum <code>PROTO_PAYLOAD_TYPE_UNKNOWN = 0;</code>
     */
    const PROTO_PAYLOAD_TYPE_UNKNOWN = 0;
    /**
     * common intensive
     *
     * Generated from protobuf enum <code>PROTO_MESSAGE = 5;</code>
     */
    const PROTO_MESSAGE = 5;
    /**
     * common commands
     *
     * Generated from protobuf enum <code>ERROR_RES = 50;</code>
     */
    const ERROR_RES = 50;
    /**
     * Generated from protobuf enum <code>HEARTBEAT_EVENT = 51;</code>
     */
    const HEARTBEAT_EVENT = 51;

    private static array $valueToName = [
        self::PROTO_PAYLOAD_TYPE_UNKNOWN => 'PROTO_PAYLOAD_TYPE_UNKNOWN',
        self::PROTO_MESSAGE => 'PROTO_MESSAGE',
        self::ERROR_RES => 'ERROR_RES',
        self::HEARTBEAT_EVENT => 'HEARTBEAT_EVENT',
    ];

    public static function name($value): string
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

