<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Request for sending a new trading order. Allowed only if the accessToken has the "trade" permissions for the trading account. 
 *
 * Generated from protobuf message <code>ProtoOANewOrderReq</code>
 */
class ProtoOANewOrderReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * The unique identifier of the trader's account in cTrader platform.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * The unique identifier of a symbol in cTrader platform.
     *
     * Generated from protobuf field <code>int64 symbolId = 3;</code>
     */
    protected $symbolId = 0;
    /**
     * The type of an order - MARKET, LIMIT, STOP, MARKET_RANGE, STOP_LIMIT.
     *
     * Generated from protobuf field <code>.ProtoOAOrderType orderType = 4;</code>
     */
    protected $orderType = 0;
    /**
     * The trade direction - BUY or SELL.
     *
     * Generated from protobuf field <code>.ProtoOATradeSide tradeSide = 5;</code>
     */
    protected $tradeSide = 0;
    /**
     * The volume represented in 0.01 of a unit (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>int64 volume = 6;</code>
     */
    protected $volume = 0;
    /**
     * The limit price, can be specified for the LIMIT order only.
     *
     * Generated from protobuf field <code>double limitPrice = 7;</code>
     */
    protected $limitPrice = 0.0;
    /**
     * Stop Price, can be specified for the STOP and the STOP_LIMIT orders only.
     *
     * Generated from protobuf field <code>double stopPrice = 8;</code>
     */
    protected $stopPrice = 0.0;
    /**
     * The specific order execution or expiration instruction - GOOD_TILL_DATE, GOOD_TILL_CANCEL, IMMEDIATE_OR_CANCEL, FILL_OR_KILL, MARKET_ON_OPEN.
     *
     * Generated from protobuf field <code>.ProtoOATimeInForce timeInForce = 9;</code>
     */
    protected $timeInForce = 0;
    /**
     * The Unix time in milliseconds of Order expiration. Should be set for the Good Till Date orders.
     *
     * Generated from protobuf field <code>int64 expirationTimestamp = 10;</code>
     */
    protected $expirationTimestamp = 0;
    /**
     * The absolute Stop Loss price (1.23456 for example). Not supported for MARKET orders.
     *
     * Generated from protobuf field <code>double stopLoss = 11;</code>
     */
    protected $stopLoss = 0.0;
    /**
     * The absolute Take Profit price (1.23456 for example). Unsupported for MARKET orders.
     *
     * Generated from protobuf field <code>double takeProfit = 12;</code>
     */
    protected $takeProfit = 0.0;
    /**
     * User-specified comment. MaxLength = 512.
     *
     * Generated from protobuf field <code>string comment = 13;</code>
     */
    protected $comment = '';
    /**
     * Base price to calculate relative slippage price for MARKET_RANGE order.
     *
     * Generated from protobuf field <code>double baseSlippagePrice = 14;</code>
     */
    protected $baseSlippagePrice = 0.0;
    /**
     * Slippage distance for MARKET_RANGE and STOP_LIMIT order.
     *
     * Generated from protobuf field <code>int32 slippageInPoints = 15;</code>
     */
    protected $slippageInPoints = 0;
    /**
     * User-specified label. MaxLength = 100.
     *
     * Generated from protobuf field <code>string label = 16;</code>
     */
    protected $label = '';
    /**
     * Reference to the existing position if the Order is intended to modify it.
     *
     * Generated from protobuf field <code>int64 positionId = 17;</code>
     */
    protected $positionId = 0;
    /**
     * Optional user-specific clientOrderId (similar to FIX ClOrderID). MaxLength = 50.
     *
     * Generated from protobuf field <code>string clientOrderId = 18;</code>
     */
    protected $clientOrderId = '';
    /**
     * Relative Stop Loss that can be specified instead of the absolute as one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY stopLoss = entryPrice - relativeStopLoss, for SELL stopLoss = entryPrice + relativeStopLoss.
     *
     * Generated from protobuf field <code>int64 relativeStopLoss = 19;</code>
     */
    protected $relativeStopLoss = 0;
    /**
     * Relative Take Profit that can be specified instead of the absolute one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY takeProfit = entryPrice + relativeTakeProfit, for SELL takeProfit = entryPrice - relativeTakeProfit.
     *
     * Generated from protobuf field <code>int64 relativeTakeProfit = 20;</code>
     */
    protected $relativeTakeProfit = 0;
    /**
     * If TRUE then stopLoss is guaranteed. Required to be set to TRUE for the Limited Risk accounts (ProtoOATrader.isLimitedRisk=true).
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 21;</code>
     */
    protected $guaranteedStopLoss = false;
    /**
     * If TRUE then the Stop Loss is Trailing.
     *
     * Generated from protobuf field <code>bool trailingStopLoss = 22;</code>
     */
    protected $trailingStopLoss = false;
    /**
     * Trigger method for the STOP or the STOP_LIMIT pending order.
     *
     * Generated from protobuf field <code>.ProtoOAOrderTriggerMethod stopTriggerMethod = 23;</code>
     */
    protected $stopTriggerMethod = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           The unique identifier of the trader's account in cTrader platform.
     *     @type int|string $symbolId
     *           The unique identifier of a symbol in cTrader platform.
     *     @type int $orderType
     *           The type of an order - MARKET, LIMIT, STOP, MARKET_RANGE, STOP_LIMIT.
     *     @type int $tradeSide
     *           The trade direction - BUY or SELL.
     *     @type int|string $volume
     *           The volume represented in 0.01 of a unit (e.g. 1000 in protocol means 10.00 units).
     *     @type float $limitPrice
     *           The limit price, can be specified for the LIMIT order only.
     *     @type float $stopPrice
     *           Stop Price, can be specified for the STOP and the STOP_LIMIT orders only.
     *     @type int $timeInForce
     *           The specific order execution or expiration instruction - GOOD_TILL_DATE, GOOD_TILL_CANCEL, IMMEDIATE_OR_CANCEL, FILL_OR_KILL, MARKET_ON_OPEN.
     *     @type int|string $expirationTimestamp
     *           The Unix time in milliseconds of Order expiration. Should be set for the Good Till Date orders.
     *     @type float $stopLoss
     *           The absolute Stop Loss price (1.23456 for example). Not supported for MARKET orders.
     *     @type float $takeProfit
     *           The absolute Take Profit price (1.23456 for example). Unsupported for MARKET orders.
     *     @type string $comment
     *           User-specified comment. MaxLength = 512.
     *     @type float $baseSlippagePrice
     *           Base price to calculate relative slippage price for MARKET_RANGE order.
     *     @type int $slippageInPoints
     *           Slippage distance for MARKET_RANGE and STOP_LIMIT order.
     *     @type string $label
     *           User-specified label. MaxLength = 100.
     *     @type int|string $positionId
     *           Reference to the existing position if the Order is intended to modify it.
     *     @type string $clientOrderId
     *           Optional user-specific clientOrderId (similar to FIX ClOrderID). MaxLength = 50.
     *     @type int|string $relativeStopLoss
     *           Relative Stop Loss that can be specified instead of the absolute as one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY stopLoss = entryPrice - relativeStopLoss, for SELL stopLoss = entryPrice + relativeStopLoss.
     *     @type int|string $relativeTakeProfit
     *           Relative Take Profit that can be specified instead of the absolute one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY takeProfit = entryPrice + relativeTakeProfit, for SELL takeProfit = entryPrice - relativeTakeProfit.
     *     @type bool $guaranteedStopLoss
     *           If TRUE then stopLoss is guaranteed. Required to be set to TRUE for the Limited Risk accounts (ProtoOATrader.isLimitedRisk=true).
     *     @type bool $trailingStopLoss
     *           If TRUE then the Stop Loss is Trailing.
     *     @type int $stopTriggerMethod
     *           Trigger method for the STOP or the STOP_LIMIT pending order.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * The unique identifier of the trader's account in cTrader platform.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * The unique identifier of the trader's account in cTrader platform.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * The unique identifier of a symbol in cTrader platform.
     *
     * Generated from protobuf field <code>int64 symbolId = 3;</code>
     * @return int|string
     */
    public function getSymbolId()
    {
        return $this->symbolId;
    }

    /**
     * The unique identifier of a symbol in cTrader platform.
     *
     * Generated from protobuf field <code>int64 symbolId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSymbolId($var)
    {
        GPBUtil::checkInt64($var);
        $this->symbolId = $var;

        return $this;
    }

    /**
     * The type of an order - MARKET, LIMIT, STOP, MARKET_RANGE, STOP_LIMIT.
     *
     * Generated from protobuf field <code>.ProtoOAOrderType orderType = 4;</code>
     * @return int
     */
    public function getOrderType()
    {
        return $this->orderType;
    }

    /**
     * The type of an order - MARKET, LIMIT, STOP, MARKET_RANGE, STOP_LIMIT.
     *
     * Generated from protobuf field <code>.ProtoOAOrderType orderType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrderType::class);
        $this->orderType = $var;

        return $this;
    }

    /**
     * The trade direction - BUY or SELL.
     *
     * Generated from protobuf field <code>.ProtoOATradeSide tradeSide = 5;</code>
     * @return int
     */
    public function getTradeSide()
    {
        return $this->tradeSide;
    }

    /**
     * The trade direction - BUY or SELL.
     *
     * Generated from protobuf field <code>.ProtoOATradeSide tradeSide = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTradeSide($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOATradeSide::class);
        $this->tradeSide = $var;

        return $this;
    }

    /**
     * The volume represented in 0.01 of a unit (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>int64 volume = 6;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * The volume represented in 0.01 of a unit (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>int64 volume = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkInt64($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * The limit price, can be specified for the LIMIT order only.
     *
     * Generated from protobuf field <code>double limitPrice = 7;</code>
     * @return float
     */
    public function getLimitPrice()
    {
        return $this->limitPrice;
    }

    /**
     * The limit price, can be specified for the LIMIT order only.
     *
     * Generated from protobuf field <code>double limitPrice = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setLimitPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->limitPrice = $var;

        return $this;
    }

    /**
     * Stop Price, can be specified for the STOP and the STOP_LIMIT orders only.
     *
     * Generated from protobuf field <code>double stopPrice = 8;</code>
     * @return float
     */
    public function getStopPrice()
    {
        return $this->stopPrice;
    }

    /**
     * Stop Price, can be specified for the STOP and the STOP_LIMIT orders only.
     *
     * Generated from protobuf field <code>double stopPrice = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setStopPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->stopPrice = $var;

        return $this;
    }

    /**
     * The specific order execution or expiration instruction - GOOD_TILL_DATE, GOOD_TILL_CANCEL, IMMEDIATE_OR_CANCEL, FILL_OR_KILL, MARKET_ON_OPEN.
     *
     * Generated from protobuf field <code>.ProtoOATimeInForce timeInForce = 9;</code>
     * @return int
     */
    public function getTimeInForce()
    {
        return $this->timeInForce;
    }

    /**
     * The specific order execution or expiration instruction - GOOD_TILL_DATE, GOOD_TILL_CANCEL, IMMEDIATE_OR_CANCEL, FILL_OR_KILL, MARKET_ON_OPEN.
     *
     * Generated from protobuf field <code>.ProtoOATimeInForce timeInForce = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeInForce($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOATimeInForce::class);
        $this->timeInForce = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds of Order expiration. Should be set for the Good Till Date orders.
     *
     * Generated from protobuf field <code>int64 expirationTimestamp = 10;</code>
     * @return int|string
     */
    public function getExpirationTimestamp()
    {
        return $this->expirationTimestamp;
    }

    /**
     * The Unix time in milliseconds of Order expiration. Should be set for the Good Till Date orders.
     *
     * Generated from protobuf field <code>int64 expirationTimestamp = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpirationTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->expirationTimestamp = $var;

        return $this;
    }

    /**
     * The absolute Stop Loss price (1.23456 for example). Not supported for MARKET orders.
     *
     * Generated from protobuf field <code>double stopLoss = 11;</code>
     * @return float
     */
    public function getStopLoss()
    {
        return $this->stopLoss;
    }

    /**
     * The absolute Stop Loss price (1.23456 for example). Not supported for MARKET orders.
     *
     * Generated from protobuf field <code>double stopLoss = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setStopLoss($var)
    {
        GPBUtil::checkDouble($var);
        $this->stopLoss = $var;

        return $this;
    }

    /**
     * The absolute Take Profit price (1.23456 for example). Unsupported for MARKET orders.
     *
     * Generated from protobuf field <code>double takeProfit = 12;</code>
     * @return float
     */
    public function getTakeProfit()
    {
        return $this->takeProfit;
    }

    /**
     * The absolute Take Profit price (1.23456 for example). Unsupported for MARKET orders.
     *
     * Generated from protobuf field <code>double takeProfit = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setTakeProfit($var)
    {
        GPBUtil::checkDouble($var);
        $this->takeProfit = $var;

        return $this;
    }

    /**
     * User-specified comment. MaxLength = 512.
     *
     * Generated from protobuf field <code>string comment = 13;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * User-specified comment. MaxLength = 512.
     *
     * Generated from protobuf field <code>string comment = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

    /**
     * Base price to calculate relative slippage price for MARKET_RANGE order.
     *
     * Generated from protobuf field <code>double baseSlippagePrice = 14;</code>
     * @return float
     */
    public function getBaseSlippagePrice()
    {
        return $this->baseSlippagePrice;
    }

    /**
     * Base price to calculate relative slippage price for MARKET_RANGE order.
     *
     * Generated from protobuf field <code>double baseSlippagePrice = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setBaseSlippagePrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->baseSlippagePrice = $var;

        return $this;
    }

    /**
     * Slippage distance for MARKET_RANGE and STOP_LIMIT order.
     *
     * Generated from protobuf field <code>int32 slippageInPoints = 15;</code>
     * @return int
     */
    public function getSlippageInPoints()
    {
        return $this->slippageInPoints;
    }

    /**
     * Slippage distance for MARKET_RANGE and STOP_LIMIT order.
     *
     * Generated from protobuf field <code>int32 slippageInPoints = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setSlippageInPoints($var)
    {
        GPBUtil::checkInt32($var);
        $this->slippageInPoints = $var;

        return $this;
    }

    /**
     * User-specified label. MaxLength = 100.
     *
     * Generated from protobuf field <code>string label = 16;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * User-specified label. MaxLength = 100.
     *
     * Generated from protobuf field <code>string label = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * Reference to the existing position if the Order is intended to modify it.
     *
     * Generated from protobuf field <code>int64 positionId = 17;</code>
     * @return int|string
     */
    public function getPositionId()
    {
        return $this->positionId;
    }

    /**
     * Reference to the existing position if the Order is intended to modify it.
     *
     * Generated from protobuf field <code>int64 positionId = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPositionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->positionId = $var;

        return $this;
    }

    /**
     * Optional user-specific clientOrderId (similar to FIX ClOrderID). MaxLength = 50.
     *
     * Generated from protobuf field <code>string clientOrderId = 18;</code>
     * @return string
     */
    public function getClientOrderId()
    {
        return $this->clientOrderId;
    }

    /**
     * Optional user-specific clientOrderId (similar to FIX ClOrderID). MaxLength = 50.
     *
     * Generated from protobuf field <code>string clientOrderId = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setClientOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientOrderId = $var;

        return $this;
    }

    /**
     * Relative Stop Loss that can be specified instead of the absolute as one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY stopLoss = entryPrice - relativeStopLoss, for SELL stopLoss = entryPrice + relativeStopLoss.
     *
     * Generated from protobuf field <code>int64 relativeStopLoss = 19;</code>
     * @return int|string
     */
    public function getRelativeStopLoss()
    {
        return $this->relativeStopLoss;
    }

    /**
     * Relative Stop Loss that can be specified instead of the absolute as one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY stopLoss = entryPrice - relativeStopLoss, for SELL stopLoss = entryPrice + relativeStopLoss.
     *
     * Generated from protobuf field <code>int64 relativeStopLoss = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRelativeStopLoss($var)
    {
        GPBUtil::checkInt64($var);
        $this->relativeStopLoss = $var;

        return $this;
    }

    /**
     * Relative Take Profit that can be specified instead of the absolute one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY takeProfit = entryPrice + relativeTakeProfit, for SELL takeProfit = entryPrice - relativeTakeProfit.
     *
     * Generated from protobuf field <code>int64 relativeTakeProfit = 20;</code>
     * @return int|string
     */
    public function getRelativeTakeProfit()
    {
        return $this->relativeTakeProfit;
    }

    /**
     * Relative Take Profit that can be specified instead of the absolute one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY takeProfit = entryPrice + relativeTakeProfit, for SELL takeProfit = entryPrice - relativeTakeProfit.
     *
     * Generated from protobuf field <code>int64 relativeTakeProfit = 20;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRelativeTakeProfit($var)
    {
        GPBUtil::checkInt64($var);
        $this->relativeTakeProfit = $var;

        return $this;
    }

    /**
     * If TRUE then stopLoss is guaranteed. Required to be set to TRUE for the Limited Risk accounts (ProtoOATrader.isLimitedRisk=true).
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 21;</code>
     * @return bool
     */
    public function getGuaranteedStopLoss()
    {
        return $this->guaranteedStopLoss;
    }

    /**
     * If TRUE then stopLoss is guaranteed. Required to be set to TRUE for the Limited Risk accounts (ProtoOATrader.isLimitedRisk=true).
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 21;</code>
     * @param bool $var
     * @return $this
     */
    public function setGuaranteedStopLoss($var)
    {
        GPBUtil::checkBool($var);
        $this->guaranteedStopLoss = $var;

        return $this;
    }

    /**
     * If TRUE then the Stop Loss is Trailing.
     *
     * Generated from protobuf field <code>bool trailingStopLoss = 22;</code>
     * @return bool
     */
    public function getTrailingStopLoss()
    {
        return $this->trailingStopLoss;
    }

    /**
     * If TRUE then the Stop Loss is Trailing.
     *
     * Generated from protobuf field <code>bool trailingStopLoss = 22;</code>
     * @param bool $var
     * @return $this
     */
    public function setTrailingStopLoss($var)
    {
        GPBUtil::checkBool($var);
        $this->trailingStopLoss = $var;

        return $this;
    }

    /**
     * Trigger method for the STOP or the STOP_LIMIT pending order.
     *
     * Generated from protobuf field <code>.ProtoOAOrderTriggerMethod stopTriggerMethod = 23;</code>
     * @return int
     */
    public function getStopTriggerMethod()
    {
        return $this->stopTriggerMethod;
    }

    /**
     * Trigger method for the STOP or the STOP_LIMIT pending order.
     *
     * Generated from protobuf field <code>.ProtoOAOrderTriggerMethod stopTriggerMethod = 23;</code>
     * @param int $var
     * @return $this
     */
    public function setStopTriggerMethod($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrderTriggerMethod::class);
        $this->stopTriggerMethod = $var;

        return $this;
    }

}

