<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ProtoOADynamicLeverage</code>
 */
class ProtoOADynamicLeverage extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique ID of dynamic leverage.
     *
     * Generated from protobuf field <code>int64 leverageId = 1;</code>
     */
    protected $leverageId = 0;
    /**
     * Tiers sorted by volume. Last tier's leverage is applied also to volume above specified.
     *
     * Generated from protobuf field <code>repeated .ProtoOADynamicLeverageTier tiers = 2;</code>
     */
    private $tiers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $leverageId
     *           Unique ID of dynamic leverage.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOADynamicLeverageTier[]|\Google\Protobuf\Internal\RepeatedField $tiers
     *           Tiers sorted by volume. Last tier's leverage is applied also to volume above specified.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique ID of dynamic leverage.
     *
     * Generated from protobuf field <code>int64 leverageId = 1;</code>
     * @return int|string
     */
    public function getLeverageId()
    {
        return $this->leverageId;
    }

    /**
     * Unique ID of dynamic leverage.
     *
     * Generated from protobuf field <code>int64 leverageId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLeverageId($var)
    {
        GPBUtil::checkInt64($var);
        $this->leverageId = $var;

        return $this;
    }

    /**
     * Tiers sorted by volume. Last tier's leverage is applied also to volume above specified.
     *
     * Generated from protobuf field <code>repeated .ProtoOADynamicLeverageTier tiers = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTiers()
    {
        return $this->tiers;
    }

    /**
     * Tiers sorted by volume. Last tier's leverage is applied also to volume above specified.
     *
     * Generated from protobuf field <code>repeated .ProtoOADynamicLeverageTier tiers = 2;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOADynamicLeverageTier[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTiers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOADynamicLeverageTier::class);
        $this->tiers = $arr;

        return $this;
    }

}

