<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 *The strategy for choosing which Position to close during a Stop Out
 *
 * Protobuf type <code>ProtoOAStopOutStrategy</code>
 */
class ProtoOAStopOutStrategy
{
    /**
     *A Stop Out strategy that closes a Position with the largest Used Margin
     *
     * Generated from protobuf enum <code>MOST_MARGIN_USED_FIRST = 0;</code>
     */
    const MOST_MARGIN_USED_FIRST = 0;
    /**
     *A Stop Out strategy that closes a Position with the least PnL
     *
     * Generated from protobuf enum <code>MOST_LOSING_FIRST = 1;</code>
     */
    const MOST_LOSING_FIRST = 1;

    private static $valueToName = [
        self::MOST_MARGIN_USED_FIRST => 'MOST_MARGIN_USED_FIRST',
        self::MOST_LOSING_FIRST => 'MOST_LOSING_FIRST',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

