<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Stop Order and Stop Loss triggering method ENUM. 
 *
 * Protobuf type <code>ProtoOAOrderTriggerMethod</code>
 */
class ProtoOAOrderTriggerMethod
{
    /**
     * Generated from protobuf enum <code>ORDER_TRIGGER_METHOD_UNKNOWN = 0;</code>
     */
    const ORDER_TRIGGER_METHOD_UNKNOWN = 0;
    /**
     * Stop Order: buy is triggered by ask, sell by bid; Stop Loss Order: for buy position is triggered by bid and for sell position by ask.
     *
     * Generated from protobuf enum <code>TRADE = 1;</code>
     */
    const TRADE = 1;
    /**
     * Stop Order: buy is triggered by bid, sell by ask; Stop Loss Order: for buy position is triggered by ask and for sell position by bid.
     *
     * Generated from protobuf enum <code>OPPOSITE = 2;</code>
     */
    const OPPOSITE = 2;
    /**
     * The same as TRADE, but trigger is checked after the second consecutive tick.
     *
     * Generated from protobuf enum <code>DOUBLE_TRADE = 3;</code>
     */
    const DOUBLE_TRADE = 3;
    /**
     * The same as OPPOSITE, but trigger is checked after the second consecutive tick.
     *
     * Generated from protobuf enum <code>DOUBLE_OPPOSITE = 4;</code>
     */
    const DOUBLE_OPPOSITE = 4;

    private static $valueToName = [
        self::ORDER_TRIGGER_METHOD_UNKNOWN => 'ORDER_TRIGGER_METHOD_UNKNOWN',
        self::TRADE => 'TRADE',
        self::OPPOSITE => 'OPPOSITE',
        self::DOUBLE_TRADE => 'DOUBLE_TRADE',
        self::DOUBLE_OPPOSITE => 'DOUBLE_OPPOSITE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

