<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Trader side ENUM. Used for order, position, deal. 
 *
 * Protobuf type <code>ProtoOATradeSide</code>
 */
class ProtoOATradeSide
{
    /**
     * Generated from protobuf enum <code>TRADE_SIDE_UNKNOWN = 0;</code>
     */
    const TRADE_SIDE_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>BUY = 1;</code>
     */
    const BUY = 1;
    /**
     * Generated from protobuf enum <code>SELL = 2;</code>
     */
    const SELL = 2;

    private static $valueToName = [
        self::TRADE_SIDE_UNKNOWN => 'TRADE_SIDE_UNKNOWN',
        self::BUY => 'BUY',
        self::SELL => 'SELL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

