<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Execution event type ENUM. 
 *
 * Protobuf type <code>ProtoOAExecutionType</code>
 */
class ProtoOAExecutionType
{
    /**
     * Generated from protobuf enum <code>EXECUTION_TYPE_UNKNOWN = 0;</code>
     */
    const EXECUTION_TYPE_UNKNOWN = 0;
    /**
     * Order passed validation.
     *
     * Generated from protobuf enum <code>ORDER_ACCEPTED = 2;</code>
     */
    const ORDER_ACCEPTED = 2;
    /**
     * Order filled.
     *
     * Generated from protobuf enum <code>ORDER_FILLED = 3;</code>
     */
    const ORDER_FILLED = 3;
    /**
     * Pending order is changed with a new one.
     *
     * Generated from protobuf enum <code>ORDER_REPLACED = 4;</code>
     */
    const ORDER_REPLACED = 4;
    /**
     * Order cancelled.
     *
     * Generated from protobuf enum <code>ORDER_CANCELLED = 5;</code>
     */
    const ORDER_CANCELLED = 5;
    /**
     * Order with GTD time in force is expired.
     *
     * Generated from protobuf enum <code>ORDER_EXPIRED = 6;</code>
     */
    const ORDER_EXPIRED = 6;
    /**
     * Order is rejected due to validations.
     *
     * Generated from protobuf enum <code>ORDER_REJECTED = 7;</code>
     */
    const ORDER_REJECTED = 7;
    /**
     * Cancel order request is rejected.
     *
     * Generated from protobuf enum <code>ORDER_CANCEL_REJECTED = 8;</code>
     */
    const ORDER_CANCEL_REJECTED = 8;
    /**
     * Type related to SWAP execution events.
     *
     * Generated from protobuf enum <code>SWAP = 9;</code>
     */
    const SWAP = 9;
    /**
     * Type related to event of deposit or withdrawal cash flow operation.
     *
     * Generated from protobuf enum <code>DEPOSIT_WITHDRAW = 10;</code>
     */
    const DEPOSIT_WITHDRAW = 10;
    /**
     * Order is partially filled.
     *
     * Generated from protobuf enum <code>ORDER_PARTIAL_FILL = 11;</code>
     */
    const ORDER_PARTIAL_FILL = 11;
    /**
     * Type related to event of bonus deposit or bonus withdrawal.
     *
     * Generated from protobuf enum <code>BONUS_DEPOSIT_WITHDRAW = 12;</code>
     */
    const BONUS_DEPOSIT_WITHDRAW = 12;

    private static $valueToName = [
        self::EXECUTION_TYPE_UNKNOWN => 'EXECUTION_TYPE_UNKNOWN',
        self::ORDER_ACCEPTED => 'ORDER_ACCEPTED',
        self::ORDER_FILLED => 'ORDER_FILLED',
        self::ORDER_REPLACED => 'ORDER_REPLACED',
        self::ORDER_CANCELLED => 'ORDER_CANCELLED',
        self::ORDER_EXPIRED => 'ORDER_EXPIRED',
        self::ORDER_REJECTED => 'ORDER_REJECTED',
        self::ORDER_CANCEL_REJECTED => 'ORDER_CANCEL_REJECTED',
        self::SWAP => 'SWAP',
        self::DEPOSIT_WITHDRAW => 'DEPOSIT_WITHDRAW',
        self::ORDER_PARTIAL_FILL => 'ORDER_PARTIAL_FILL',
        self::BONUS_DEPOSIT_WITHDRAW => 'BONUS_DEPOSIT_WITHDRAW',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

