<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Enum for specifying type of trading commission. 
 *
 * Protobuf type <code>ProtoOACommissionType</code>
 */
class ProtoOACommissionType
{
    /**
     * Generated from protobuf enum <code>PROTO_OA_COMMISSION_TYPE_UNKNOWN = 0;</code>
     */
    const PROTO_OA_COMMISSION_TYPE_UNKNOWN = 0;
    /**
     * USD per million USD volume - usually used for FX. Example: 50 USD for 1 mil USD of trading volume.
     *
     * Generated from protobuf enum <code>USD_PER_MILLION_USD = 1;</code>
     */
    const USD_PER_MILLION_USD = 1;
    /**
     * USD per 1 lot - usually used for CFDs and futures for commodities, and indices. Example: 15 USD for 1 contract.
     *
     * Generated from protobuf enum <code>USD_PER_LOT = 2;</code>
     */
    const USD_PER_LOT = 2;
    /**
     * Percentage of trading volume - usually used for Equities. Example: 0.005% of notional trading volume. Multiplied by 100,000.
     *
     * Generated from protobuf enum <code>PERCENTAGE_OF_VALUE = 3;</code>
     */
    const PERCENTAGE_OF_VALUE = 3;
    /**
     * Quote ccy of Symbol per 1 lot - will be used for CFDs and futures for commodities, and indices. Example: 15 EUR for 1 contract of DAX.
     *
     * Generated from protobuf enum <code>QUOTE_CCY_PER_LOT = 4;</code>
     */
    const QUOTE_CCY_PER_LOT = 4;

    private static $valueToName = [
        self::PROTO_OA_COMMISSION_TYPE_UNKNOWN => 'PROTO_OA_COMMISSION_TYPE_UNKNOWN',
        self::USD_PER_MILLION_USD => 'USD_PER_MILLION_USD',
        self::USD_PER_LOT => 'USD_PER_LOT',
        self::PERCENTAGE_OF_VALUE => 'PERCENTAGE_OF_VALUE',
        self::QUOTE_CCY_PER_LOT => 'QUOTE_CCY_PER_LOT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

