<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Position/order trading details entity. 
 *
 * Generated from protobuf message <code>ProtoOATradeData</code>
 */
class ProtoOATradeData extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identifier of the symbol in specific server environment within cTrader platform. Different brokers might have different IDs.
     *
     * Generated from protobuf field <code>int64 symbolId = 1;</code>
     */
    protected $symbolId = 0;
    /**
     * Volume in cents (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>int64 volume = 2;</code>
     */
    protected $volume = 0;
    /**
     * Buy, Sell.
     *
     * Generated from protobuf field <code>.ProtoOATradeSide tradeSide = 3;</code>
     */
    protected $tradeSide = 0;
    /**
     * The Unix time in milliseconds when position was opened or order was created.
     *
     * Generated from protobuf field <code>int64 openTimestamp = 4;</code>
     */
    protected $openTimestamp = 0;
    /**
     * Text label specified during order request.
     *
     * Generated from protobuf field <code>string label = 5;</code>
     */
    protected $label = '';
    /**
     * If TRUE then position/order stop loss is guaranteedStopLoss.
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 6;</code>
     */
    protected $guaranteedStopLoss = false;
    /**
     * User-specified comment.
     *
     * Generated from protobuf field <code>string comment = 7;</code>
     */
    protected $comment = '';
    /**
     * Specifies the units in which the Symbol is denominated.
     *
     * Generated from protobuf field <code>string measurementUnits = 8;</code>
     */
    protected $measurementUnits = '';
    /**
     * The Unix time in milliseconds when a Position was closed
     *
     * Generated from protobuf field <code>uint64 closeTimestamp = 9;</code>
     */
    protected $closeTimestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $symbolId
     *           The unique identifier of the symbol in specific server environment within cTrader platform. Different brokers might have different IDs.
     *     @type int|string $volume
     *           Volume in cents (e.g. 1000 in protocol means 10.00 units).
     *     @type int $tradeSide
     *           Buy, Sell.
     *     @type int|string $openTimestamp
     *           The Unix time in milliseconds when position was opened or order was created.
     *     @type string $label
     *           Text label specified during order request.
     *     @type bool $guaranteedStopLoss
     *           If TRUE then position/order stop loss is guaranteedStopLoss.
     *     @type string $comment
     *           User-specified comment.
     *     @type string $measurementUnits
     *           Specifies the units in which the Symbol is denominated.
     *     @type int|string $closeTimestamp
     *           The Unix time in milliseconds when a Position was closed
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identifier of the symbol in specific server environment within cTrader platform. Different brokers might have different IDs.
     *
     * Generated from protobuf field <code>int64 symbolId = 1;</code>
     * @return int|string
     */
    public function getSymbolId()
    {
        return $this->symbolId;
    }

    /**
     * The unique identifier of the symbol in specific server environment within cTrader platform. Different brokers might have different IDs.
     *
     * Generated from protobuf field <code>int64 symbolId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSymbolId($var)
    {
        GPBUtil::checkInt64($var);
        $this->symbolId = $var;

        return $this;
    }

    /**
     * Volume in cents (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>int64 volume = 2;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Volume in cents (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>int64 volume = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkInt64($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * Buy, Sell.
     *
     * Generated from protobuf field <code>.ProtoOATradeSide tradeSide = 3;</code>
     * @return int
     */
    public function getTradeSide()
    {
        return $this->tradeSide;
    }

    /**
     * Buy, Sell.
     *
     * Generated from protobuf field <code>.ProtoOATradeSide tradeSide = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTradeSide($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOATradeSide::class);
        $this->tradeSide = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds when position was opened or order was created.
     *
     * Generated from protobuf field <code>int64 openTimestamp = 4;</code>
     * @return int|string
     */
    public function getOpenTimestamp()
    {
        return $this->openTimestamp;
    }

    /**
     * The Unix time in milliseconds when position was opened or order was created.
     *
     * Generated from protobuf field <code>int64 openTimestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOpenTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->openTimestamp = $var;

        return $this;
    }

    /**
     * Text label specified during order request.
     *
     * Generated from protobuf field <code>string label = 5;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Text label specified during order request.
     *
     * Generated from protobuf field <code>string label = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * If TRUE then position/order stop loss is guaranteedStopLoss.
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 6;</code>
     * @return bool
     */
    public function getGuaranteedStopLoss()
    {
        return $this->guaranteedStopLoss;
    }

    /**
     * If TRUE then position/order stop loss is guaranteedStopLoss.
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setGuaranteedStopLoss($var)
    {
        GPBUtil::checkBool($var);
        $this->guaranteedStopLoss = $var;

        return $this;
    }

    /**
     * User-specified comment.
     *
     * Generated from protobuf field <code>string comment = 7;</code>
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * User-specified comment.
     *
     * Generated from protobuf field <code>string comment = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->comment = $var;

        return $this;
    }

    /**
     * Specifies the units in which the Symbol is denominated.
     *
     * Generated from protobuf field <code>string measurementUnits = 8;</code>
     * @return string
     */
    public function getMeasurementUnits()
    {
        return $this->measurementUnits;
    }

    /**
     * Specifies the units in which the Symbol is denominated.
     *
     * Generated from protobuf field <code>string measurementUnits = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMeasurementUnits($var)
    {
        GPBUtil::checkString($var, True);
        $this->measurementUnits = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds when a Position was closed
     *
     * Generated from protobuf field <code>uint64 closeTimestamp = 9;</code>
     * @return int|string
     */
    public function getCloseTimestamp()
    {
        return $this->closeTimestamp;
    }

    /**
     * The Unix time in milliseconds when a Position was closed
     *
     * Generated from protobuf field <code>uint64 closeTimestamp = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCloseTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->closeTimestamp = $var;

        return $this;
    }

}

