<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Order type ENUM. 
 *
 * Protobuf type <code>ProtoOAOrderType</code>
 */
class ProtoOAOrderType
{
    /**
     * Generated from protobuf enum <code>ORDER_TYPE_UNKNOWN = 0;</code>
     */
    const ORDER_TYPE_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>MARKET = 1;</code>
     */
    const MARKET = 1;
    /**
     * Generated from protobuf enum <code>LIMIT = 2;</code>
     */
    const LIMIT = 2;
    /**
     * Generated from protobuf enum <code>STOP = 3;</code>
     */
    const STOP = 3;
    /**
     * Generated from protobuf enum <code>STOP_LOSS_TAKE_PROFIT = 4;</code>
     */
    const STOP_LOSS_TAKE_PROFIT = 4;
    /**
     * Generated from protobuf enum <code>MARKET_RANGE = 5;</code>
     */
    const MARKET_RANGE = 5;
    /**
     * Generated from protobuf enum <code>STOP_LIMIT = 6;</code>
     */
    const STOP_LIMIT = 6;

    private static $valueToName = [
        self::ORDER_TYPE_UNKNOWN => 'ORDER_TYPE_UNKNOWN',
        self::MARKET => 'MARKET',
        self::LIMIT => 'LIMIT',
        self::STOP => 'STOP',
        self::STOP_LOSS_TAKE_PROFIT => 'STOP_LOSS_TAKE_PROFIT',
        self::MARKET_RANGE => 'MARKET_RANGE',
        self::STOP_LIMIT => 'STOP_LIMIT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

