<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Margin call entity, specifies threshold for exact margin call type. Only 3 instances of margin calls are supported, identified by marginCallType. See ProtoOANotificationType for details. 
 *
 * Generated from protobuf message <code>ProtoOAMarginCall</code>
 */
class ProtoOAMarginCall extends \Google\Protobuf\Internal\Message
{
    /**
     * Type of margin call. All margin calls are similar, only difference is in marginLevelThreshold.
     *
     * Generated from protobuf field <code>.ProtoOANotificationType marginCallType = 1;</code>
     */
    protected $marginCallType = 0;
    /**
     * Margin level threshold for margin call.
     *
     * Generated from protobuf field <code>double marginLevelThreshold = 2;</code>
     */
    protected $marginLevelThreshold = 0.0;
    /**
     * The Unix time in milliseconds of the last update of the margin call.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 3;</code>
     */
    protected $utcLastUpdateTimestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $marginCallType
     *           Type of margin call. All margin calls are similar, only difference is in marginLevelThreshold.
     *     @type float $marginLevelThreshold
     *           Margin level threshold for margin call.
     *     @type int|string $utcLastUpdateTimestamp
     *           The Unix time in milliseconds of the last update of the margin call.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Type of margin call. All margin calls are similar, only difference is in marginLevelThreshold.
     *
     * Generated from protobuf field <code>.ProtoOANotificationType marginCallType = 1;</code>
     * @return int
     */
    public function getMarginCallType()
    {
        return $this->marginCallType;
    }

    /**
     * Type of margin call. All margin calls are similar, only difference is in marginLevelThreshold.
     *
     * Generated from protobuf field <code>.ProtoOANotificationType marginCallType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMarginCallType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOANotificationType::class);
        $this->marginCallType = $var;

        return $this;
    }

    /**
     * Margin level threshold for margin call.
     *
     * Generated from protobuf field <code>double marginLevelThreshold = 2;</code>
     * @return float
     */
    public function getMarginLevelThreshold()
    {
        return $this->marginLevelThreshold;
    }

    /**
     * Margin level threshold for margin call.
     *
     * Generated from protobuf field <code>double marginLevelThreshold = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setMarginLevelThreshold($var)
    {
        GPBUtil::checkDouble($var);
        $this->marginLevelThreshold = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds of the last update of the margin call.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 3;</code>
     * @return int|string
     */
    public function getUtcLastUpdateTimestamp()
    {
        return $this->utcLastUpdateTimestamp;
    }

    /**
     * The Unix time in milliseconds of the last update of the margin call.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUtcLastUpdateTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->utcLastUpdateTimestamp = $var;

        return $this;
    }

}

