<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Response with a list of existing user Margin Calls, usually contains 3 items. 
 *
 * Generated from protobuf message <code>ProtoOAMarginCallListRes</code>
 */
class ProtoOAMarginCallListRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Generated from protobuf field <code>repeated .ProtoOAMarginCall marginCall = 2;</code>
     */
    private $marginCall;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOAMarginCall[]|\Google\Protobuf\Internal\RepeatedField $marginCall
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .ProtoOAMarginCall marginCall = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMarginCall()
    {
        return $this->marginCall;
    }

    /**
     * Generated from protobuf field <code>repeated .ProtoOAMarginCall marginCall = 2;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOAMarginCall[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMarginCall($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOAMarginCall::class);
        $this->marginCall = $arr;

        return $this;
    }

}

