<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ProtoOAHoliday</code>
 */
class ProtoOAHoliday extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique ID of holiday.
     *
     * Generated from protobuf field <code>int64 holidayId = 1;</code>
     */
    protected $holidayId = 0;
    /**
     * Name of holiday.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Description of holiday.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Timezone used for holiday.
     *
     * Generated from protobuf field <code>string scheduleTimeZone = 4;</code>
     */
    protected $scheduleTimeZone = '';
    /**
     * Amount of days from 1st Jan 1970, multiply it by 86400000 to get Unix time in milliseconds.
     *
     * Generated from protobuf field <code>int64 holidayDate = 5;</code>
     */
    protected $holidayDate = 0;
    /**
     * If TRUE, then the holiday happens each year.
     *
     * Generated from protobuf field <code>bool isRecurring = 6;</code>
     */
    protected $isRecurring = false;
    /**
     * Amount of seconds from 00:00:00 of the holiday day when holiday actually starts.
     *
     * Generated from protobuf field <code>int32 startSecond = 7;</code>
     */
    protected $startSecond = 0;
    /**
     * Amount of seconds from 00:00:00 of the holiday day when holiday actually finishes.
     *
     * Generated from protobuf field <code>int32 endSecond = 8;</code>
     */
    protected $endSecond = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $holidayId
     *           Unique ID of holiday.
     *     @type string $name
     *           Name of holiday.
     *     @type string $description
     *           Description of holiday.
     *     @type string $scheduleTimeZone
     *           Timezone used for holiday.
     *     @type int|string $holidayDate
     *           Amount of days from 1st Jan 1970, multiply it by 86400000 to get Unix time in milliseconds.
     *     @type bool $isRecurring
     *           If TRUE, then the holiday happens each year.
     *     @type int $startSecond
     *           Amount of seconds from 00:00:00 of the holiday day when holiday actually starts.
     *     @type int $endSecond
     *           Amount of seconds from 00:00:00 of the holiday day when holiday actually finishes.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique ID of holiday.
     *
     * Generated from protobuf field <code>int64 holidayId = 1;</code>
     * @return int|string
     */
    public function getHolidayId()
    {
        return $this->holidayId;
    }

    /**
     * Unique ID of holiday.
     *
     * Generated from protobuf field <code>int64 holidayId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHolidayId($var)
    {
        GPBUtil::checkInt64($var);
        $this->holidayId = $var;

        return $this;
    }

    /**
     * Name of holiday.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of holiday.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Description of holiday.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Description of holiday.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Timezone used for holiday.
     *
     * Generated from protobuf field <code>string scheduleTimeZone = 4;</code>
     * @return string
     */
    public function getScheduleTimeZone()
    {
        return $this->scheduleTimeZone;
    }

    /**
     * Timezone used for holiday.
     *
     * Generated from protobuf field <code>string scheduleTimeZone = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setScheduleTimeZone($var)
    {
        GPBUtil::checkString($var, True);
        $this->scheduleTimeZone = $var;

        return $this;
    }

    /**
     * Amount of days from 1st Jan 1970, multiply it by 86400000 to get Unix time in milliseconds.
     *
     * Generated from protobuf field <code>int64 holidayDate = 5;</code>
     * @return int|string
     */
    public function getHolidayDate()
    {
        return $this->holidayDate;
    }

    /**
     * Amount of days from 1st Jan 1970, multiply it by 86400000 to get Unix time in milliseconds.
     *
     * Generated from protobuf field <code>int64 holidayDate = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHolidayDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->holidayDate = $var;

        return $this;
    }

    /**
     * If TRUE, then the holiday happens each year.
     *
     * Generated from protobuf field <code>bool isRecurring = 6;</code>
     * @return bool
     */
    public function getIsRecurring()
    {
        return $this->isRecurring;
    }

    /**
     * If TRUE, then the holiday happens each year.
     *
     * Generated from protobuf field <code>bool isRecurring = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsRecurring($var)
    {
        GPBUtil::checkBool($var);
        $this->isRecurring = $var;

        return $this;
    }

    /**
     * Amount of seconds from 00:00:00 of the holiday day when holiday actually starts.
     *
     * Generated from protobuf field <code>int32 startSecond = 7;</code>
     * @return int
     */
    public function getStartSecond()
    {
        return $this->startSecond;
    }

    /**
     * Amount of seconds from 00:00:00 of the holiday day when holiday actually starts.
     *
     * Generated from protobuf field <code>int32 startSecond = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setStartSecond($var)
    {
        GPBUtil::checkInt32($var);
        $this->startSecond = $var;

        return $this;
    }

    /**
     * Amount of seconds from 00:00:00 of the holiday day when holiday actually finishes.
     *
     * Generated from protobuf field <code>int32 endSecond = 8;</code>
     * @return int
     */
    public function getEndSecond()
    {
        return $this->endSecond;
    }

    /**
     * Amount of seconds from 00:00:00 of the holiday day when holiday actually finishes.
     *
     * Generated from protobuf field <code>int32 endSecond = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setEndSecond($var)
    {
        GPBUtil::checkInt32($var);
        $this->endSecond = $var;

        return $this;
    }

}

