<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Enum for specifying access right for a trader. 
 *
 * Protobuf type <code>ProtoOAAccessRights</code>
 */
class ProtoOAAccessRights
{
    /**
     * Enable all trading.
     *
     * Generated from protobuf enum <code>FULL_ACCESS = 0;</code>
     */
    const FULL_ACCESS = 0;
    /**
     * Only closing trading request are enabled.
     *
     * Generated from protobuf enum <code>CLOSE_ONLY = 1;</code>
     */
    const CLOSE_ONLY = 1;
    /**
     * View only access.
     *
     * Generated from protobuf enum <code>NO_TRADING = 2;</code>
     */
    const NO_TRADING = 2;
    /**
     * No access.
     *
     * Generated from protobuf enum <code>NO_LOGIN = 3;</code>
     */
    const NO_LOGIN = 3;

    private static $valueToName = [
        self::FULL_ACCESS => 'FULL_ACCESS',
        self::CLOSE_ONLY => 'CLOSE_ONLY',
        self::NO_TRADING => 'NO_TRADING',
        self::NO_LOGIN => 'NO_LOGIN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

