<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Deal details for ProtoOADealOffsetListReq. 
 *
 * Generated from protobuf message <code>ProtoOADealOffset</code>
 */
class ProtoOADealOffset extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique ID of the execution Deal.
     *
     * Generated from protobuf field <code>int64 dealId = 1;</code>
     */
    protected $dealId = 0;
    /**
     * Matched volume, in cents.
     *
     * Generated from protobuf field <code>int64 volume = 2;</code>
     */
    protected $volume = 0;
    /**
     * The Unix time in milliseconds when the offset Deal was executed.
     *
     * Generated from protobuf field <code>int64 executionTimestamp = 3;</code>
     */
    protected $executionTimestamp = 0;
    /**
     *  Execution price of the offset Deal.
     *
     * Generated from protobuf field <code>double executionPrice = 4;</code>
     */
    protected $executionPrice = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $dealId
     *           The unique ID of the execution Deal.
     *     @type int|string $volume
     *           Matched volume, in cents.
     *     @type int|string $executionTimestamp
     *           The Unix time in milliseconds when the offset Deal was executed.
     *     @type float $executionPrice
     *            Execution price of the offset Deal.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique ID of the execution Deal.
     *
     * Generated from protobuf field <code>int64 dealId = 1;</code>
     * @return int|string
     */
    public function getDealId()
    {
        return $this->dealId;
    }

    /**
     * The unique ID of the execution Deal.
     *
     * Generated from protobuf field <code>int64 dealId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDealId($var)
    {
        GPBUtil::checkInt64($var);
        $this->dealId = $var;

        return $this;
    }

    /**
     * Matched volume, in cents.
     *
     * Generated from protobuf field <code>int64 volume = 2;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Matched volume, in cents.
     *
     * Generated from protobuf field <code>int64 volume = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkInt64($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds when the offset Deal was executed.
     *
     * Generated from protobuf field <code>int64 executionTimestamp = 3;</code>
     * @return int|string
     */
    public function getExecutionTimestamp()
    {
        return $this->executionTimestamp;
    }

    /**
     * The Unix time in milliseconds when the offset Deal was executed.
     *
     * Generated from protobuf field <code>int64 executionTimestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExecutionTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->executionTimestamp = $var;

        return $this;
    }

    /**
     *  Execution price of the offset Deal.
     *
     * Generated from protobuf field <code>double executionPrice = 4;</code>
     * @return float
     */
    public function getExecutionPrice()
    {
        return $this->executionPrice;
    }

    /**
     *  Execution price of the offset Deal.
     *
     * Generated from protobuf field <code>double executionPrice = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setExecutionPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->executionPrice = $var;

        return $this;
    }

}

