<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Request for amending the existing pending order. Allowed only if the Access Token has "trade" permissions for the trading account. 
 *
 * Generated from protobuf message <code>ProtoOAAmendOrderReq</code>
 */
class ProtoOAAmendOrderReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * The unique ID of the order.
     *
     * Generated from protobuf field <code>int64 orderId = 3;</code>
     */
    protected $orderId = 0;
    /**
     * Volume, represented in 0.01 of a unit (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>int64 volume = 4;</code>
     */
    protected $volume = 0;
    /**
     * The Limit Price, can be specified for the LIMIT order only.
     *
     * Generated from protobuf field <code>double limitPrice = 5;</code>
     */
    protected $limitPrice = 0.0;
    /**
     * The Stop Price, can be specified for the STOP and the STOP_LIMIT orders.
     *
     * Generated from protobuf field <code>double stopPrice = 6;</code>
     */
    protected $stopPrice = 0.0;
    /**
     * The Unix timestamp in milliseconds of Order expiration. Should be set for the Good Till Date orders.
     *
     * Generated from protobuf field <code>int64 expirationTimestamp = 7;</code>
     */
    protected $expirationTimestamp = 0;
    /**
     * The absolute Stop Loss price (e.g. 1.23456). Not supported for MARKET orders.
     *
     * Generated from protobuf field <code>double stopLoss = 8;</code>
     */
    protected $stopLoss = 0.0;
    /**
     * The absolute Take Profit price (e.g. 1.23456). Not supported for MARKET orders.
     *
     * Generated from protobuf field <code>double takeProfit = 9;</code>
     */
    protected $takeProfit = 0.0;
    /**
     * Slippage distance for the MARKET_RANGE and the STOP_LIMIT orders.
     *
     * Generated from protobuf field <code>int32 slippageInPoints = 10;</code>
     */
    protected $slippageInPoints = 0;
    /**
     * The relative Stop Loss can be specified instead of the absolute one. Specified in 1/100000 of a unit of price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY stopLoss = entryPrice - relativeStopLoss, for SELL stopLoss = entryPrice + relativeStopLoss.
     *
     * Generated from protobuf field <code>int64 relativeStopLoss = 11;</code>
     */
    protected $relativeStopLoss = 0;
    /**
     * The relative Take Profit can be specified instead of the absolute one. Specified in 1/100000 of a unit of price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY takeProfit = entryPrice + relativeTakeProfit, for SELL takeProfit = entryPrice - relativeTakeProfit.
     *
     * Generated from protobuf field <code>int64 relativeTakeProfit = 12;</code>
     */
    protected $relativeTakeProfit = 0;
    /**
     * If TRUE then the Stop Loss is guaranteed. Available for the French Risk or the Guaranteed Stop Loss Accounts.
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 13;</code>
     */
    protected $guaranteedStopLoss = false;
    /**
     * If TRUE then the Trailing Stop Loss is applied.
     *
     * Generated from protobuf field <code>bool trailingStopLoss = 14;</code>
     */
    protected $trailingStopLoss = false;
    /**
     * Trigger method for the STOP or the STOP_LIMIT pending order.
     *
     * Generated from protobuf field <code>.ProtoOAOrderTriggerMethod stopTriggerMethod = 15;</code>
     */
    protected $stopTriggerMethod = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type int|string $orderId
     *           The unique ID of the order.
     *     @type int|string $volume
     *           Volume, represented in 0.01 of a unit (e.g. 1000 in protocol means 10.00 units).
     *     @type float $limitPrice
     *           The Limit Price, can be specified for the LIMIT order only.
     *     @type float $stopPrice
     *           The Stop Price, can be specified for the STOP and the STOP_LIMIT orders.
     *     @type int|string $expirationTimestamp
     *           The Unix timestamp in milliseconds of Order expiration. Should be set for the Good Till Date orders.
     *     @type float $stopLoss
     *           The absolute Stop Loss price (e.g. 1.23456). Not supported for MARKET orders.
     *     @type float $takeProfit
     *           The absolute Take Profit price (e.g. 1.23456). Not supported for MARKET orders.
     *     @type int $slippageInPoints
     *           Slippage distance for the MARKET_RANGE and the STOP_LIMIT orders.
     *     @type int|string $relativeStopLoss
     *           The relative Stop Loss can be specified instead of the absolute one. Specified in 1/100000 of a unit of price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY stopLoss = entryPrice - relativeStopLoss, for SELL stopLoss = entryPrice + relativeStopLoss.
     *     @type int|string $relativeTakeProfit
     *           The relative Take Profit can be specified instead of the absolute one. Specified in 1/100000 of a unit of price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY takeProfit = entryPrice + relativeTakeProfit, for SELL takeProfit = entryPrice - relativeTakeProfit.
     *     @type bool $guaranteedStopLoss
     *           If TRUE then the Stop Loss is guaranteed. Available for the French Risk or the Guaranteed Stop Loss Accounts.
     *     @type bool $trailingStopLoss
     *           If TRUE then the Trailing Stop Loss is applied.
     *     @type int $stopTriggerMethod
     *           Trigger method for the STOP or the STOP_LIMIT pending order.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * The unique ID of the order.
     *
     * Generated from protobuf field <code>int64 orderId = 3;</code>
     * @return int|string
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * The unique ID of the order.
     *
     * Generated from protobuf field <code>int64 orderId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt64($var);
        $this->orderId = $var;

        return $this;
    }

    /**
     * Volume, represented in 0.01 of a unit (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>int64 volume = 4;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Volume, represented in 0.01 of a unit (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>int64 volume = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkInt64($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * The Limit Price, can be specified for the LIMIT order only.
     *
     * Generated from protobuf field <code>double limitPrice = 5;</code>
     * @return float
     */
    public function getLimitPrice()
    {
        return $this->limitPrice;
    }

    /**
     * The Limit Price, can be specified for the LIMIT order only.
     *
     * Generated from protobuf field <code>double limitPrice = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setLimitPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->limitPrice = $var;

        return $this;
    }

    /**
     * The Stop Price, can be specified for the STOP and the STOP_LIMIT orders.
     *
     * Generated from protobuf field <code>double stopPrice = 6;</code>
     * @return float
     */
    public function getStopPrice()
    {
        return $this->stopPrice;
    }

    /**
     * The Stop Price, can be specified for the STOP and the STOP_LIMIT orders.
     *
     * Generated from protobuf field <code>double stopPrice = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setStopPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->stopPrice = $var;

        return $this;
    }

    /**
     * The Unix timestamp in milliseconds of Order expiration. Should be set for the Good Till Date orders.
     *
     * Generated from protobuf field <code>int64 expirationTimestamp = 7;</code>
     * @return int|string
     */
    public function getExpirationTimestamp()
    {
        return $this->expirationTimestamp;
    }

    /**
     * The Unix timestamp in milliseconds of Order expiration. Should be set for the Good Till Date orders.
     *
     * Generated from protobuf field <code>int64 expirationTimestamp = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpirationTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->expirationTimestamp = $var;

        return $this;
    }

    /**
     * The absolute Stop Loss price (e.g. 1.23456). Not supported for MARKET orders.
     *
     * Generated from protobuf field <code>double stopLoss = 8;</code>
     * @return float
     */
    public function getStopLoss()
    {
        return $this->stopLoss;
    }

    /**
     * The absolute Stop Loss price (e.g. 1.23456). Not supported for MARKET orders.
     *
     * Generated from protobuf field <code>double stopLoss = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setStopLoss($var)
    {
        GPBUtil::checkDouble($var);
        $this->stopLoss = $var;

        return $this;
    }

    /**
     * The absolute Take Profit price (e.g. 1.23456). Not supported for MARKET orders.
     *
     * Generated from protobuf field <code>double takeProfit = 9;</code>
     * @return float
     */
    public function getTakeProfit()
    {
        return $this->takeProfit;
    }

    /**
     * The absolute Take Profit price (e.g. 1.23456). Not supported for MARKET orders.
     *
     * Generated from protobuf field <code>double takeProfit = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setTakeProfit($var)
    {
        GPBUtil::checkDouble($var);
        $this->takeProfit = $var;

        return $this;
    }

    /**
     * Slippage distance for the MARKET_RANGE and the STOP_LIMIT orders.
     *
     * Generated from protobuf field <code>int32 slippageInPoints = 10;</code>
     * @return int
     */
    public function getSlippageInPoints()
    {
        return $this->slippageInPoints;
    }

    /**
     * Slippage distance for the MARKET_RANGE and the STOP_LIMIT orders.
     *
     * Generated from protobuf field <code>int32 slippageInPoints = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setSlippageInPoints($var)
    {
        GPBUtil::checkInt32($var);
        $this->slippageInPoints = $var;

        return $this;
    }

    /**
     * The relative Stop Loss can be specified instead of the absolute one. Specified in 1/100000 of a unit of price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY stopLoss = entryPrice - relativeStopLoss, for SELL stopLoss = entryPrice + relativeStopLoss.
     *
     * Generated from protobuf field <code>int64 relativeStopLoss = 11;</code>
     * @return int|string
     */
    public function getRelativeStopLoss()
    {
        return $this->relativeStopLoss;
    }

    /**
     * The relative Stop Loss can be specified instead of the absolute one. Specified in 1/100000 of a unit of price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY stopLoss = entryPrice - relativeStopLoss, for SELL stopLoss = entryPrice + relativeStopLoss.
     *
     * Generated from protobuf field <code>int64 relativeStopLoss = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRelativeStopLoss($var)
    {
        GPBUtil::checkInt64($var);
        $this->relativeStopLoss = $var;

        return $this;
    }

    /**
     * The relative Take Profit can be specified instead of the absolute one. Specified in 1/100000 of a unit of price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY takeProfit = entryPrice + relativeTakeProfit, for SELL takeProfit = entryPrice - relativeTakeProfit.
     *
     * Generated from protobuf field <code>int64 relativeTakeProfit = 12;</code>
     * @return int|string
     */
    public function getRelativeTakeProfit()
    {
        return $this->relativeTakeProfit;
    }

    /**
     * The relative Take Profit can be specified instead of the absolute one. Specified in 1/100000 of a unit of price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY takeProfit = entryPrice + relativeTakeProfit, for SELL takeProfit = entryPrice - relativeTakeProfit.
     *
     * Generated from protobuf field <code>int64 relativeTakeProfit = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRelativeTakeProfit($var)
    {
        GPBUtil::checkInt64($var);
        $this->relativeTakeProfit = $var;

        return $this;
    }

    /**
     * If TRUE then the Stop Loss is guaranteed. Available for the French Risk or the Guaranteed Stop Loss Accounts.
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 13;</code>
     * @return bool
     */
    public function getGuaranteedStopLoss()
    {
        return $this->guaranteedStopLoss;
    }

    /**
     * If TRUE then the Stop Loss is guaranteed. Available for the French Risk or the Guaranteed Stop Loss Accounts.
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setGuaranteedStopLoss($var)
    {
        GPBUtil::checkBool($var);
        $this->guaranteedStopLoss = $var;

        return $this;
    }

    /**
     * If TRUE then the Trailing Stop Loss is applied.
     *
     * Generated from protobuf field <code>bool trailingStopLoss = 14;</code>
     * @return bool
     */
    public function getTrailingStopLoss()
    {
        return $this->trailingStopLoss;
    }

    /**
     * If TRUE then the Trailing Stop Loss is applied.
     *
     * Generated from protobuf field <code>bool trailingStopLoss = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setTrailingStopLoss($var)
    {
        GPBUtil::checkBool($var);
        $this->trailingStopLoss = $var;

        return $this;
    }

    /**
     * Trigger method for the STOP or the STOP_LIMIT pending order.
     *
     * Generated from protobuf field <code>.ProtoOAOrderTriggerMethod stopTriggerMethod = 15;</code>
     * @return int
     */
    public function getStopTriggerMethod()
    {
        return $this->stopTriggerMethod;
    }

    /**
     * Trigger method for the STOP or the STOP_LIMIT pending order.
     *
     * Generated from protobuf field <code>.ProtoOAOrderTriggerMethod stopTriggerMethod = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setStopTriggerMethod($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrderTriggerMethod::class);
        $this->stopTriggerMethod = $var;

        return $this;
    }

}

