<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiCommonMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Base message that is used for all messages that are sent to/from Open API proxy of cTrader platform. 
 *
 * Generated from protobuf message <code>ProtoMessage</code>
 */
class ProtoMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Contains id of ProtoPayloadType or other custom PayloadTypes (e.g. ProtoOAPayloadType).
     *
     * Generated from protobuf field <code>uint32 payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Serialized protobuf message that corresponds to payloadType.
     *
     * Generated from protobuf field <code>bytes payload = 2;</code>
     */
    protected $payload = '';
    /**
     * Request message id, assigned by the client that will be returned in the response.
     *
     * Generated from protobuf field <code>string clientMsgId = 3;</code>
     */
    protected $clientMsgId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *           Contains id of ProtoPayloadType or other custom PayloadTypes (e.g. ProtoOAPayloadType).
     *     @type string $payload
     *           Serialized protobuf message that corresponds to payloadType.
     *     @type string $clientMsgId
     *           Request message id, assigned by the client that will be returned in the response.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiCommonMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Contains id of ProtoPayloadType or other custom PayloadTypes (e.g. ProtoOAPayloadType).
     *
     * Generated from protobuf field <code>uint32 payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Contains id of ProtoPayloadType or other custom PayloadTypes (e.g. ProtoOAPayloadType).
     *
     * Generated from protobuf field <code>uint32 payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkUint32($var);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Serialized protobuf message that corresponds to payloadType.
     *
     * Generated from protobuf field <code>bytes payload = 2;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Serialized protobuf message that corresponds to payloadType.
     *
     * Generated from protobuf field <code>bytes payload = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

    /**
     * Request message id, assigned by the client that will be returned in the response.
     *
     * Generated from protobuf field <code>string clientMsgId = 3;</code>
     * @return string
     */
    public function getClientMsgId()
    {
        return $this->clientMsgId;
    }

    /**
     * Request message id, assigned by the client that will be returned in the response.
     *
     * Generated from protobuf field <code>string clientMsgId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClientMsgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientMsgId = $var;

        return $this;
    }

}

