<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ProtoOADynamicLeverageTier</code>
 */
class ProtoOADynamicLeverageTier extends \Google\Protobuf\Internal\Message
{
    /**
     * Max USD volume (in cents) of the Open Position (per side) to apply specified leverage. Last tier's leverage is applied also to volume above specified.
     *
     * Generated from protobuf field <code>int64 volume = 1;</code>
     */
    protected $volume = 0;
    /**
     * Applied leverage.
     *
     * Generated from protobuf field <code>int32 leverage = 2;</code>
     */
    protected $leverage = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $volume
     *           Max USD volume (in cents) of the Open Position (per side) to apply specified leverage. Last tier's leverage is applied also to volume above specified.
     *     @type int $leverage
     *           Applied leverage.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Max USD volume (in cents) of the Open Position (per side) to apply specified leverage. Last tier's leverage is applied also to volume above specified.
     *
     * Generated from protobuf field <code>int64 volume = 1;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Max USD volume (in cents) of the Open Position (per side) to apply specified leverage. Last tier's leverage is applied also to volume above specified.
     *
     * Generated from protobuf field <code>int64 volume = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkInt64($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * Applied leverage.
     *
     * Generated from protobuf field <code>int32 leverage = 2;</code>
     * @return int
     */
    public function getLeverage()
    {
        return $this->leverage;
    }

    /**
     * Applied leverage.
     *
     * Generated from protobuf field <code>int32 leverage = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLeverage($var)
    {
        GPBUtil::checkInt32($var);
        $this->leverage = $var;

        return $this;
    }

}

