<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Asset entity. 
 *
 * Generated from protobuf message <code>ProtoOAAsset</code>
 */
class ProtoOAAsset extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique asset ID.
     *
     * Generated from protobuf field <code>int64 assetId = 1;</code>
     */
    protected $assetId = 0;
    /**
     * The asset name.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * User friendly name.
     *
     * Generated from protobuf field <code>string displayName = 3;</code>
     */
    protected $displayName = '';
    /**
     * Precision of the asset.
     *
     * Generated from protobuf field <code>int32 digits = 4;</code>
     */
    protected $digits = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $assetId
     *           The unique asset ID.
     *     @type string $name
     *           The asset name.
     *     @type string $displayName
     *           User friendly name.
     *     @type int $digits
     *           Precision of the asset.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique asset ID.
     *
     * Generated from protobuf field <code>int64 assetId = 1;</code>
     * @return int|string
     */
    public function getAssetId()
    {
        return $this->assetId;
    }

    /**
     * The unique asset ID.
     *
     * Generated from protobuf field <code>int64 assetId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAssetId($var)
    {
        GPBUtil::checkInt64($var);
        $this->assetId = $var;

        return $this;
    }

    /**
     * The asset name.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The asset name.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * User friendly name.
     *
     * Generated from protobuf field <code>string displayName = 3;</code>
     * @return string
     */
    public function getDisplayName()
    {
        return $this->displayName;
    }

    /**
     * User friendly name.
     *
     * Generated from protobuf field <code>string displayName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDisplayName($var)
    {
        GPBUtil::checkString($var, True);
        $this->displayName = $var;

        return $this;
    }

    /**
     * Precision of the asset.
     *
     * Generated from protobuf field <code>int32 digits = 4;</code>
     * @return int
     */
    public function getDigits()
    {
        return $this->digits;
    }

    /**
     * Precision of the asset.
     *
     * Generated from protobuf field <code>int32 digits = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDigits($var)
    {
        GPBUtil::checkInt32($var);
        $this->digits = $var;

        return $this;
    }

}

