<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Generic response when an ERROR occurred. 
 *
 * Generated from protobuf message <code>ProtoOAErrorRes</code>
 */
class ProtoOAErrorRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * The unique identifier of the trader's account in cTrader platform.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * The name of the ProtoErrorCode or the other custom ErrorCodes (e.g. ProtoCHErrorCode).
     *
     * Generated from protobuf field <code>string errorCode = 3;</code>
     */
    protected $errorCode = '';
    /**
     * The error description.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     */
    protected $description = '';
    /**
     * The Unix time in seconds when the current maintenance session will be ended.
     *
     * Generated from protobuf field <code>int64 maintenanceEndTimestamp = 5;</code>
     */
    protected $maintenanceEndTimestamp = 0;
    /**
     * When you hit rate limit with errorCode=BLOCKED_PAYLOAD_TYPE, this field will contain amount of seconds until related payload type will be unlocked.
     *
     * Generated from protobuf field <code>uint64 retryAfter = 6;</code>
     */
    protected $retryAfter = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           The unique identifier of the trader's account in cTrader platform.
     *     @type string $errorCode
     *           The name of the ProtoErrorCode or the other custom ErrorCodes (e.g. ProtoCHErrorCode).
     *     @type string $description
     *           The error description.
     *     @type int|string $maintenanceEndTimestamp
     *           The Unix time in seconds when the current maintenance session will be ended.
     *     @type int|string $retryAfter
     *           When you hit rate limit with errorCode=BLOCKED_PAYLOAD_TYPE, this field will contain amount of seconds until related payload type will be unlocked.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * The unique identifier of the trader's account in cTrader platform.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * The unique identifier of the trader's account in cTrader platform.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * The name of the ProtoErrorCode or the other custom ErrorCodes (e.g. ProtoCHErrorCode).
     *
     * Generated from protobuf field <code>string errorCode = 3;</code>
     * @return string
     */
    public function getErrorCode()
    {
        return $this->errorCode;
    }

    /**
     * The name of the ProtoErrorCode or the other custom ErrorCodes (e.g. ProtoCHErrorCode).
     *
     * Generated from protobuf field <code>string errorCode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->errorCode = $var;

        return $this;
    }

    /**
     * The error description.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * The error description.
     *
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * The Unix time in seconds when the current maintenance session will be ended.
     *
     * Generated from protobuf field <code>int64 maintenanceEndTimestamp = 5;</code>
     * @return int|string
     */
    public function getMaintenanceEndTimestamp()
    {
        return $this->maintenanceEndTimestamp;
    }

    /**
     * The Unix time in seconds when the current maintenance session will be ended.
     *
     * Generated from protobuf field <code>int64 maintenanceEndTimestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaintenanceEndTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->maintenanceEndTimestamp = $var;

        return $this;
    }

    /**
     * When you hit rate limit with errorCode=BLOCKED_PAYLOAD_TYPE, this field will contain amount of seconds until related payload type will be unlocked.
     *
     * Generated from protobuf field <code>uint64 retryAfter = 6;</code>
     * @return int|string
     */
    public function getRetryAfter()
    {
        return $this->retryAfter;
    }

    /**
     * When you hit rate limit with errorCode=BLOCKED_PAYLOAD_TYPE, this field will contain amount of seconds until related payload type will be unlocked.
     *
     * Generated from protobuf field <code>uint64 retryAfter = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRetryAfter($var)
    {
        GPBUtil::checkUint64($var);
        $this->retryAfter = $var;

        return $this;
    }

}

