<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Event that is sent when the structure of depth of market is changed. Requires subscription on the depth of markets for the symbol, see ProtoOASubscribeDepthQuotesReq. 
 *
 * Generated from protobuf message <code>ProtoOADepthEvent</code>
 */
class ProtoOADepthEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * Unique identifier of the Symbol in cTrader platform.
     *
     * Generated from protobuf field <code>uint64 symbolId = 3;</code>
     */
    protected $symbolId = 0;
    /**
     * The list of changes in the depth of market quotes.
     *
     * Generated from protobuf field <code>repeated .ProtoOADepthQuote newQuotes = 4;</code>
     */
    private $newQuotes;
    /**
     * The list of quotes to delete.
     *
     * Generated from protobuf field <code>repeated uint64 deletedQuotes = 5 [packed = true];</code>
     */
    private $deletedQuotes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type int|string $symbolId
     *           Unique identifier of the Symbol in cTrader platform.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOADepthQuote[]|\Google\Protobuf\Internal\RepeatedField $newQuotes
     *           The list of changes in the depth of market quotes.
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $deletedQuotes
     *           The list of quotes to delete.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * Unique identifier of the Symbol in cTrader platform.
     *
     * Generated from protobuf field <code>uint64 symbolId = 3;</code>
     * @return int|string
     */
    public function getSymbolId()
    {
        return $this->symbolId;
    }

    /**
     * Unique identifier of the Symbol in cTrader platform.
     *
     * Generated from protobuf field <code>uint64 symbolId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSymbolId($var)
    {
        GPBUtil::checkUint64($var);
        $this->symbolId = $var;

        return $this;
    }

    /**
     * The list of changes in the depth of market quotes.
     *
     * Generated from protobuf field <code>repeated .ProtoOADepthQuote newQuotes = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNewQuotes()
    {
        return $this->newQuotes;
    }

    /**
     * The list of changes in the depth of market quotes.
     *
     * Generated from protobuf field <code>repeated .ProtoOADepthQuote newQuotes = 4;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOADepthQuote[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNewQuotes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOADepthQuote::class);
        $this->newQuotes = $arr;

        return $this;
    }

    /**
     * The list of quotes to delete.
     *
     * Generated from protobuf field <code>repeated uint64 deletedQuotes = 5 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeletedQuotes()
    {
        return $this->deletedQuotes;
    }

    /**
     * The list of quotes to delete.
     *
     * Generated from protobuf field <code>repeated uint64 deletedQuotes = 5 [packed = true];</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeletedQuotes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->deletedQuotes = $arr;

        return $this;
    }

}

