<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 * Protobuf type <code>ProtoOADayOfWeek</code>
 */
class ProtoOADayOfWeek
{
    /**
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * Generated from protobuf enum <code>MONDAY = 1;</code>
     */
    const MONDAY = 1;
    /**
     * Generated from protobuf enum <code>TUESDAY = 2;</code>
     */
    const TUESDAY = 2;
    /**
     * Generated from protobuf enum <code>WEDNESDAY = 3;</code>
     */
    const WEDNESDAY = 3;
    /**
     * Generated from protobuf enum <code>THURSDAY = 4;</code>
     */
    const THURSDAY = 4;
    /**
     * Generated from protobuf enum <code>FRIDAY = 5;</code>
     */
    const FRIDAY = 5;
    /**
     * Generated from protobuf enum <code>SATURDAY = 6;</code>
     */
    const SATURDAY = 6;
    /**
     * Generated from protobuf enum <code>SUNDAY = 7;</code>
     */
    const SUNDAY = 7;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::MONDAY => 'MONDAY',
        self::TUESDAY => 'TUESDAY',
        self::WEDNESDAY => 'WEDNESDAY',
        self::THURSDAY => 'THURSDAY',
        self::FRIDAY => 'FRIDAY',
        self::SATURDAY => 'SATURDAY',
        self::SUNDAY => 'SUNDAY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

