<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Event that is sent following the successful order acceptance or execution by the server. Acts as response to the ProtoOANewOrderReq, ProtoOACancelOrderReq, ProtoOAAmendOrderReq, ProtoOAAmendPositionSLTPReq, ProtoOAClosePositionReq requests. Also, the event is sent when a Deposit/Withdrawal took place. 
 *
 * Generated from protobuf message <code>ProtoOAExecutionEvent</code>
 */
class ProtoOAExecutionEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * Type of the order operation. For example: ACCEPTED, FILLED, etc.
     *
     * Generated from protobuf field <code>.ProtoOAExecutionType executionType = 3;</code>
     */
    protected $executionType = 0;
    /**
     * Reference to the position linked with the execution
     *
     * Generated from protobuf field <code>.ProtoOAPosition position = 4;</code>
     */
    protected $position = null;
    /**
     * Reference to the initial order.
     *
     * Generated from protobuf field <code>.ProtoOAOrder order = 5;</code>
     */
    protected $order = null;
    /**
     * Reference to the deal (execution).
     *
     * Generated from protobuf field <code>.ProtoOADeal deal = 6;</code>
     */
    protected $deal = null;
    /**
     * Reference to the Bonus Deposit or Withdrawal operation.
     *
     * Generated from protobuf field <code>.ProtoOABonusDepositWithdraw bonusDepositWithdraw = 7;</code>
     */
    protected $bonusDepositWithdraw = null;
    /**
     * Reference to the Deposit or Withdrawal operation.
     *
     * Generated from protobuf field <code>.ProtoOADepositWithdraw depositWithdraw = 8;</code>
     */
    protected $depositWithdraw = null;
    /**
     * The name of the ProtoErrorCode or the other custom ErrorCodes (e.g. ProtoCHErrorCode).
     *
     * Generated from protobuf field <code>string errorCode = 9;</code>
     */
    protected $errorCode = '';
    /**
     * If TRUE then the event generated by the server logic instead of the trader's request. (e.g. stop-out).
     *
     * Generated from protobuf field <code>bool isServerEvent = 10;</code>
     */
    protected $isServerEvent = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type int $executionType
     *           Type of the order operation. For example: ACCEPTED, FILLED, etc.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOAPosition $position
     *           Reference to the position linked with the execution
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrder $order
     *           Reference to the initial order.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOADeal $deal
     *           Reference to the deal (execution).
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOABonusDepositWithdraw $bonusDepositWithdraw
     *           Reference to the Bonus Deposit or Withdrawal operation.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOADepositWithdraw $depositWithdraw
     *           Reference to the Deposit or Withdrawal operation.
     *     @type string $errorCode
     *           The name of the ProtoErrorCode or the other custom ErrorCodes (e.g. ProtoCHErrorCode).
     *     @type bool $isServerEvent
     *           If TRUE then the event generated by the server logic instead of the trader's request. (e.g. stop-out).
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * Type of the order operation. For example: ACCEPTED, FILLED, etc.
     *
     * Generated from protobuf field <code>.ProtoOAExecutionType executionType = 3;</code>
     * @return int
     */
    public function getExecutionType()
    {
        return $this->executionType;
    }

    /**
     * Type of the order operation. For example: ACCEPTED, FILLED, etc.
     *
     * Generated from protobuf field <code>.ProtoOAExecutionType executionType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setExecutionType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAExecutionType::class);
        $this->executionType = $var;

        return $this;
    }

    /**
     * Reference to the position linked with the execution
     *
     * Generated from protobuf field <code>.ProtoOAPosition position = 4;</code>
     * @return \SocialiteProviders\Ctrader\Protobuf\ProtoOAPosition
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * Reference to the position linked with the execution
     *
     * Generated from protobuf field <code>.ProtoOAPosition position = 4;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOAPosition $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkMessage($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPosition::class);
        $this->position = $var;

        return $this;
    }

    /**
     * Reference to the initial order.
     *
     * Generated from protobuf field <code>.ProtoOAOrder order = 5;</code>
     * @return \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrder
     */
    public function getOrder()
    {
        return $this->order;
    }

    /**
     * Reference to the initial order.
     *
     * Generated from protobuf field <code>.ProtoOAOrder order = 5;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrder $var
     * @return $this
     */
    public function setOrder($var)
    {
        GPBUtil::checkMessage($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrder::class);
        $this->order = $var;

        return $this;
    }

    /**
     * Reference to the deal (execution).
     *
     * Generated from protobuf field <code>.ProtoOADeal deal = 6;</code>
     * @return \SocialiteProviders\Ctrader\Protobuf\ProtoOADeal
     */
    public function getDeal()
    {
        return $this->deal;
    }

    /**
     * Reference to the deal (execution).
     *
     * Generated from protobuf field <code>.ProtoOADeal deal = 6;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOADeal $var
     * @return $this
     */
    public function setDeal($var)
    {
        GPBUtil::checkMessage($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOADeal::class);
        $this->deal = $var;

        return $this;
    }

    /**
     * Reference to the Bonus Deposit or Withdrawal operation.
     *
     * Generated from protobuf field <code>.ProtoOABonusDepositWithdraw bonusDepositWithdraw = 7;</code>
     * @return \SocialiteProviders\Ctrader\Protobuf\ProtoOABonusDepositWithdraw
     */
    public function getBonusDepositWithdraw()
    {
        return $this->bonusDepositWithdraw;
    }

    /**
     * Reference to the Bonus Deposit or Withdrawal operation.
     *
     * Generated from protobuf field <code>.ProtoOABonusDepositWithdraw bonusDepositWithdraw = 7;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOABonusDepositWithdraw $var
     * @return $this
     */
    public function setBonusDepositWithdraw($var)
    {
        GPBUtil::checkMessage($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOABonusDepositWithdraw::class);
        $this->bonusDepositWithdraw = $var;

        return $this;
    }

    /**
     * Reference to the Deposit or Withdrawal operation.
     *
     * Generated from protobuf field <code>.ProtoOADepositWithdraw depositWithdraw = 8;</code>
     * @return \SocialiteProviders\Ctrader\Protobuf\ProtoOADepositWithdraw
     */
    public function getDepositWithdraw()
    {
        return $this->depositWithdraw;
    }

    /**
     * Reference to the Deposit or Withdrawal operation.
     *
     * Generated from protobuf field <code>.ProtoOADepositWithdraw depositWithdraw = 8;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOADepositWithdraw $var
     * @return $this
     */
    public function setDepositWithdraw($var)
    {
        GPBUtil::checkMessage($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOADepositWithdraw::class);
        $this->depositWithdraw = $var;

        return $this;
    }

    /**
     * The name of the ProtoErrorCode or the other custom ErrorCodes (e.g. ProtoCHErrorCode).
     *
     * Generated from protobuf field <code>string errorCode = 9;</code>
     * @return string
     */
    public function getErrorCode()
    {
        return $this->errorCode;
    }

    /**
     * The name of the ProtoErrorCode or the other custom ErrorCodes (e.g. ProtoCHErrorCode).
     *
     * Generated from protobuf field <code>string errorCode = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->errorCode = $var;

        return $this;
    }

    /**
     * If TRUE then the event generated by the server logic instead of the trader's request. (e.g. stop-out).
     *
     * Generated from protobuf field <code>bool isServerEvent = 10;</code>
     * @return bool
     */
    public function getIsServerEvent()
    {
        return $this->isServerEvent;
    }

    /**
     * If TRUE then the event generated by the server logic instead of the trader's request. (e.g. stop-out).
     *
     * Generated from protobuf field <code>bool isServerEvent = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsServerEvent($var)
    {
        GPBUtil::checkBool($var);
        $this->isServerEvent = $var;

        return $this;
    }

}

