<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Enum for specifying type of an account. 
 *
 * Protobuf type <code>ProtoOAAccountType</code>
 */
class ProtoOAAccountType
{
    /**
     * Allows multiple positions on a trading account for a symbol.
     *
     * Generated from protobuf enum <code>HEDGED = 0;</code>
     */
    const HEDGED = 0;
    /**
     * Only one position per symbol is allowed on a trading account.
     *
     * Generated from protobuf enum <code>NETTED = 1;</code>
     */
    const NETTED = 1;
    /**
     * Spread betting type account.
     *
     * Generated from protobuf enum <code>SPREAD_BETTING = 2;</code>
     */
    const SPREAD_BETTING = 2;

    private static $valueToName = [
        self::HEDGED => 'HEDGED',
        self::NETTED => 'NETTED',
        self::SPREAD_BETTING => 'SPREAD_BETTING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

