<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Event that is sent when the margin allocated to a specific position is changed. 
 *
 * Generated from protobuf message <code>ProtoOAMarginChangedEvent</code>
 */
class ProtoOAMarginChangedEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * The unique ID of the position.
     *
     * Generated from protobuf field <code>uint64 positionId = 3;</code>
     */
    protected $positionId = 0;
    /**
     * The new value of the margin used.
     *
     * Generated from protobuf field <code>uint64 usedMargin = 4;</code>
     */
    protected $usedMargin = 0;
    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects usedMargin.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 5;</code>
     */
    protected $moneyDigits = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type int|string $positionId
     *           The unique ID of the position.
     *     @type int|string $usedMargin
     *           The new value of the margin used.
     *     @type int $moneyDigits
     *           Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects usedMargin.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * The unique ID of the position.
     *
     * Generated from protobuf field <code>uint64 positionId = 3;</code>
     * @return int|string
     */
    public function getPositionId()
    {
        return $this->positionId;
    }

    /**
     * The unique ID of the position.
     *
     * Generated from protobuf field <code>uint64 positionId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPositionId($var)
    {
        GPBUtil::checkUint64($var);
        $this->positionId = $var;

        return $this;
    }

    /**
     * The new value of the margin used.
     *
     * Generated from protobuf field <code>uint64 usedMargin = 4;</code>
     * @return int|string
     */
    public function getUsedMargin()
    {
        return $this->usedMargin;
    }

    /**
     * The new value of the margin used.
     *
     * Generated from protobuf field <code>uint64 usedMargin = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUsedMargin($var)
    {
        GPBUtil::checkUint64($var);
        $this->usedMargin = $var;

        return $this;
    }

    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects usedMargin.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 5;</code>
     * @return int
     */
    public function getMoneyDigits()
    {
        return $this->moneyDigits;
    }

    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects usedMargin.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMoneyDigits($var)
    {
        GPBUtil::checkUint32($var);
        $this->moneyDigits = $var;

        return $this;
    }

}

