<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Response to the ProtoOAGetTickDataReq request. 
 *
 * Generated from protobuf message <code>ProtoOAGetTickDataRes</code>
 */
class ProtoOAGetTickDataRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * The list of ticks is in chronological order (newest first). The first tick contains Unix time in milliseconds while all subsequent ticks have the time difference in milliseconds between the previous and the current one.
     *
     * Generated from protobuf field <code>repeated .ProtoOATickData tickData = 3;</code>
     */
    private $tickData;
    /**
     * If TRUE then the number of records by filter is larger than chunkSize, the response contains the number of records that is equal to chunkSize.
     *
     * Generated from protobuf field <code>bool hasMore = 4;</code>
     */
    protected $hasMore = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOATickData[]|\Google\Protobuf\Internal\RepeatedField $tickData
     *           The list of ticks is in chronological order (newest first). The first tick contains Unix time in milliseconds while all subsequent ticks have the time difference in milliseconds between the previous and the current one.
     *     @type bool $hasMore
     *           If TRUE then the number of records by filter is larger than chunkSize, the response contains the number of records that is equal to chunkSize.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * The list of ticks is in chronological order (newest first). The first tick contains Unix time in milliseconds while all subsequent ticks have the time difference in milliseconds between the previous and the current one.
     *
     * Generated from protobuf field <code>repeated .ProtoOATickData tickData = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTickData()
    {
        return $this->tickData;
    }

    /**
     * The list of ticks is in chronological order (newest first). The first tick contains Unix time in milliseconds while all subsequent ticks have the time difference in milliseconds between the previous and the current one.
     *
     * Generated from protobuf field <code>repeated .ProtoOATickData tickData = 3;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOATickData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTickData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOATickData::class);
        $this->tickData = $arr;

        return $this;
    }

    /**
     * If TRUE then the number of records by filter is larger than chunkSize, the response contains the number of records that is equal to chunkSize.
     *
     * Generated from protobuf field <code>bool hasMore = 4;</code>
     * @return bool
     */
    public function getHasMore()
    {
        return $this->hasMore;
    }

    /**
     * If TRUE then the number of records by filter is larger than chunkSize, the response contains the number of records that is equal to chunkSize.
     *
     * Generated from protobuf field <code>bool hasMore = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasMore($var)
    {
        GPBUtil::checkBool($var);
        $this->hasMore = $var;

        return $this;
    }

}

