<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiCommonMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Error response that is sent from Open API proxy when error occurs. 
 *
 * Generated from protobuf message <code>ProtoErrorRes</code>
 */
class ProtoErrorRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Contains name of ProtoErrorCode or other custom ErrorCodes (e.g. ProtoCHErrorCode).
     *
     * Generated from protobuf field <code>string errorCode = 2;</code>
     */
    protected $errorCode = '';
    /**
     * Error description.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * The Unix time in milliseconds of the end of the maintenance.
     *
     * Generated from protobuf field <code>uint64 maintenanceEndTimestamp = 4;</code>
     */
    protected $maintenanceEndTimestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type string $errorCode
     *           Contains name of ProtoErrorCode or other custom ErrorCodes (e.g. ProtoCHErrorCode).
     *     @type string $description
     *           Error description.
     *     @type int|string $maintenanceEndTimestamp
     *           The Unix time in milliseconds of the end of the maintenance.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiCommonMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Contains name of ProtoErrorCode or other custom ErrorCodes (e.g. ProtoCHErrorCode).
     *
     * Generated from protobuf field <code>string errorCode = 2;</code>
     * @return string
     */
    public function getErrorCode()
    {
        return $this->errorCode;
    }

    /**
     * Contains name of ProtoErrorCode or other custom ErrorCodes (e.g. ProtoCHErrorCode).
     *
     * Generated from protobuf field <code>string errorCode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->errorCode = $var;

        return $this;
    }

    /**
     * Error description.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Error description.
     *
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds of the end of the maintenance.
     *
     * Generated from protobuf field <code>uint64 maintenanceEndTimestamp = 4;</code>
     * @return int|string
     */
    public function getMaintenanceEndTimestamp()
    {
        return $this->maintenanceEndTimestamp;
    }

    /**
     * The Unix time in milliseconds of the end of the maintenance.
     *
     * Generated from protobuf field <code>uint64 maintenanceEndTimestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaintenanceEndTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->maintenanceEndTimestamp = $var;

        return $this;
    }

}

