<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Bonus operation type ENUM. 
 *
 * Protobuf type <code>ProtoOAChangeBonusType</code>
 */
class ProtoOAChangeBonusType
{
    /**
     * Generated from protobuf enum <code>BONUS_DEPOSIT = 0;</code>
     */
    const BONUS_DEPOSIT = 0;
    /**
     * Generated from protobuf enum <code>BONUS_WITHDRAW = 1;</code>
     */
    const BONUS_WITHDRAW = 1;

    private static $valueToName = [
        self::BONUS_DEPOSIT => 'BONUS_DEPOSIT',
        self::BONUS_WITHDRAW => 'BONUS_WITHDRAW',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

