<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Trendbar period ENUM. 
 *
 * Protobuf type <code>ProtoOATrendbarPeriod</code>
 */
class ProtoOATrendbarPeriod
{
    /**
     * Generated from protobuf enum <code>TRENDBAR_PERIOD_UNKNOWN = 0;</code>
     */
    const TRENDBAR_PERIOD_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>M1 = 1;</code>
     */
    const M1 = 1;
    /**
     * Generated from protobuf enum <code>M2 = 2;</code>
     */
    const M2 = 2;
    /**
     * Generated from protobuf enum <code>M3 = 3;</code>
     */
    const M3 = 3;
    /**
     * Generated from protobuf enum <code>M4 = 4;</code>
     */
    const M4 = 4;
    /**
     * Generated from protobuf enum <code>M5 = 5;</code>
     */
    const M5 = 5;
    /**
     * Generated from protobuf enum <code>M10 = 6;</code>
     */
    const M10 = 6;
    /**
     * Generated from protobuf enum <code>M15 = 7;</code>
     */
    const M15 = 7;
    /**
     * Generated from protobuf enum <code>M30 = 8;</code>
     */
    const M30 = 8;
    /**
     * Generated from protobuf enum <code>H1 = 9;</code>
     */
    const H1 = 9;
    /**
     * Generated from protobuf enum <code>H4 = 10;</code>
     */
    const H4 = 10;
    /**
     * Generated from protobuf enum <code>H12 = 11;</code>
     */
    const H12 = 11;
    /**
     * Generated from protobuf enum <code>D1 = 12;</code>
     */
    const D1 = 12;
    /**
     * Generated from protobuf enum <code>W1 = 13;</code>
     */
    const W1 = 13;
    /**
     * Generated from protobuf enum <code>MN1 = 14;</code>
     */
    const MN1 = 14;

    private static $valueToName = [
        self::TRENDBAR_PERIOD_UNKNOWN => 'TRENDBAR_PERIOD_UNKNOWN',
        self::M1 => 'M1',
        self::M2 => 'M2',
        self::M3 => 'M3',
        self::M4 => 'M4',
        self::M5 => 'M5',
        self::M10 => 'M10',
        self::M15 => 'M15',
        self::M30 => 'M30',
        self::H1 => 'H1',
        self::H4 => 'H4',
        self::H12 => 'H12',
        self::D1 => 'D1',
        self::W1 => 'W1',
        self::MN1 => 'MN1',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

