<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Request for retrieving Orders related to a Position by using Position ID. Filtered by utcLastUpdateTimestamp. 
 *
 * Generated from protobuf message <code>ProtoOAOrderListByPositionIdReq</code>
 */
class ProtoOAOrderListByPositionIdReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * The unique ID of the Position.
     *
     * Generated from protobuf field <code>int64 positionId = 3;</code>
     */
    protected $positionId = 0;
    /**
     * The Unix time from which the search starts >=0 (1st Jan 1970). Search by utcLastUpdateTimestamp of the Order.
     *
     * Generated from protobuf field <code>int64 fromTimestamp = 4;</code>
     */
    protected $fromTimestamp = 0;
    /**
     * The Unix time where to stop searching <= 2147483646000 (19th Jan 2038). Search by utcLastUpdateTimestamp of the Order.
     *
     * Generated from protobuf field <code>int64 toTimestamp = 5;</code>
     */
    protected $toTimestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type int|string $positionId
     *           The unique ID of the Position.
     *     @type int|string $fromTimestamp
     *           The Unix time from which the search starts >=0 (1st Jan 1970). Search by utcLastUpdateTimestamp of the Order.
     *     @type int|string $toTimestamp
     *           The Unix time where to stop searching <= 2147483646000 (19th Jan 2038). Search by utcLastUpdateTimestamp of the Order.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * The unique ID of the Position.
     *
     * Generated from protobuf field <code>int64 positionId = 3;</code>
     * @return int|string
     */
    public function getPositionId()
    {
        return $this->positionId;
    }

    /**
     * The unique ID of the Position.
     *
     * Generated from protobuf field <code>int64 positionId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPositionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->positionId = $var;

        return $this;
    }

    /**
     * The Unix time from which the search starts >=0 (1st Jan 1970). Search by utcLastUpdateTimestamp of the Order.
     *
     * Generated from protobuf field <code>int64 fromTimestamp = 4;</code>
     * @return int|string
     */
    public function getFromTimestamp()
    {
        return $this->fromTimestamp;
    }

    /**
     * The Unix time from which the search starts >=0 (1st Jan 1970). Search by utcLastUpdateTimestamp of the Order.
     *
     * Generated from protobuf field <code>int64 fromTimestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFromTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->fromTimestamp = $var;

        return $this;
    }

    /**
     * The Unix time where to stop searching <= 2147483646000 (19th Jan 2038). Search by utcLastUpdateTimestamp of the Order.
     *
     * Generated from protobuf field <code>int64 toTimestamp = 5;</code>
     * @return int|string
     */
    public function getToTimestamp()
    {
        return $this->toTimestamp;
    }

    /**
     * The Unix time where to stop searching <= 2147483646000 (19th Jan 2038). Search by utcLastUpdateTimestamp of the Order.
     *
     * Generated from protobuf field <code>int64 toTimestamp = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setToTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->toTimestamp = $var;

        return $this;
    }

}

