<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Enum for specifying margin calculation type for an account. 
 *
 * Protobuf type <code>ProtoOATotalMarginCalculationType</code>
 */
class ProtoOATotalMarginCalculationType
{
    /**
     * Generated from protobuf enum <code>MAX = 0;</code>
     */
    const MAX = 0;
    /**
     * Generated from protobuf enum <code>SUM = 1;</code>
     */
    const SUM = 1;
    /**
     * Generated from protobuf enum <code>NET = 2;</code>
     */
    const NET = 2;

    private static $valueToName = [
        self::MAX => 'MAX',
        self::SUM => 'SUM',
        self::NET => 'NET',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

