<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Type of notification, currently only 3 instances of marginCall are supported. 
 *
 * Protobuf type <code>ProtoOANotificationType</code>
 */
class ProtoOANotificationType
{
    /**
     * Generated from protobuf enum <code>NOTIFICATION_TYPE_UNKNOWN = 0;</code>
     */
    const NOTIFICATION_TYPE_UNKNOWN = 0;
    /**
     * one of three margin calls, they are all similar.
     *
     * Generated from protobuf enum <code>MARGIN_LEVEL_THRESHOLD_1 = 61;</code>
     */
    const MARGIN_LEVEL_THRESHOLD_1 = 61;
    /**
     * one of three margin calls, they are all similar.
     *
     * Generated from protobuf enum <code>MARGIN_LEVEL_THRESHOLD_2 = 62;</code>
     */
    const MARGIN_LEVEL_THRESHOLD_2 = 62;
    /**
     * one of three margin calls, they are all similar.
     *
     * Generated from protobuf enum <code>MARGIN_LEVEL_THRESHOLD_3 = 63;</code>
     */
    const MARGIN_LEVEL_THRESHOLD_3 = 63;

    private static $valueToName = [
        self::NOTIFICATION_TYPE_UNKNOWN => 'NOTIFICATION_TYPE_UNKNOWN',
        self::MARGIN_LEVEL_THRESHOLD_1 => 'MARGIN_LEVEL_THRESHOLD_1',
        self::MARGIN_LEVEL_THRESHOLD_2 => 'MARGIN_LEVEL_THRESHOLD_2',
        self::MARGIN_LEVEL_THRESHOLD_3 => 'MARGIN_LEVEL_THRESHOLD_3',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

