<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Event that is sent when the level of the Trailing Stop Loss is changed due to the price level changes. 
 *
 * Generated from protobuf message <code>ProtoOATrailingSLChangedEvent</code>
 */
class ProtoOATrailingSLChangedEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * The unique ID of the position.
     *
     * Generated from protobuf field <code>int64 positionId = 3;</code>
     */
    protected $positionId = 0;
    /**
     * The unique ID of the order.
     *
     * Generated from protobuf field <code>int64 orderId = 4;</code>
     */
    protected $orderId = 0;
    /**
     * New value of the Stop Loss price.
     *
     * Generated from protobuf field <code>double stopPrice = 5;</code>
     */
    protected $stopPrice = 0.0;
    /**
     * The Unix time in milliseconds when the Stop Loss was updated.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 6;</code>
     */
    protected $utcLastUpdateTimestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type int|string $positionId
     *           The unique ID of the position.
     *     @type int|string $orderId
     *           The unique ID of the order.
     *     @type float $stopPrice
     *           New value of the Stop Loss price.
     *     @type int|string $utcLastUpdateTimestamp
     *           The Unix time in milliseconds when the Stop Loss was updated.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * The unique ID of the position.
     *
     * Generated from protobuf field <code>int64 positionId = 3;</code>
     * @return int|string
     */
    public function getPositionId()
    {
        return $this->positionId;
    }

    /**
     * The unique ID of the position.
     *
     * Generated from protobuf field <code>int64 positionId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPositionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->positionId = $var;

        return $this;
    }

    /**
     * The unique ID of the order.
     *
     * Generated from protobuf field <code>int64 orderId = 4;</code>
     * @return int|string
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * The unique ID of the order.
     *
     * Generated from protobuf field <code>int64 orderId = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt64($var);
        $this->orderId = $var;

        return $this;
    }

    /**
     * New value of the Stop Loss price.
     *
     * Generated from protobuf field <code>double stopPrice = 5;</code>
     * @return float
     */
    public function getStopPrice()
    {
        return $this->stopPrice;
    }

    /**
     * New value of the Stop Loss price.
     *
     * Generated from protobuf field <code>double stopPrice = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setStopPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->stopPrice = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds when the Stop Loss was updated.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 6;</code>
     * @return int|string
     */
    public function getUtcLastUpdateTimestamp()
    {
        return $this->utcLastUpdateTimestamp;
    }

    /**
     * The Unix time in milliseconds when the Stop Loss was updated.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUtcLastUpdateTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->utcLastUpdateTimestamp = $var;

        return $this;
    }

}

