<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Response to the ProtoOAGetCtidProfileByTokenReq request. 
 *
 * Generated from protobuf message <code>ProtoOAGetCtidProfileByTokenRes</code>
 */
class ProtoOAGetCtidProfileByTokenRes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Trader's profile.
     *
     * Generated from protobuf field <code>.ProtoOACtidProfile profile = 2;</code>
     */
    protected $profile = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOACtidProfile $profile
     *           Trader's profile.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Trader's profile.
     *
     * Generated from protobuf field <code>.ProtoOACtidProfile profile = 2;</code>
     * @return \SocialiteProviders\Ctrader\Protobuf\ProtoOACtidProfile
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * Trader's profile.
     *
     * Generated from protobuf field <code>.ProtoOACtidProfile profile = 2;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOACtidProfile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOACtidProfile::class);
        $this->profile = $var;

        return $this;
    }

}

