<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Trade order entity. 
 *
 * Generated from protobuf message <code>ProtoOAOrder</code>
 */
class ProtoOAOrder extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique ID of the order. Note: trader might have two orders with the same id if orders are taken from accounts from different brokers.
     *
     * Generated from protobuf field <code>int64 orderId = 1;</code>
     */
    protected $orderId = 0;
    /**
     * Detailed trader data.
     *
     * Generated from protobuf field <code>.ProtoOATradeData tradeData = 2;</code>
     */
    protected $tradeData = null;
    /**
     * Order type.
     *
     * Generated from protobuf field <code>.ProtoOAOrderType orderType = 3;</code>
     */
    protected $orderType = 0;
    /**
     * Order status.
     *
     * Generated from protobuf field <code>.ProtoOAOrderStatus orderStatus = 4;</code>
     */
    protected $orderStatus = 0;
    /**
     * The Unix time in milliseconds of expiration if the order has time in force GTD.
     *
     * Generated from protobuf field <code>int64 expirationTimestamp = 6;</code>
     */
    protected $expirationTimestamp = 0;
    /**
     * Price at which an order was executed. For order with FILLED status.
     *
     * Generated from protobuf field <code>double executionPrice = 7;</code>
     */
    protected $executionPrice = 0.0;
    /**
     * Part of the volume that was filled in cents (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>int64 executedVolume = 8;</code>
     */
    protected $executedVolume = 0;
    /**
     * The Unix time in milliseconds of the last update of the order.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 9;</code>
     */
    protected $utcLastUpdateTimestamp = 0;
    /**
     * Used for Market Range order with combination of slippageInPoints to specify price range were order can be executed.
     *
     * Generated from protobuf field <code>double baseSlippagePrice = 10;</code>
     */
    protected $baseSlippagePrice = 0.0;
    /**
     * Used for Market Range and STOP_LIMIT orders to to specify price range were order can be executed.
     *
     * Generated from protobuf field <code>int64 slippageInPoints = 11;</code>
     */
    protected $slippageInPoints = 0;
    /**
     * If TRUE then the order is closing part of whole position. Must have specified positionId.
     *
     * Generated from protobuf field <code>bool closingOrder = 12;</code>
     */
    protected $closingOrder = false;
    /**
     * Valid only for LIMIT orders.
     *
     * Generated from protobuf field <code>double limitPrice = 13;</code>
     */
    protected $limitPrice = 0.0;
    /**
     * Valid only for STOP and STOP_LIMIT orders.
     *
     * Generated from protobuf field <code>double stopPrice = 14;</code>
     */
    protected $stopPrice = 0.0;
    /**
     * Absolute stopLoss price.
     *
     * Generated from protobuf field <code>double stopLoss = 15;</code>
     */
    protected $stopLoss = 0.0;
    /**
     * Absolute takeProfit price.
     *
     * Generated from protobuf field <code>double takeProfit = 16;</code>
     */
    protected $takeProfit = 0.0;
    /**
     * Optional ClientOrderId. Max Length = 50 chars.
     *
     * Generated from protobuf field <code>string clientOrderId = 17;</code>
     */
    protected $clientOrderId = '';
    /**
     * Order's time in force. Depends on order type.
     *
     * Generated from protobuf field <code>.ProtoOATimeInForce timeInForce = 18;</code>
     */
    protected $timeInForce = 0;
    /**
     * ID of the position linked to the order (e.g. closing order, order that increase volume of a specific position, etc.).
     *
     * Generated from protobuf field <code>int64 positionId = 19;</code>
     */
    protected $positionId = 0;
    /**
     * Relative stopLoss that can be specified instead of absolute as one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY stopLoss = entryPrice - relativeStopLoss, for SELL stopLoss = entryPrice + relativeStopLoss.
     *
     * Generated from protobuf field <code>int64 relativeStopLoss = 20;</code>
     */
    protected $relativeStopLoss = 0;
    /**
     * Relative takeProfit that can be specified instead of absolute one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) ForBUY takeProfit = entryPrice + relativeTakeProfit, for SELL takeProfit = entryPrice - relativeTakeProfit.
     *
     * Generated from protobuf field <code>int64 relativeTakeProfit = 21;</code>
     */
    protected $relativeTakeProfit = 0;
    /**
     * If TRUE then order was stopped out from server side.
     *
     * Generated from protobuf field <code>bool isStopOut = 22;</code>
     */
    protected $isStopOut = false;
    /**
     * If TRUE then order is trailingStopLoss. Valid for STOP_LOSS_TAKE_PROFIT order.
     *
     * Generated from protobuf field <code>bool trailingStopLoss = 23;</code>
     */
    protected $trailingStopLoss = false;
    /**
     * Trigger method for the order. Valid only for STOP and STOP_LIMIT orders.
     *
     * Generated from protobuf field <code>.ProtoOAOrderTriggerMethod stopTriggerMethod = 24;</code>
     */
    protected $stopTriggerMethod = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $orderId
     *           The unique ID of the order. Note: trader might have two orders with the same id if orders are taken from accounts from different brokers.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOATradeData $tradeData
     *           Detailed trader data.
     *     @type int $orderType
     *           Order type.
     *     @type int $orderStatus
     *           Order status.
     *     @type int|string $expirationTimestamp
     *           The Unix time in milliseconds of expiration if the order has time in force GTD.
     *     @type float $executionPrice
     *           Price at which an order was executed. For order with FILLED status.
     *     @type int|string $executedVolume
     *           Part of the volume that was filled in cents (e.g. 1000 in protocol means 10.00 units).
     *     @type int|string $utcLastUpdateTimestamp
     *           The Unix time in milliseconds of the last update of the order.
     *     @type float $baseSlippagePrice
     *           Used for Market Range order with combination of slippageInPoints to specify price range were order can be executed.
     *     @type int|string $slippageInPoints
     *           Used for Market Range and STOP_LIMIT orders to to specify price range were order can be executed.
     *     @type bool $closingOrder
     *           If TRUE then the order is closing part of whole position. Must have specified positionId.
     *     @type float $limitPrice
     *           Valid only for LIMIT orders.
     *     @type float $stopPrice
     *           Valid only for STOP and STOP_LIMIT orders.
     *     @type float $stopLoss
     *           Absolute stopLoss price.
     *     @type float $takeProfit
     *           Absolute takeProfit price.
     *     @type string $clientOrderId
     *           Optional ClientOrderId. Max Length = 50 chars.
     *     @type int $timeInForce
     *           Order's time in force. Depends on order type.
     *     @type int|string $positionId
     *           ID of the position linked to the order (e.g. closing order, order that increase volume of a specific position, etc.).
     *     @type int|string $relativeStopLoss
     *           Relative stopLoss that can be specified instead of absolute as one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY stopLoss = entryPrice - relativeStopLoss, for SELL stopLoss = entryPrice + relativeStopLoss.
     *     @type int|string $relativeTakeProfit
     *           Relative takeProfit that can be specified instead of absolute one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) ForBUY takeProfit = entryPrice + relativeTakeProfit, for SELL takeProfit = entryPrice - relativeTakeProfit.
     *     @type bool $isStopOut
     *           If TRUE then order was stopped out from server side.
     *     @type bool $trailingStopLoss
     *           If TRUE then order is trailingStopLoss. Valid for STOP_LOSS_TAKE_PROFIT order.
     *     @type int $stopTriggerMethod
     *           Trigger method for the order. Valid only for STOP and STOP_LIMIT orders.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique ID of the order. Note: trader might have two orders with the same id if orders are taken from accounts from different brokers.
     *
     * Generated from protobuf field <code>int64 orderId = 1;</code>
     * @return int|string
     */
    public function getOrderId()
    {
        return $this->orderId;
    }

    /**
     * The unique ID of the order. Note: trader might have two orders with the same id if orders are taken from accounts from different brokers.
     *
     * Generated from protobuf field <code>int64 orderId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrderId($var)
    {
        GPBUtil::checkInt64($var);
        $this->orderId = $var;

        return $this;
    }

    /**
     * Detailed trader data.
     *
     * Generated from protobuf field <code>.ProtoOATradeData tradeData = 2;</code>
     * @return \SocialiteProviders\Ctrader\Protobuf\ProtoOATradeData
     */
    public function getTradeData()
    {
        return $this->tradeData;
    }

    /**
     * Detailed trader data.
     *
     * Generated from protobuf field <code>.ProtoOATradeData tradeData = 2;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOATradeData $var
     * @return $this
     */
    public function setTradeData($var)
    {
        GPBUtil::checkMessage($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOATradeData::class);
        $this->tradeData = $var;

        return $this;
    }

    /**
     * Order type.
     *
     * Generated from protobuf field <code>.ProtoOAOrderType orderType = 3;</code>
     * @return int
     */
    public function getOrderType()
    {
        return $this->orderType;
    }

    /**
     * Order type.
     *
     * Generated from protobuf field <code>.ProtoOAOrderType orderType = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrderType::class);
        $this->orderType = $var;

        return $this;
    }

    /**
     * Order status.
     *
     * Generated from protobuf field <code>.ProtoOAOrderStatus orderStatus = 4;</code>
     * @return int
     */
    public function getOrderStatus()
    {
        return $this->orderStatus;
    }

    /**
     * Order status.
     *
     * Generated from protobuf field <code>.ProtoOAOrderStatus orderStatus = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setOrderStatus($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrderStatus::class);
        $this->orderStatus = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds of expiration if the order has time in force GTD.
     *
     * Generated from protobuf field <code>int64 expirationTimestamp = 6;</code>
     * @return int|string
     */
    public function getExpirationTimestamp()
    {
        return $this->expirationTimestamp;
    }

    /**
     * The Unix time in milliseconds of expiration if the order has time in force GTD.
     *
     * Generated from protobuf field <code>int64 expirationTimestamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpirationTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->expirationTimestamp = $var;

        return $this;
    }

    /**
     * Price at which an order was executed. For order with FILLED status.
     *
     * Generated from protobuf field <code>double executionPrice = 7;</code>
     * @return float
     */
    public function getExecutionPrice()
    {
        return $this->executionPrice;
    }

    /**
     * Price at which an order was executed. For order with FILLED status.
     *
     * Generated from protobuf field <code>double executionPrice = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setExecutionPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->executionPrice = $var;

        return $this;
    }

    /**
     * Part of the volume that was filled in cents (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>int64 executedVolume = 8;</code>
     * @return int|string
     */
    public function getExecutedVolume()
    {
        return $this->executedVolume;
    }

    /**
     * Part of the volume that was filled in cents (e.g. 1000 in protocol means 10.00 units).
     *
     * Generated from protobuf field <code>int64 executedVolume = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExecutedVolume($var)
    {
        GPBUtil::checkInt64($var);
        $this->executedVolume = $var;

        return $this;
    }

    /**
     * The Unix time in milliseconds of the last update of the order.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 9;</code>
     * @return int|string
     */
    public function getUtcLastUpdateTimestamp()
    {
        return $this->utcLastUpdateTimestamp;
    }

    /**
     * The Unix time in milliseconds of the last update of the order.
     *
     * Generated from protobuf field <code>int64 utcLastUpdateTimestamp = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUtcLastUpdateTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->utcLastUpdateTimestamp = $var;

        return $this;
    }

    /**
     * Used for Market Range order with combination of slippageInPoints to specify price range were order can be executed.
     *
     * Generated from protobuf field <code>double baseSlippagePrice = 10;</code>
     * @return float
     */
    public function getBaseSlippagePrice()
    {
        return $this->baseSlippagePrice;
    }

    /**
     * Used for Market Range order with combination of slippageInPoints to specify price range were order can be executed.
     *
     * Generated from protobuf field <code>double baseSlippagePrice = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setBaseSlippagePrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->baseSlippagePrice = $var;

        return $this;
    }

    /**
     * Used for Market Range and STOP_LIMIT orders to to specify price range were order can be executed.
     *
     * Generated from protobuf field <code>int64 slippageInPoints = 11;</code>
     * @return int|string
     */
    public function getSlippageInPoints()
    {
        return $this->slippageInPoints;
    }

    /**
     * Used for Market Range and STOP_LIMIT orders to to specify price range were order can be executed.
     *
     * Generated from protobuf field <code>int64 slippageInPoints = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSlippageInPoints($var)
    {
        GPBUtil::checkInt64($var);
        $this->slippageInPoints = $var;

        return $this;
    }

    /**
     * If TRUE then the order is closing part of whole position. Must have specified positionId.
     *
     * Generated from protobuf field <code>bool closingOrder = 12;</code>
     * @return bool
     */
    public function getClosingOrder()
    {
        return $this->closingOrder;
    }

    /**
     * If TRUE then the order is closing part of whole position. Must have specified positionId.
     *
     * Generated from protobuf field <code>bool closingOrder = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setClosingOrder($var)
    {
        GPBUtil::checkBool($var);
        $this->closingOrder = $var;

        return $this;
    }

    /**
     * Valid only for LIMIT orders.
     *
     * Generated from protobuf field <code>double limitPrice = 13;</code>
     * @return float
     */
    public function getLimitPrice()
    {
        return $this->limitPrice;
    }

    /**
     * Valid only for LIMIT orders.
     *
     * Generated from protobuf field <code>double limitPrice = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setLimitPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->limitPrice = $var;

        return $this;
    }

    /**
     * Valid only for STOP and STOP_LIMIT orders.
     *
     * Generated from protobuf field <code>double stopPrice = 14;</code>
     * @return float
     */
    public function getStopPrice()
    {
        return $this->stopPrice;
    }

    /**
     * Valid only for STOP and STOP_LIMIT orders.
     *
     * Generated from protobuf field <code>double stopPrice = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setStopPrice($var)
    {
        GPBUtil::checkDouble($var);
        $this->stopPrice = $var;

        return $this;
    }

    /**
     * Absolute stopLoss price.
     *
     * Generated from protobuf field <code>double stopLoss = 15;</code>
     * @return float
     */
    public function getStopLoss()
    {
        return $this->stopLoss;
    }

    /**
     * Absolute stopLoss price.
     *
     * Generated from protobuf field <code>double stopLoss = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setStopLoss($var)
    {
        GPBUtil::checkDouble($var);
        $this->stopLoss = $var;

        return $this;
    }

    /**
     * Absolute takeProfit price.
     *
     * Generated from protobuf field <code>double takeProfit = 16;</code>
     * @return float
     */
    public function getTakeProfit()
    {
        return $this->takeProfit;
    }

    /**
     * Absolute takeProfit price.
     *
     * Generated from protobuf field <code>double takeProfit = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setTakeProfit($var)
    {
        GPBUtil::checkDouble($var);
        $this->takeProfit = $var;

        return $this;
    }

    /**
     * Optional ClientOrderId. Max Length = 50 chars.
     *
     * Generated from protobuf field <code>string clientOrderId = 17;</code>
     * @return string
     */
    public function getClientOrderId()
    {
        return $this->clientOrderId;
    }

    /**
     * Optional ClientOrderId. Max Length = 50 chars.
     *
     * Generated from protobuf field <code>string clientOrderId = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setClientOrderId($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientOrderId = $var;

        return $this;
    }

    /**
     * Order's time in force. Depends on order type.
     *
     * Generated from protobuf field <code>.ProtoOATimeInForce timeInForce = 18;</code>
     * @return int
     */
    public function getTimeInForce()
    {
        return $this->timeInForce;
    }

    /**
     * Order's time in force. Depends on order type.
     *
     * Generated from protobuf field <code>.ProtoOATimeInForce timeInForce = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeInForce($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOATimeInForce::class);
        $this->timeInForce = $var;

        return $this;
    }

    /**
     * ID of the position linked to the order (e.g. closing order, order that increase volume of a specific position, etc.).
     *
     * Generated from protobuf field <code>int64 positionId = 19;</code>
     * @return int|string
     */
    public function getPositionId()
    {
        return $this->positionId;
    }

    /**
     * ID of the position linked to the order (e.g. closing order, order that increase volume of a specific position, etc.).
     *
     * Generated from protobuf field <code>int64 positionId = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPositionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->positionId = $var;

        return $this;
    }

    /**
     * Relative stopLoss that can be specified instead of absolute as one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY stopLoss = entryPrice - relativeStopLoss, for SELL stopLoss = entryPrice + relativeStopLoss.
     *
     * Generated from protobuf field <code>int64 relativeStopLoss = 20;</code>
     * @return int|string
     */
    public function getRelativeStopLoss()
    {
        return $this->relativeStopLoss;
    }

    /**
     * Relative stopLoss that can be specified instead of absolute as one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) For BUY stopLoss = entryPrice - relativeStopLoss, for SELL stopLoss = entryPrice + relativeStopLoss.
     *
     * Generated from protobuf field <code>int64 relativeStopLoss = 20;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRelativeStopLoss($var)
    {
        GPBUtil::checkInt64($var);
        $this->relativeStopLoss = $var;

        return $this;
    }

    /**
     * Relative takeProfit that can be specified instead of absolute one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) ForBUY takeProfit = entryPrice + relativeTakeProfit, for SELL takeProfit = entryPrice - relativeTakeProfit.
     *
     * Generated from protobuf field <code>int64 relativeTakeProfit = 21;</code>
     * @return int|string
     */
    public function getRelativeTakeProfit()
    {
        return $this->relativeTakeProfit;
    }

    /**
     * Relative takeProfit that can be specified instead of absolute one. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782) ForBUY takeProfit = entryPrice + relativeTakeProfit, for SELL takeProfit = entryPrice - relativeTakeProfit.
     *
     * Generated from protobuf field <code>int64 relativeTakeProfit = 21;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRelativeTakeProfit($var)
    {
        GPBUtil::checkInt64($var);
        $this->relativeTakeProfit = $var;

        return $this;
    }

    /**
     * If TRUE then order was stopped out from server side.
     *
     * Generated from protobuf field <code>bool isStopOut = 22;</code>
     * @return bool
     */
    public function getIsStopOut()
    {
        return $this->isStopOut;
    }

    /**
     * If TRUE then order was stopped out from server side.
     *
     * Generated from protobuf field <code>bool isStopOut = 22;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsStopOut($var)
    {
        GPBUtil::checkBool($var);
        $this->isStopOut = $var;

        return $this;
    }

    /**
     * If TRUE then order is trailingStopLoss. Valid for STOP_LOSS_TAKE_PROFIT order.
     *
     * Generated from protobuf field <code>bool trailingStopLoss = 23;</code>
     * @return bool
     */
    public function getTrailingStopLoss()
    {
        return $this->trailingStopLoss;
    }

    /**
     * If TRUE then order is trailingStopLoss. Valid for STOP_LOSS_TAKE_PROFIT order.
     *
     * Generated from protobuf field <code>bool trailingStopLoss = 23;</code>
     * @param bool $var
     * @return $this
     */
    public function setTrailingStopLoss($var)
    {
        GPBUtil::checkBool($var);
        $this->trailingStopLoss = $var;

        return $this;
    }

    /**
     * Trigger method for the order. Valid only for STOP and STOP_LIMIT orders.
     *
     * Generated from protobuf field <code>.ProtoOAOrderTriggerMethod stopTriggerMethod = 24;</code>
     * @return int
     */
    public function getStopTriggerMethod()
    {
        return $this->stopTriggerMethod;
    }

    /**
     * Trigger method for the order. Valid only for STOP and STOP_LIMIT orders.
     *
     * Generated from protobuf field <code>.ProtoOAOrderTriggerMethod stopTriggerMethod = 24;</code>
     * @param int $var
     * @return $this
     */
    public function setStopTriggerMethod($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAOrderTriggerMethod::class);
        $this->stopTriggerMethod = $var;

        return $this;
    }

}

