<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Event that is sent when a new spot event is generated on the server side. Requires subscription on the spot events, see ProtoOASubscribeSpotsReq. First event, received after subscription will contain latest spot prices even if market is closed. 
 *
 * Generated from protobuf message <code>ProtoOASpotEvent</code>
 */
class ProtoOASpotEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * Unique identifier of the Symbol in cTrader platform.
     *
     * Generated from protobuf field <code>int64 symbolId = 3;</code>
     */
    protected $symbolId = 0;
    /**
     * Bid price. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782)
     *
     * Generated from protobuf field <code>uint64 bid = 4;</code>
     */
    protected $bid = 0;
    /**
     * Ask price. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782)
     *
     * Generated from protobuf field <code>uint64 ask = 5;</code>
     */
    protected $ask = 0;
    /**
     * Returns live trend bar. Requires subscription on the trend bars.
     *
     * Generated from protobuf field <code>repeated .ProtoOATrendbar trendbar = 6;</code>
     */
    private $trendbar;
    /**
     * Last session close. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782)
     *
     * Generated from protobuf field <code>uint64 sessionClose = 7;</code>
     */
    protected $sessionClose = 0;
    /**
     * The Unix time for spot.
     *
     * Generated from protobuf field <code>int64 timestamp = 8;</code>
     */
    protected $timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type int|string $ctidTraderAccountId
     *           Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *     @type int|string $symbolId
     *           Unique identifier of the Symbol in cTrader platform.
     *     @type int|string $bid
     *           Bid price. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782)
     *     @type int|string $ask
     *           Ask price. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782)
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOATrendbar[]|\Google\Protobuf\Internal\RepeatedField $trendbar
     *           Returns live trend bar. Requires subscription on the trend bars.
     *     @type int|string $sessionClose
     *           Last session close. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782)
     *     @type int|string $timestamp
     *           The Unix time for spot.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * Unique identifier of the trader's account. Used to match responses to trader's accounts.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * Unique identifier of the Symbol in cTrader platform.
     *
     * Generated from protobuf field <code>int64 symbolId = 3;</code>
     * @return int|string
     */
    public function getSymbolId()
    {
        return $this->symbolId;
    }

    /**
     * Unique identifier of the Symbol in cTrader platform.
     *
     * Generated from protobuf field <code>int64 symbolId = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSymbolId($var)
    {
        GPBUtil::checkInt64($var);
        $this->symbolId = $var;

        return $this;
    }

    /**
     * Bid price. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782)
     *
     * Generated from protobuf field <code>uint64 bid = 4;</code>
     * @return int|string
     */
    public function getBid()
    {
        return $this->bid;
    }

    /**
     * Bid price. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782)
     *
     * Generated from protobuf field <code>uint64 bid = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBid($var)
    {
        GPBUtil::checkUint64($var);
        $this->bid = $var;

        return $this;
    }

    /**
     * Ask price. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782)
     *
     * Generated from protobuf field <code>uint64 ask = 5;</code>
     * @return int|string
     */
    public function getAsk()
    {
        return $this->ask;
    }

    /**
     * Ask price. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782)
     *
     * Generated from protobuf field <code>uint64 ask = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAsk($var)
    {
        GPBUtil::checkUint64($var);
        $this->ask = $var;

        return $this;
    }

    /**
     * Returns live trend bar. Requires subscription on the trend bars.
     *
     * Generated from protobuf field <code>repeated .ProtoOATrendbar trendbar = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTrendbar()
    {
        return $this->trendbar;
    }

    /**
     * Returns live trend bar. Requires subscription on the trend bars.
     *
     * Generated from protobuf field <code>repeated .ProtoOATrendbar trendbar = 6;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOATrendbar[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTrendbar($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOATrendbar::class);
        $this->trendbar = $arr;

        return $this;
    }

    /**
     * Last session close. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782)
     *
     * Generated from protobuf field <code>uint64 sessionClose = 7;</code>
     * @return int|string
     */
    public function getSessionClose()
    {
        return $this->sessionClose;
    }

    /**
     * Last session close. Specified in 1/100000 of unit of a price. (e.g. 123000 in protocol means 1.23, 53423782 means 534.23782)
     *
     * Generated from protobuf field <code>uint64 sessionClose = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSessionClose($var)
    {
        GPBUtil::checkUint64($var);
        $this->sessionClose = $var;

        return $this;
    }

    /**
     * The Unix time for spot.
     *
     * Generated from protobuf field <code>int64 timestamp = 8;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * The Unix time for spot.
     *
     * Generated from protobuf field <code>int64 timestamp = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

}

