<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Trading symbol entity. 
 *
 * Generated from protobuf message <code>ProtoOASymbol</code>
 */
class ProtoOASymbol extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique identifier of the symbol in specific server environment within cTrader platform. Different servers have different IDs.
     *
     * Generated from protobuf field <code>int64 symbolId = 1;</code>
     */
    protected $symbolId = 0;
    /**
     * Number of price digits to be displayed.
     *
     * Generated from protobuf field <code>int32 digits = 2;</code>
     */
    protected $digits = 0;
    /**
     * Pip position on digits.
     *
     * Generated from protobuf field <code>int32 pipPosition = 3;</code>
     */
    protected $pipPosition = 0;
    /**
     * If TRUE then the short selling with the symbol is enabled.
     *
     * Generated from protobuf field <code>bool enableShortSelling = 4;</code>
     */
    protected $enableShortSelling = false;
    /**
     * If TRUE then setting of guaranteedStopLoss is available for limited risk accounts.
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 5;</code>
     */
    protected $guaranteedStopLoss = false;
    /**
     * Day of the week when SWAP charge amount will be tripled. Doesn't impact Rollover Commission.
     *
     * Generated from protobuf field <code>.ProtoOADayOfWeek swapRollover3Days = 6;</code>
     */
    protected $swapRollover3Days = 0;
    /**
     * SWAP charge for long positions.
     *
     * Generated from protobuf field <code>double swapLong = 7;</code>
     */
    protected $swapLong = 0.0;
    /**
     * SWAP charge for short positions.
     *
     * Generated from protobuf field <code>double swapShort = 8;</code>
     */
    protected $swapShort = 0.0;
    /**
     * Maximum allowed volume in cents for an order with a symbol.
     *
     * Generated from protobuf field <code>int64 maxVolume = 9;</code>
     */
    protected $maxVolume = 0;
    /**
     * Minimum allowed volume in cents for an order with a symbol.
     *
     * Generated from protobuf field <code>int64 minVolume = 10;</code>
     */
    protected $minVolume = 0;
    /**
     * Step of the volume in cents for an order.
     *
     * Generated from protobuf field <code>int64 stepVolume = 11;</code>
     */
    protected $stepVolume = 0;
    /**
     * Value of max exposure per symbol, per account. Blocks execution if breached.
     *
     * Generated from protobuf field <code>uint64 maxExposure = 12;</code>
     */
    protected $maxExposure = 0;
    /**
     * Symbol trading interval, specified in seconds starting from SUNDAY 00:00 in specified time zone.
     *
     * Generated from protobuf field <code>repeated .ProtoOAInterval schedule = 13;</code>
     */
    private $schedule;
    /**
     * Commission base amount. Total commission depends on commissionType. Use preciseTradingCommissionRate.
     *
     * Generated from protobuf field <code>int64 commission = 14;</code>
     */
    protected $commission = 0;
    /**
     * Commission type. See ProtoOACommissionType for details.
     *
     * Generated from protobuf field <code>.ProtoOACommissionType commissionType = 15;</code>
     */
    protected $commissionType = 0;
    /**
     * Minimum allowed distance between stop loss and current market price.
     *
     * Generated from protobuf field <code>uint32 slDistance = 16;</code>
     */
    protected $slDistance = 0;
    /**
     * Minimum allowed distance between take profit and current market price.
     *
     * Generated from protobuf field <code>uint32 tpDistance = 17;</code>
     */
    protected $tpDistance = 0;
    /**
     * Minimum allowed distance between guaranteed stop loss and current market price.
     *
     * Generated from protobuf field <code>uint32 gslDistance = 18;</code>
     */
    protected $gslDistance = 0;
    /**
     * Guaranteed stop loss fee.
     *
     * Generated from protobuf field <code>int64 gslCharge = 19;</code>
     */
    protected $gslCharge = 0;
    /**
     * Unit of distance measure for slDistance, tpDistance, gslDistance.
     *
     * Generated from protobuf field <code>.ProtoOASymbolDistanceType distanceSetIn = 20;</code>
     */
    protected $distanceSetIn = 0;
    /**
     * Minimum commission amount per trade. Use preciseMinCommission.
     *
     * Generated from protobuf field <code>int64 minCommission = 21;</code>
     */
    protected $minCommission = 0;
    /**
     * Minimum commission Type. See ProtoOAMinCommissionType for details.
     *
     * Generated from protobuf field <code>.ProtoOAMinCommissionType minCommissionType = 22;</code>
     */
    protected $minCommissionType = 0;
    /**
     * Currency for minimum commission. (USD or quote currency).
     *
     * Generated from protobuf field <code>string minCommissionAsset = 23;</code>
     */
    protected $minCommissionAsset = '';
    /**
     * Administrative Fee, charged instead of Swaps if the Account is marked as a "Shariah Compliant (Swap Free)". The Administrative Fee is charged daily as USD per current open volume of Position in lots. The Account charged in the Deposit currency.
     *
     * Generated from protobuf field <code>int64 rolloverCommission = 24;</code>
     */
    protected $rolloverCommission = 0;
    /**
     * Initial period before the first rolloverCommission will be charged on the account.
     *
     * Generated from protobuf field <code>int32 skipRolloverDays = 25;</code>
     */
    protected $skipRolloverDays = 0;
    /**
     * Time zone for the symbol trading intervals.
     *
     * Generated from protobuf field <code>string scheduleTimeZone = 26;</code>
     */
    protected $scheduleTimeZone = '';
    /**
     * Rules for trading with the symbol. See ProtoOATradingMode for details.
     *
     * Generated from protobuf field <code>.ProtoOATradingMode tradingMode = 27;</code>
     */
    protected $tradingMode = 0;
    /**
     * Day of the week (in UTC) when Administrative Fee charge amount will be tripled. Applied only if RolloverChargePeriod = 0 or 1.
     *
     * Generated from protobuf field <code>.ProtoOADayOfWeek rolloverCommission3Days = 28;</code>
     */
    protected $rolloverCommission3Days = 0;
    /**
     * Specifies type of SWAP computation as PIPS (0) or PERCENTAGE (1, annual, in percent).
     *
     * Generated from protobuf field <code>.ProtoOASwapCalculationType swapCalculationType = 29;</code>
     */
    protected $swapCalculationType = 0;
    /**
     * Lot size of the Symbol (in cents).
     *
     * Generated from protobuf field <code>int64 lotSize = 30;</code>
     */
    protected $lotSize = 0;
    /**
     * Commission base amount. Total commission depends on commissionType: for non-percentage types it is multiplied by 10^8, for percentage of value commission type it is multiplied by 10^5.
     *
     * Generated from protobuf field <code>int64 preciseTradingCommissionRate = 31;</code>
     */
    protected $preciseTradingCommissionRate = 0;
    /**
     * Minimum commission amount per trade multiplied by 10^8.
     *
     * Generated from protobuf field <code>int64 preciseMinCommission = 32;</code>
     */
    protected $preciseMinCommission = 0;
    /**
     * List of holidays for this symbol specified by broker.
     *
     * Generated from protobuf field <code>repeated .ProtoOAHoliday holiday = 33;</code>
     */
    private $holiday;
    /**
     * Percentage (1 = 0.01%) of the realized Gross Profit, which will be paid by the Trader for any trade if the Quote Asset of the traded Symbol is not matched with the Deposit Asset.
     *
     * Generated from protobuf field <code>int32 pnlConversionFeeRate = 34;</code>
     */
    protected $pnlConversionFeeRate = 0;
    /**
     * The unique identifier of dynamic leverage entity. https://help.ctrader.com/ctrader/trading/dynamic-leverage
     *
     * Generated from protobuf field <code>int64 leverageId = 35;</code>
     */
    protected $leverageId = 0;
    /**
     * Period of charging swaps in hours. 24 means swaps will be charged 1 time per day, 12 - every 12 hours, 8 - every 8 hours, etc.
     *
     * Generated from protobuf field <code>int32 swapPeriod = 36;</code>
     */
    protected $swapPeriod = 0;
    /**
     * Time in minutes from 00:00 (UTC) when intraday swaps are charged for the first time.
     *
     * Generated from protobuf field <code>int32 swapTime = 37;</code>
     */
    protected $swapTime = 0;
    /**
     * Count of swapPeriods before the first SWAP charge.
     *
     * Generated from protobuf field <code>int32 skipSWAPPeriods = 38;</code>
     */
    protected $skipSWAPPeriods = 0;
    /**
     * If enabled, SWAP will be charged for all days of the week, including Saturday and Sunday.
     *
     * Generated from protobuf field <code>bool chargeSwapAtWeekends = 39;</code>
     */
    protected $chargeSwapAtWeekends = false;
    /**
     * Specifies the units in which the base Asset of the Symbol is denominated.
     *
     * Generated from protobuf field <code>string measurementUnits = 40;</code>
     */
    protected $measurementUnits = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $symbolId
     *           The unique identifier of the symbol in specific server environment within cTrader platform. Different servers have different IDs.
     *     @type int $digits
     *           Number of price digits to be displayed.
     *     @type int $pipPosition
     *           Pip position on digits.
     *     @type bool $enableShortSelling
     *           If TRUE then the short selling with the symbol is enabled.
     *     @type bool $guaranteedStopLoss
     *           If TRUE then setting of guaranteedStopLoss is available for limited risk accounts.
     *     @type int $swapRollover3Days
     *           Day of the week when SWAP charge amount will be tripled. Doesn't impact Rollover Commission.
     *     @type float $swapLong
     *           SWAP charge for long positions.
     *     @type float $swapShort
     *           SWAP charge for short positions.
     *     @type int|string $maxVolume
     *           Maximum allowed volume in cents for an order with a symbol.
     *     @type int|string $minVolume
     *           Minimum allowed volume in cents for an order with a symbol.
     *     @type int|string $stepVolume
     *           Step of the volume in cents for an order.
     *     @type int|string $maxExposure
     *           Value of max exposure per symbol, per account. Blocks execution if breached.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOAInterval[]|\Google\Protobuf\Internal\RepeatedField $schedule
     *           Symbol trading interval, specified in seconds starting from SUNDAY 00:00 in specified time zone.
     *     @type int|string $commission
     *           Commission base amount. Total commission depends on commissionType. Use preciseTradingCommissionRate.
     *     @type int $commissionType
     *           Commission type. See ProtoOACommissionType for details.
     *     @type int $slDistance
     *           Minimum allowed distance between stop loss and current market price.
     *     @type int $tpDistance
     *           Minimum allowed distance between take profit and current market price.
     *     @type int $gslDistance
     *           Minimum allowed distance between guaranteed stop loss and current market price.
     *     @type int|string $gslCharge
     *           Guaranteed stop loss fee.
     *     @type int $distanceSetIn
     *           Unit of distance measure for slDistance, tpDistance, gslDistance.
     *     @type int|string $minCommission
     *           Minimum commission amount per trade. Use preciseMinCommission.
     *     @type int $minCommissionType
     *           Minimum commission Type. See ProtoOAMinCommissionType for details.
     *     @type string $minCommissionAsset
     *           Currency for minimum commission. (USD or quote currency).
     *     @type int|string $rolloverCommission
     *           Administrative Fee, charged instead of Swaps if the Account is marked as a "Shariah Compliant (Swap Free)". The Administrative Fee is charged daily as USD per current open volume of Position in lots. The Account charged in the Deposit currency.
     *     @type int $skipRolloverDays
     *           Initial period before the first rolloverCommission will be charged on the account.
     *     @type string $scheduleTimeZone
     *           Time zone for the symbol trading intervals.
     *     @type int $tradingMode
     *           Rules for trading with the symbol. See ProtoOATradingMode for details.
     *     @type int $rolloverCommission3Days
     *           Day of the week (in UTC) when Administrative Fee charge amount will be tripled. Applied only if RolloverChargePeriod = 0 or 1.
     *     @type int $swapCalculationType
     *           Specifies type of SWAP computation as PIPS (0) or PERCENTAGE (1, annual, in percent).
     *     @type int|string $lotSize
     *           Lot size of the Symbol (in cents).
     *     @type int|string $preciseTradingCommissionRate
     *           Commission base amount. Total commission depends on commissionType: for non-percentage types it is multiplied by 10^8, for percentage of value commission type it is multiplied by 10^5.
     *     @type int|string $preciseMinCommission
     *           Minimum commission amount per trade multiplied by 10^8.
     *     @type \SocialiteProviders\Ctrader\Protobuf\ProtoOAHoliday[]|\Google\Protobuf\Internal\RepeatedField $holiday
     *           List of holidays for this symbol specified by broker.
     *     @type int $pnlConversionFeeRate
     *           Percentage (1 = 0.01%) of the realized Gross Profit, which will be paid by the Trader for any trade if the Quote Asset of the traded Symbol is not matched with the Deposit Asset.
     *     @type int|string $leverageId
     *           The unique identifier of dynamic leverage entity. https://help.ctrader.com/ctrader/trading/dynamic-leverage
     *     @type int $swapPeriod
     *           Period of charging swaps in hours. 24 means swaps will be charged 1 time per day, 12 - every 12 hours, 8 - every 8 hours, etc.
     *     @type int $swapTime
     *           Time in minutes from 00:00 (UTC) when intraday swaps are charged for the first time.
     *     @type int $skipSWAPPeriods
     *           Count of swapPeriods before the first SWAP charge.
     *     @type bool $chargeSwapAtWeekends
     *           If enabled, SWAP will be charged for all days of the week, including Saturday and Sunday.
     *     @type string $measurementUnits
     *           Specifies the units in which the base Asset of the Symbol is denominated.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique identifier of the symbol in specific server environment within cTrader platform. Different servers have different IDs.
     *
     * Generated from protobuf field <code>int64 symbolId = 1;</code>
     * @return int|string
     */
    public function getSymbolId()
    {
        return $this->symbolId;
    }

    /**
     * The unique identifier of the symbol in specific server environment within cTrader platform. Different servers have different IDs.
     *
     * Generated from protobuf field <code>int64 symbolId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSymbolId($var)
    {
        GPBUtil::checkInt64($var);
        $this->symbolId = $var;

        return $this;
    }

    /**
     * Number of price digits to be displayed.
     *
     * Generated from protobuf field <code>int32 digits = 2;</code>
     * @return int
     */
    public function getDigits()
    {
        return $this->digits;
    }

    /**
     * Number of price digits to be displayed.
     *
     * Generated from protobuf field <code>int32 digits = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDigits($var)
    {
        GPBUtil::checkInt32($var);
        $this->digits = $var;

        return $this;
    }

    /**
     * Pip position on digits.
     *
     * Generated from protobuf field <code>int32 pipPosition = 3;</code>
     * @return int
     */
    public function getPipPosition()
    {
        return $this->pipPosition;
    }

    /**
     * Pip position on digits.
     *
     * Generated from protobuf field <code>int32 pipPosition = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPipPosition($var)
    {
        GPBUtil::checkInt32($var);
        $this->pipPosition = $var;

        return $this;
    }

    /**
     * If TRUE then the short selling with the symbol is enabled.
     *
     * Generated from protobuf field <code>bool enableShortSelling = 4;</code>
     * @return bool
     */
    public function getEnableShortSelling()
    {
        return $this->enableShortSelling;
    }

    /**
     * If TRUE then the short selling with the symbol is enabled.
     *
     * Generated from protobuf field <code>bool enableShortSelling = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableShortSelling($var)
    {
        GPBUtil::checkBool($var);
        $this->enableShortSelling = $var;

        return $this;
    }

    /**
     * If TRUE then setting of guaranteedStopLoss is available for limited risk accounts.
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 5;</code>
     * @return bool
     */
    public function getGuaranteedStopLoss()
    {
        return $this->guaranteedStopLoss;
    }

    /**
     * If TRUE then setting of guaranteedStopLoss is available for limited risk accounts.
     *
     * Generated from protobuf field <code>bool guaranteedStopLoss = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setGuaranteedStopLoss($var)
    {
        GPBUtil::checkBool($var);
        $this->guaranteedStopLoss = $var;

        return $this;
    }

    /**
     * Day of the week when SWAP charge amount will be tripled. Doesn't impact Rollover Commission.
     *
     * Generated from protobuf field <code>.ProtoOADayOfWeek swapRollover3Days = 6;</code>
     * @return int
     */
    public function getSwapRollover3Days()
    {
        return $this->swapRollover3Days;
    }

    /**
     * Day of the week when SWAP charge amount will be tripled. Doesn't impact Rollover Commission.
     *
     * Generated from protobuf field <code>.ProtoOADayOfWeek swapRollover3Days = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSwapRollover3Days($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOADayOfWeek::class);
        $this->swapRollover3Days = $var;

        return $this;
    }

    /**
     * SWAP charge for long positions.
     *
     * Generated from protobuf field <code>double swapLong = 7;</code>
     * @return float
     */
    public function getSwapLong()
    {
        return $this->swapLong;
    }

    /**
     * SWAP charge for long positions.
     *
     * Generated from protobuf field <code>double swapLong = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setSwapLong($var)
    {
        GPBUtil::checkDouble($var);
        $this->swapLong = $var;

        return $this;
    }

    /**
     * SWAP charge for short positions.
     *
     * Generated from protobuf field <code>double swapShort = 8;</code>
     * @return float
     */
    public function getSwapShort()
    {
        return $this->swapShort;
    }

    /**
     * SWAP charge for short positions.
     *
     * Generated from protobuf field <code>double swapShort = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setSwapShort($var)
    {
        GPBUtil::checkDouble($var);
        $this->swapShort = $var;

        return $this;
    }

    /**
     * Maximum allowed volume in cents for an order with a symbol.
     *
     * Generated from protobuf field <code>int64 maxVolume = 9;</code>
     * @return int|string
     */
    public function getMaxVolume()
    {
        return $this->maxVolume;
    }

    /**
     * Maximum allowed volume in cents for an order with a symbol.
     *
     * Generated from protobuf field <code>int64 maxVolume = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxVolume($var)
    {
        GPBUtil::checkInt64($var);
        $this->maxVolume = $var;

        return $this;
    }

    /**
     * Minimum allowed volume in cents for an order with a symbol.
     *
     * Generated from protobuf field <code>int64 minVolume = 10;</code>
     * @return int|string
     */
    public function getMinVolume()
    {
        return $this->minVolume;
    }

    /**
     * Minimum allowed volume in cents for an order with a symbol.
     *
     * Generated from protobuf field <code>int64 minVolume = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinVolume($var)
    {
        GPBUtil::checkInt64($var);
        $this->minVolume = $var;

        return $this;
    }

    /**
     * Step of the volume in cents for an order.
     *
     * Generated from protobuf field <code>int64 stepVolume = 11;</code>
     * @return int|string
     */
    public function getStepVolume()
    {
        return $this->stepVolume;
    }

    /**
     * Step of the volume in cents for an order.
     *
     * Generated from protobuf field <code>int64 stepVolume = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStepVolume($var)
    {
        GPBUtil::checkInt64($var);
        $this->stepVolume = $var;

        return $this;
    }

    /**
     * Value of max exposure per symbol, per account. Blocks execution if breached.
     *
     * Generated from protobuf field <code>uint64 maxExposure = 12;</code>
     * @return int|string
     */
    public function getMaxExposure()
    {
        return $this->maxExposure;
    }

    /**
     * Value of max exposure per symbol, per account. Blocks execution if breached.
     *
     * Generated from protobuf field <code>uint64 maxExposure = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxExposure($var)
    {
        GPBUtil::checkUint64($var);
        $this->maxExposure = $var;

        return $this;
    }

    /**
     * Symbol trading interval, specified in seconds starting from SUNDAY 00:00 in specified time zone.
     *
     * Generated from protobuf field <code>repeated .ProtoOAInterval schedule = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSchedule()
    {
        return $this->schedule;
    }

    /**
     * Symbol trading interval, specified in seconds starting from SUNDAY 00:00 in specified time zone.
     *
     * Generated from protobuf field <code>repeated .ProtoOAInterval schedule = 13;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOAInterval[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSchedule($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOAInterval::class);
        $this->schedule = $arr;

        return $this;
    }

    /**
     * Commission base amount. Total commission depends on commissionType. Use preciseTradingCommissionRate.
     *
     * Generated from protobuf field <code>int64 commission = 14;</code>
     * @return int|string
     */
    public function getCommission()
    {
        return $this->commission;
    }

    /**
     * Commission base amount. Total commission depends on commissionType. Use preciseTradingCommissionRate.
     *
     * Generated from protobuf field <code>int64 commission = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCommission($var)
    {
        GPBUtil::checkInt64($var);
        $this->commission = $var;

        return $this;
    }

    /**
     * Commission type. See ProtoOACommissionType for details.
     *
     * Generated from protobuf field <code>.ProtoOACommissionType commissionType = 15;</code>
     * @return int
     */
    public function getCommissionType()
    {
        return $this->commissionType;
    }

    /**
     * Commission type. See ProtoOACommissionType for details.
     *
     * Generated from protobuf field <code>.ProtoOACommissionType commissionType = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setCommissionType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOACommissionType::class);
        $this->commissionType = $var;

        return $this;
    }

    /**
     * Minimum allowed distance between stop loss and current market price.
     *
     * Generated from protobuf field <code>uint32 slDistance = 16;</code>
     * @return int
     */
    public function getSlDistance()
    {
        return $this->slDistance;
    }

    /**
     * Minimum allowed distance between stop loss and current market price.
     *
     * Generated from protobuf field <code>uint32 slDistance = 16;</code>
     * @param int $var
     * @return $this
     */
    public function setSlDistance($var)
    {
        GPBUtil::checkUint32($var);
        $this->slDistance = $var;

        return $this;
    }

    /**
     * Minimum allowed distance between take profit and current market price.
     *
     * Generated from protobuf field <code>uint32 tpDistance = 17;</code>
     * @return int
     */
    public function getTpDistance()
    {
        return $this->tpDistance;
    }

    /**
     * Minimum allowed distance between take profit and current market price.
     *
     * Generated from protobuf field <code>uint32 tpDistance = 17;</code>
     * @param int $var
     * @return $this
     */
    public function setTpDistance($var)
    {
        GPBUtil::checkUint32($var);
        $this->tpDistance = $var;

        return $this;
    }

    /**
     * Minimum allowed distance between guaranteed stop loss and current market price.
     *
     * Generated from protobuf field <code>uint32 gslDistance = 18;</code>
     * @return int
     */
    public function getGslDistance()
    {
        return $this->gslDistance;
    }

    /**
     * Minimum allowed distance between guaranteed stop loss and current market price.
     *
     * Generated from protobuf field <code>uint32 gslDistance = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setGslDistance($var)
    {
        GPBUtil::checkUint32($var);
        $this->gslDistance = $var;

        return $this;
    }

    /**
     * Guaranteed stop loss fee.
     *
     * Generated from protobuf field <code>int64 gslCharge = 19;</code>
     * @return int|string
     */
    public function getGslCharge()
    {
        return $this->gslCharge;
    }

    /**
     * Guaranteed stop loss fee.
     *
     * Generated from protobuf field <code>int64 gslCharge = 19;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGslCharge($var)
    {
        GPBUtil::checkInt64($var);
        $this->gslCharge = $var;

        return $this;
    }

    /**
     * Unit of distance measure for slDistance, tpDistance, gslDistance.
     *
     * Generated from protobuf field <code>.ProtoOASymbolDistanceType distanceSetIn = 20;</code>
     * @return int
     */
    public function getDistanceSetIn()
    {
        return $this->distanceSetIn;
    }

    /**
     * Unit of distance measure for slDistance, tpDistance, gslDistance.
     *
     * Generated from protobuf field <code>.ProtoOASymbolDistanceType distanceSetIn = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setDistanceSetIn($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOASymbolDistanceType::class);
        $this->distanceSetIn = $var;

        return $this;
    }

    /**
     * Minimum commission amount per trade. Use preciseMinCommission.
     *
     * Generated from protobuf field <code>int64 minCommission = 21;</code>
     * @return int|string
     */
    public function getMinCommission()
    {
        return $this->minCommission;
    }

    /**
     * Minimum commission amount per trade. Use preciseMinCommission.
     *
     * Generated from protobuf field <code>int64 minCommission = 21;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMinCommission($var)
    {
        GPBUtil::checkInt64($var);
        $this->minCommission = $var;

        return $this;
    }

    /**
     * Minimum commission Type. See ProtoOAMinCommissionType for details.
     *
     * Generated from protobuf field <code>.ProtoOAMinCommissionType minCommissionType = 22;</code>
     * @return int
     */
    public function getMinCommissionType()
    {
        return $this->minCommissionType;
    }

    /**
     * Minimum commission Type. See ProtoOAMinCommissionType for details.
     *
     * Generated from protobuf field <code>.ProtoOAMinCommissionType minCommissionType = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setMinCommissionType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAMinCommissionType::class);
        $this->minCommissionType = $var;

        return $this;
    }

    /**
     * Currency for minimum commission. (USD or quote currency).
     *
     * Generated from protobuf field <code>string minCommissionAsset = 23;</code>
     * @return string
     */
    public function getMinCommissionAsset()
    {
        return $this->minCommissionAsset;
    }

    /**
     * Currency for minimum commission. (USD or quote currency).
     *
     * Generated from protobuf field <code>string minCommissionAsset = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setMinCommissionAsset($var)
    {
        GPBUtil::checkString($var, True);
        $this->minCommissionAsset = $var;

        return $this;
    }

    /**
     * Administrative Fee, charged instead of Swaps if the Account is marked as a "Shariah Compliant (Swap Free)". The Administrative Fee is charged daily as USD per current open volume of Position in lots. The Account charged in the Deposit currency.
     *
     * Generated from protobuf field <code>int64 rolloverCommission = 24;</code>
     * @return int|string
     */
    public function getRolloverCommission()
    {
        return $this->rolloverCommission;
    }

    /**
     * Administrative Fee, charged instead of Swaps if the Account is marked as a "Shariah Compliant (Swap Free)". The Administrative Fee is charged daily as USD per current open volume of Position in lots. The Account charged in the Deposit currency.
     *
     * Generated from protobuf field <code>int64 rolloverCommission = 24;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRolloverCommission($var)
    {
        GPBUtil::checkInt64($var);
        $this->rolloverCommission = $var;

        return $this;
    }

    /**
     * Initial period before the first rolloverCommission will be charged on the account.
     *
     * Generated from protobuf field <code>int32 skipRolloverDays = 25;</code>
     * @return int
     */
    public function getSkipRolloverDays()
    {
        return $this->skipRolloverDays;
    }

    /**
     * Initial period before the first rolloverCommission will be charged on the account.
     *
     * Generated from protobuf field <code>int32 skipRolloverDays = 25;</code>
     * @param int $var
     * @return $this
     */
    public function setSkipRolloverDays($var)
    {
        GPBUtil::checkInt32($var);
        $this->skipRolloverDays = $var;

        return $this;
    }

    /**
     * Time zone for the symbol trading intervals.
     *
     * Generated from protobuf field <code>string scheduleTimeZone = 26;</code>
     * @return string
     */
    public function getScheduleTimeZone()
    {
        return $this->scheduleTimeZone;
    }

    /**
     * Time zone for the symbol trading intervals.
     *
     * Generated from protobuf field <code>string scheduleTimeZone = 26;</code>
     * @param string $var
     * @return $this
     */
    public function setScheduleTimeZone($var)
    {
        GPBUtil::checkString($var, True);
        $this->scheduleTimeZone = $var;

        return $this;
    }

    /**
     * Rules for trading with the symbol. See ProtoOATradingMode for details.
     *
     * Generated from protobuf field <code>.ProtoOATradingMode tradingMode = 27;</code>
     * @return int
     */
    public function getTradingMode()
    {
        return $this->tradingMode;
    }

    /**
     * Rules for trading with the symbol. See ProtoOATradingMode for details.
     *
     * Generated from protobuf field <code>.ProtoOATradingMode tradingMode = 27;</code>
     * @param int $var
     * @return $this
     */
    public function setTradingMode($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOATradingMode::class);
        $this->tradingMode = $var;

        return $this;
    }

    /**
     * Day of the week (in UTC) when Administrative Fee charge amount will be tripled. Applied only if RolloverChargePeriod = 0 or 1.
     *
     * Generated from protobuf field <code>.ProtoOADayOfWeek rolloverCommission3Days = 28;</code>
     * @return int
     */
    public function getRolloverCommission3Days()
    {
        return $this->rolloverCommission3Days;
    }

    /**
     * Day of the week (in UTC) when Administrative Fee charge amount will be tripled. Applied only if RolloverChargePeriod = 0 or 1.
     *
     * Generated from protobuf field <code>.ProtoOADayOfWeek rolloverCommission3Days = 28;</code>
     * @param int $var
     * @return $this
     */
    public function setRolloverCommission3Days($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOADayOfWeek::class);
        $this->rolloverCommission3Days = $var;

        return $this;
    }

    /**
     * Specifies type of SWAP computation as PIPS (0) or PERCENTAGE (1, annual, in percent).
     *
     * Generated from protobuf field <code>.ProtoOASwapCalculationType swapCalculationType = 29;</code>
     * @return int
     */
    public function getSwapCalculationType()
    {
        return $this->swapCalculationType;
    }

    /**
     * Specifies type of SWAP computation as PIPS (0) or PERCENTAGE (1, annual, in percent).
     *
     * Generated from protobuf field <code>.ProtoOASwapCalculationType swapCalculationType = 29;</code>
     * @param int $var
     * @return $this
     */
    public function setSwapCalculationType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOASwapCalculationType::class);
        $this->swapCalculationType = $var;

        return $this;
    }

    /**
     * Lot size of the Symbol (in cents).
     *
     * Generated from protobuf field <code>int64 lotSize = 30;</code>
     * @return int|string
     */
    public function getLotSize()
    {
        return $this->lotSize;
    }

    /**
     * Lot size of the Symbol (in cents).
     *
     * Generated from protobuf field <code>int64 lotSize = 30;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLotSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->lotSize = $var;

        return $this;
    }

    /**
     * Commission base amount. Total commission depends on commissionType: for non-percentage types it is multiplied by 10^8, for percentage of value commission type it is multiplied by 10^5.
     *
     * Generated from protobuf field <code>int64 preciseTradingCommissionRate = 31;</code>
     * @return int|string
     */
    public function getPreciseTradingCommissionRate()
    {
        return $this->preciseTradingCommissionRate;
    }

    /**
     * Commission base amount. Total commission depends on commissionType: for non-percentage types it is multiplied by 10^8, for percentage of value commission type it is multiplied by 10^5.
     *
     * Generated from protobuf field <code>int64 preciseTradingCommissionRate = 31;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPreciseTradingCommissionRate($var)
    {
        GPBUtil::checkInt64($var);
        $this->preciseTradingCommissionRate = $var;

        return $this;
    }

    /**
     * Minimum commission amount per trade multiplied by 10^8.
     *
     * Generated from protobuf field <code>int64 preciseMinCommission = 32;</code>
     * @return int|string
     */
    public function getPreciseMinCommission()
    {
        return $this->preciseMinCommission;
    }

    /**
     * Minimum commission amount per trade multiplied by 10^8.
     *
     * Generated from protobuf field <code>int64 preciseMinCommission = 32;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPreciseMinCommission($var)
    {
        GPBUtil::checkInt64($var);
        $this->preciseMinCommission = $var;

        return $this;
    }

    /**
     * List of holidays for this symbol specified by broker.
     *
     * Generated from protobuf field <code>repeated .ProtoOAHoliday holiday = 33;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHoliday()
    {
        return $this->holiday;
    }

    /**
     * List of holidays for this symbol specified by broker.
     *
     * Generated from protobuf field <code>repeated .ProtoOAHoliday holiday = 33;</code>
     * @param \SocialiteProviders\Ctrader\Protobuf\ProtoOAHoliday[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHoliday($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SocialiteProviders\Ctrader\Protobuf\ProtoOAHoliday::class);
        $this->holiday = $arr;

        return $this;
    }

    /**
     * Percentage (1 = 0.01%) of the realized Gross Profit, which will be paid by the Trader for any trade if the Quote Asset of the traded Symbol is not matched with the Deposit Asset.
     *
     * Generated from protobuf field <code>int32 pnlConversionFeeRate = 34;</code>
     * @return int
     */
    public function getPnlConversionFeeRate()
    {
        return $this->pnlConversionFeeRate;
    }

    /**
     * Percentage (1 = 0.01%) of the realized Gross Profit, which will be paid by the Trader for any trade if the Quote Asset of the traded Symbol is not matched with the Deposit Asset.
     *
     * Generated from protobuf field <code>int32 pnlConversionFeeRate = 34;</code>
     * @param int $var
     * @return $this
     */
    public function setPnlConversionFeeRate($var)
    {
        GPBUtil::checkInt32($var);
        $this->pnlConversionFeeRate = $var;

        return $this;
    }

    /**
     * The unique identifier of dynamic leverage entity. https://help.ctrader.com/ctrader/trading/dynamic-leverage
     *
     * Generated from protobuf field <code>int64 leverageId = 35;</code>
     * @return int|string
     */
    public function getLeverageId()
    {
        return $this->leverageId;
    }

    /**
     * The unique identifier of dynamic leverage entity. https://help.ctrader.com/ctrader/trading/dynamic-leverage
     *
     * Generated from protobuf field <code>int64 leverageId = 35;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLeverageId($var)
    {
        GPBUtil::checkInt64($var);
        $this->leverageId = $var;

        return $this;
    }

    /**
     * Period of charging swaps in hours. 24 means swaps will be charged 1 time per day, 12 - every 12 hours, 8 - every 8 hours, etc.
     *
     * Generated from protobuf field <code>int32 swapPeriod = 36;</code>
     * @return int
     */
    public function getSwapPeriod()
    {
        return $this->swapPeriod;
    }

    /**
     * Period of charging swaps in hours. 24 means swaps will be charged 1 time per day, 12 - every 12 hours, 8 - every 8 hours, etc.
     *
     * Generated from protobuf field <code>int32 swapPeriod = 36;</code>
     * @param int $var
     * @return $this
     */
    public function setSwapPeriod($var)
    {
        GPBUtil::checkInt32($var);
        $this->swapPeriod = $var;

        return $this;
    }

    /**
     * Time in minutes from 00:00 (UTC) when intraday swaps are charged for the first time.
     *
     * Generated from protobuf field <code>int32 swapTime = 37;</code>
     * @return int
     */
    public function getSwapTime()
    {
        return $this->swapTime;
    }

    /**
     * Time in minutes from 00:00 (UTC) when intraday swaps are charged for the first time.
     *
     * Generated from protobuf field <code>int32 swapTime = 37;</code>
     * @param int $var
     * @return $this
     */
    public function setSwapTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->swapTime = $var;

        return $this;
    }

    /**
     * Count of swapPeriods before the first SWAP charge.
     *
     * Generated from protobuf field <code>int32 skipSWAPPeriods = 38;</code>
     * @return int
     */
    public function getSkipSWAPPeriods()
    {
        return $this->skipSWAPPeriods;
    }

    /**
     * Count of swapPeriods before the first SWAP charge.
     *
     * Generated from protobuf field <code>int32 skipSWAPPeriods = 38;</code>
     * @param int $var
     * @return $this
     */
    public function setSkipSWAPPeriods($var)
    {
        GPBUtil::checkInt32($var);
        $this->skipSWAPPeriods = $var;

        return $this;
    }

    /**
     * If enabled, SWAP will be charged for all days of the week, including Saturday and Sunday.
     *
     * Generated from protobuf field <code>bool chargeSwapAtWeekends = 39;</code>
     * @return bool
     */
    public function getChargeSwapAtWeekends()
    {
        return $this->chargeSwapAtWeekends;
    }

    /**
     * If enabled, SWAP will be charged for all days of the week, including Saturday and Sunday.
     *
     * Generated from protobuf field <code>bool chargeSwapAtWeekends = 39;</code>
     * @param bool $var
     * @return $this
     */
    public function setChargeSwapAtWeekends($var)
    {
        GPBUtil::checkBool($var);
        $this->chargeSwapAtWeekends = $var;

        return $this;
    }

    /**
     * Specifies the units in which the base Asset of the Symbol is denominated.
     *
     * Generated from protobuf field <code>string measurementUnits = 40;</code>
     * @return string
     */
    public function getMeasurementUnits()
    {
        return $this->measurementUnits;
    }

    /**
     * Specifies the units in which the base Asset of the Symbol is denominated.
     *
     * Generated from protobuf field <code>string measurementUnits = 40;</code>
     * @param string $var
     * @return $this
     */
    public function setMeasurementUnits($var)
    {
        GPBUtil::checkString($var, True);
        $this->measurementUnits = $var;

        return $this;
    }

}

