<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Price quote type. 
 *
 * Protobuf type <code>ProtoOAQuoteType</code>
 */
class ProtoOAQuoteType
{
    /**
     * Generated from protobuf enum <code>QUOTE_TYPE_UNKNOWN = 0;</code>
     */
    const QUOTE_TYPE_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>BID = 1;</code>
     */
    const BID = 1;
    /**
     * Generated from protobuf enum <code>ASK = 2;</code>
     */
    const ASK = 2;

    private static $valueToName = [
        self::QUOTE_TYPE_UNKNOWN => 'QUOTE_TYPE_UNKNOWN',
        self::BID => 'BID',
        self::ASK => 'ASK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

