<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Trading account entity. 
 *
 * Generated from protobuf message <code>ProtoOATrader</code>
 */
class ProtoOATrader extends \Google\Protobuf\Internal\Message
{
    /**
     * The unique Trader's Account ID used to match the responses to the Trader's Account.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 1;</code>
     */
    protected $ctidTraderAccountId = 0;
    /**
     * Current account balance.
     *
     * Generated from protobuf field <code>int64 balance = 2;</code>
     */
    protected $balance = 0;
    /**
     * Balance version used to identify the final balance. Increments each time when the trader's account balance is changed.
     *
     * Generated from protobuf field <code>int64 balanceVersion = 3;</code>
     */
    protected $balanceVersion = 0;
    /**
     * Amount of broker's bonus allocated to the account.
     *
     * Generated from protobuf field <code>int64 managerBonus = 4;</code>
     */
    protected $managerBonus = 0;
    /**
     * Amount of introducing broker bonus allocated to the account.
     *
     * Generated from protobuf field <code>int64 ibBonus = 5;</code>
     */
    protected $ibBonus = 0;
    /**
     * Broker's bonus that cannot be withdrew from the account as cash.
     *
     * Generated from protobuf field <code>int64 nonWithdrawableBonus = 6;</code>
     */
    protected $nonWithdrawableBonus = 0;
    /**
     * Access rights that an owner has to the account in cTrader platform. See ProtoOAAccessRights for details.
     *
     * Generated from protobuf field <code>.ProtoOAAccessRights accessRights = 7;</code>
     */
    protected $accessRights = 0;
    /**
     * Deposit currency of the account.
     *
     * Generated from protobuf field <code>int64 depositAssetId = 8;</code>
     */
    protected $depositAssetId = 0;
    /**
     * If TRUE then account is Shariah compliant.
     *
     * Generated from protobuf field <code>bool swapFree = 9;</code>
     */
    protected $swapFree = false;
    /**
     * Account leverage (e.g. If leverage = 1:50 then value = 5000).
     *
     * Generated from protobuf field <code>uint32 leverageInCents = 10;</code>
     */
    protected $leverageInCents = 0;
    /**
     * Margin computation type for the account (MAX, SUM, NET).
     *
     * Generated from protobuf field <code>.ProtoOATotalMarginCalculationType totalMarginCalculationType = 11;</code>
     */
    protected $totalMarginCalculationType = 0;
    /**
     * Maximum allowed leverage for the account. Used as validation when a Trader can change leverage value.
     *
     * Generated from protobuf field <code>uint32 maxLeverage = 12;</code>
     */
    protected $maxLeverage = 0;
    /**
     * If TRUE then account is AMF compliant. Use isLimitedRisk and limitedRiskMarginCalculationStrategy.
     *
     * Generated from protobuf field <code>bool frenchRisk = 13;</code>
     */
    protected $frenchRisk = false;
    /**
     * ID of the account that is unique per server (Broker).
     *
     * Generated from protobuf field <code>int64 traderLogin = 14;</code>
     */
    protected $traderLogin = 0;
    /**
     * Account type: HEDGED, NETTED, etc.
     *
     * Generated from protobuf field <code>.ProtoOAAccountType accountType = 15;</code>
     */
    protected $accountType = 0;
    /**
     * Some whitelabel assigned to trader by broker at the moment of account creation.
     *
     * Generated from protobuf field <code>string brokerName = 16;</code>
     */
    protected $brokerName = '';
    /**
     * The Unix timestamp in milliseconds of the account registration. Should be used as minimal date in historical data requests.
     *
     * Generated from protobuf field <code>int64 registrationTimestamp = 17;</code>
     */
    protected $registrationTimestamp = 0;
    /**
     * If TRUE then account is compliant to use specific margin calculation strategy. Such accounts are require to have guaranteed stop loss on all positions.
     *
     * Generated from protobuf field <code>bool isLimitedRisk = 18;</code>
     */
    protected $isLimitedRisk = false;
    /**
     * Special strategy used in margin calculations for this account (if account isLimitedRisk).
     *
     * Generated from protobuf field <code>.ProtoOALimitedRiskMarginCalculationStrategy limitedRiskMarginCalculationStrategy = 19;</code>
     */
    protected $limitedRiskMarginCalculationStrategy = 0;
    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects balance, managerBonus, ibBonus, nonWithdrawableBonus.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 20;</code>
     */
    protected $moneyDigits = 0;
    /**
     * If TRUE - Position is fully closed on Stop Out, if FALSE - smart (partial closing) Stop Out is applied, if unspecified  - Stop Out format is determined by Broker.
     *
     * Generated from protobuf field <code>bool fairStopOut = 21;</code>
     */
    protected $fairStopOut = false;
    /**
     *The Stop Out strategy that is used for this Trader. The Trader can change the value in the cTrader UI if this option is not disabled by the Broker
     *
     * Generated from protobuf field <code>.ProtoOAStopOutStrategy stopOutStrategy = 22;</code>
     */
    protected $stopOutStrategy = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $ctidTraderAccountId
     *           The unique Trader's Account ID used to match the responses to the Trader's Account.
     *     @type int|string $balance
     *           Current account balance.
     *     @type int|string $balanceVersion
     *           Balance version used to identify the final balance. Increments each time when the trader's account balance is changed.
     *     @type int|string $managerBonus
     *           Amount of broker's bonus allocated to the account.
     *     @type int|string $ibBonus
     *           Amount of introducing broker bonus allocated to the account.
     *     @type int|string $nonWithdrawableBonus
     *           Broker's bonus that cannot be withdrew from the account as cash.
     *     @type int $accessRights
     *           Access rights that an owner has to the account in cTrader platform. See ProtoOAAccessRights for details.
     *     @type int|string $depositAssetId
     *           Deposit currency of the account.
     *     @type bool $swapFree
     *           If TRUE then account is Shariah compliant.
     *     @type int $leverageInCents
     *           Account leverage (e.g. If leverage = 1:50 then value = 5000).
     *     @type int $totalMarginCalculationType
     *           Margin computation type for the account (MAX, SUM, NET).
     *     @type int $maxLeverage
     *           Maximum allowed leverage for the account. Used as validation when a Trader can change leverage value.
     *     @type bool $frenchRisk
     *           If TRUE then account is AMF compliant. Use isLimitedRisk and limitedRiskMarginCalculationStrategy.
     *     @type int|string $traderLogin
     *           ID of the account that is unique per server (Broker).
     *     @type int $accountType
     *           Account type: HEDGED, NETTED, etc.
     *     @type string $brokerName
     *           Some whitelabel assigned to trader by broker at the moment of account creation.
     *     @type int|string $registrationTimestamp
     *           The Unix timestamp in milliseconds of the account registration. Should be used as minimal date in historical data requests.
     *     @type bool $isLimitedRisk
     *           If TRUE then account is compliant to use specific margin calculation strategy. Such accounts are require to have guaranteed stop loss on all positions.
     *     @type int $limitedRiskMarginCalculationStrategy
     *           Special strategy used in margin calculations for this account (if account isLimitedRisk).
     *     @type int $moneyDigits
     *           Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects balance, managerBonus, ibBonus, nonWithdrawableBonus.
     *     @type bool $fairStopOut
     *           If TRUE - Position is fully closed on Stop Out, if FALSE - smart (partial closing) Stop Out is applied, if unspecified  - Stop Out format is determined by Broker.
     *     @type int $stopOutStrategy
     *          The Stop Out strategy that is used for this Trader. The Trader can change the value in the cTrader UI if this option is not disabled by the Broker
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * The unique Trader's Account ID used to match the responses to the Trader's Account.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 1;</code>
     * @return int|string
     */
    public function getCtidTraderAccountId()
    {
        return $this->ctidTraderAccountId;
    }

    /**
     * The unique Trader's Account ID used to match the responses to the Trader's Account.
     *
     * Generated from protobuf field <code>int64 ctidTraderAccountId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCtidTraderAccountId($var)
    {
        GPBUtil::checkInt64($var);
        $this->ctidTraderAccountId = $var;

        return $this;
    }

    /**
     * Current account balance.
     *
     * Generated from protobuf field <code>int64 balance = 2;</code>
     * @return int|string
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     * Current account balance.
     *
     * Generated from protobuf field <code>int64 balance = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkInt64($var);
        $this->balance = $var;

        return $this;
    }

    /**
     * Balance version used to identify the final balance. Increments each time when the trader's account balance is changed.
     *
     * Generated from protobuf field <code>int64 balanceVersion = 3;</code>
     * @return int|string
     */
    public function getBalanceVersion()
    {
        return $this->balanceVersion;
    }

    /**
     * Balance version used to identify the final balance. Increments each time when the trader's account balance is changed.
     *
     * Generated from protobuf field <code>int64 balanceVersion = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBalanceVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->balanceVersion = $var;

        return $this;
    }

    /**
     * Amount of broker's bonus allocated to the account.
     *
     * Generated from protobuf field <code>int64 managerBonus = 4;</code>
     * @return int|string
     */
    public function getManagerBonus()
    {
        return $this->managerBonus;
    }

    /**
     * Amount of broker's bonus allocated to the account.
     *
     * Generated from protobuf field <code>int64 managerBonus = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setManagerBonus($var)
    {
        GPBUtil::checkInt64($var);
        $this->managerBonus = $var;

        return $this;
    }

    /**
     * Amount of introducing broker bonus allocated to the account.
     *
     * Generated from protobuf field <code>int64 ibBonus = 5;</code>
     * @return int|string
     */
    public function getIbBonus()
    {
        return $this->ibBonus;
    }

    /**
     * Amount of introducing broker bonus allocated to the account.
     *
     * Generated from protobuf field <code>int64 ibBonus = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIbBonus($var)
    {
        GPBUtil::checkInt64($var);
        $this->ibBonus = $var;

        return $this;
    }

    /**
     * Broker's bonus that cannot be withdrew from the account as cash.
     *
     * Generated from protobuf field <code>int64 nonWithdrawableBonus = 6;</code>
     * @return int|string
     */
    public function getNonWithdrawableBonus()
    {
        return $this->nonWithdrawableBonus;
    }

    /**
     * Broker's bonus that cannot be withdrew from the account as cash.
     *
     * Generated from protobuf field <code>int64 nonWithdrawableBonus = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNonWithdrawableBonus($var)
    {
        GPBUtil::checkInt64($var);
        $this->nonWithdrawableBonus = $var;

        return $this;
    }

    /**
     * Access rights that an owner has to the account in cTrader platform. See ProtoOAAccessRights for details.
     *
     * Generated from protobuf field <code>.ProtoOAAccessRights accessRights = 7;</code>
     * @return int
     */
    public function getAccessRights()
    {
        return $this->accessRights;
    }

    /**
     * Access rights that an owner has to the account in cTrader platform. See ProtoOAAccessRights for details.
     *
     * Generated from protobuf field <code>.ProtoOAAccessRights accessRights = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setAccessRights($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAAccessRights::class);
        $this->accessRights = $var;

        return $this;
    }

    /**
     * Deposit currency of the account.
     *
     * Generated from protobuf field <code>int64 depositAssetId = 8;</code>
     * @return int|string
     */
    public function getDepositAssetId()
    {
        return $this->depositAssetId;
    }

    /**
     * Deposit currency of the account.
     *
     * Generated from protobuf field <code>int64 depositAssetId = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDepositAssetId($var)
    {
        GPBUtil::checkInt64($var);
        $this->depositAssetId = $var;

        return $this;
    }

    /**
     * If TRUE then account is Shariah compliant.
     *
     * Generated from protobuf field <code>bool swapFree = 9;</code>
     * @return bool
     */
    public function getSwapFree()
    {
        return $this->swapFree;
    }

    /**
     * If TRUE then account is Shariah compliant.
     *
     * Generated from protobuf field <code>bool swapFree = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setSwapFree($var)
    {
        GPBUtil::checkBool($var);
        $this->swapFree = $var;

        return $this;
    }

    /**
     * Account leverage (e.g. If leverage = 1:50 then value = 5000).
     *
     * Generated from protobuf field <code>uint32 leverageInCents = 10;</code>
     * @return int
     */
    public function getLeverageInCents()
    {
        return $this->leverageInCents;
    }

    /**
     * Account leverage (e.g. If leverage = 1:50 then value = 5000).
     *
     * Generated from protobuf field <code>uint32 leverageInCents = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setLeverageInCents($var)
    {
        GPBUtil::checkUint32($var);
        $this->leverageInCents = $var;

        return $this;
    }

    /**
     * Margin computation type for the account (MAX, SUM, NET).
     *
     * Generated from protobuf field <code>.ProtoOATotalMarginCalculationType totalMarginCalculationType = 11;</code>
     * @return int
     */
    public function getTotalMarginCalculationType()
    {
        return $this->totalMarginCalculationType;
    }

    /**
     * Margin computation type for the account (MAX, SUM, NET).
     *
     * Generated from protobuf field <code>.ProtoOATotalMarginCalculationType totalMarginCalculationType = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalMarginCalculationType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOATotalMarginCalculationType::class);
        $this->totalMarginCalculationType = $var;

        return $this;
    }

    /**
     * Maximum allowed leverage for the account. Used as validation when a Trader can change leverage value.
     *
     * Generated from protobuf field <code>uint32 maxLeverage = 12;</code>
     * @return int
     */
    public function getMaxLeverage()
    {
        return $this->maxLeverage;
    }

    /**
     * Maximum allowed leverage for the account. Used as validation when a Trader can change leverage value.
     *
     * Generated from protobuf field <code>uint32 maxLeverage = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxLeverage($var)
    {
        GPBUtil::checkUint32($var);
        $this->maxLeverage = $var;

        return $this;
    }

    /**
     * If TRUE then account is AMF compliant. Use isLimitedRisk and limitedRiskMarginCalculationStrategy.
     *
     * Generated from protobuf field <code>bool frenchRisk = 13;</code>
     * @return bool
     */
    public function getFrenchRisk()
    {
        return $this->frenchRisk;
    }

    /**
     * If TRUE then account is AMF compliant. Use isLimitedRisk and limitedRiskMarginCalculationStrategy.
     *
     * Generated from protobuf field <code>bool frenchRisk = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setFrenchRisk($var)
    {
        GPBUtil::checkBool($var);
        $this->frenchRisk = $var;

        return $this;
    }

    /**
     * ID of the account that is unique per server (Broker).
     *
     * Generated from protobuf field <code>int64 traderLogin = 14;</code>
     * @return int|string
     */
    public function getTraderLogin()
    {
        return $this->traderLogin;
    }

    /**
     * ID of the account that is unique per server (Broker).
     *
     * Generated from protobuf field <code>int64 traderLogin = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTraderLogin($var)
    {
        GPBUtil::checkInt64($var);
        $this->traderLogin = $var;

        return $this;
    }

    /**
     * Account type: HEDGED, NETTED, etc.
     *
     * Generated from protobuf field <code>.ProtoOAAccountType accountType = 15;</code>
     * @return int
     */
    public function getAccountType()
    {
        return $this->accountType;
    }

    /**
     * Account type: HEDGED, NETTED, etc.
     *
     * Generated from protobuf field <code>.ProtoOAAccountType accountType = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setAccountType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAAccountType::class);
        $this->accountType = $var;

        return $this;
    }

    /**
     * Some whitelabel assigned to trader by broker at the moment of account creation.
     *
     * Generated from protobuf field <code>string brokerName = 16;</code>
     * @return string
     */
    public function getBrokerName()
    {
        return $this->brokerName;
    }

    /**
     * Some whitelabel assigned to trader by broker at the moment of account creation.
     *
     * Generated from protobuf field <code>string brokerName = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setBrokerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->brokerName = $var;

        return $this;
    }

    /**
     * The Unix timestamp in milliseconds of the account registration. Should be used as minimal date in historical data requests.
     *
     * Generated from protobuf field <code>int64 registrationTimestamp = 17;</code>
     * @return int|string
     */
    public function getRegistrationTimestamp()
    {
        return $this->registrationTimestamp;
    }

    /**
     * The Unix timestamp in milliseconds of the account registration. Should be used as minimal date in historical data requests.
     *
     * Generated from protobuf field <code>int64 registrationTimestamp = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRegistrationTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->registrationTimestamp = $var;

        return $this;
    }

    /**
     * If TRUE then account is compliant to use specific margin calculation strategy. Such accounts are require to have guaranteed stop loss on all positions.
     *
     * Generated from protobuf field <code>bool isLimitedRisk = 18;</code>
     * @return bool
     */
    public function getIsLimitedRisk()
    {
        return $this->isLimitedRisk;
    }

    /**
     * If TRUE then account is compliant to use specific margin calculation strategy. Such accounts are require to have guaranteed stop loss on all positions.
     *
     * Generated from protobuf field <code>bool isLimitedRisk = 18;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLimitedRisk($var)
    {
        GPBUtil::checkBool($var);
        $this->isLimitedRisk = $var;

        return $this;
    }

    /**
     * Special strategy used in margin calculations for this account (if account isLimitedRisk).
     *
     * Generated from protobuf field <code>.ProtoOALimitedRiskMarginCalculationStrategy limitedRiskMarginCalculationStrategy = 19;</code>
     * @return int
     */
    public function getLimitedRiskMarginCalculationStrategy()
    {
        return $this->limitedRiskMarginCalculationStrategy;
    }

    /**
     * Special strategy used in margin calculations for this account (if account isLimitedRisk).
     *
     * Generated from protobuf field <code>.ProtoOALimitedRiskMarginCalculationStrategy limitedRiskMarginCalculationStrategy = 19;</code>
     * @param int $var
     * @return $this
     */
    public function setLimitedRiskMarginCalculationStrategy($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOALimitedRiskMarginCalculationStrategy::class);
        $this->limitedRiskMarginCalculationStrategy = $var;

        return $this;
    }

    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects balance, managerBonus, ibBonus, nonWithdrawableBonus.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 20;</code>
     * @return int
     */
    public function getMoneyDigits()
    {
        return $this->moneyDigits;
    }

    /**
     * Specifies the exponent of the monetary values. E.g. moneyDigits = 8 must be interpret as business value multiplied by 10^8, then real balance would be 10053099944 / 10^8 = 100.53099944. Affects balance, managerBonus, ibBonus, nonWithdrawableBonus.
     *
     * Generated from protobuf field <code>uint32 moneyDigits = 20;</code>
     * @param int $var
     * @return $this
     */
    public function setMoneyDigits($var)
    {
        GPBUtil::checkUint32($var);
        $this->moneyDigits = $var;

        return $this;
    }

    /**
     * If TRUE - Position is fully closed on Stop Out, if FALSE - smart (partial closing) Stop Out is applied, if unspecified  - Stop Out format is determined by Broker.
     *
     * Generated from protobuf field <code>bool fairStopOut = 21;</code>
     * @return bool
     */
    public function getFairStopOut()
    {
        return $this->fairStopOut;
    }

    /**
     * If TRUE - Position is fully closed on Stop Out, if FALSE - smart (partial closing) Stop Out is applied, if unspecified  - Stop Out format is determined by Broker.
     *
     * Generated from protobuf field <code>bool fairStopOut = 21;</code>
     * @param bool $var
     * @return $this
     */
    public function setFairStopOut($var)
    {
        GPBUtil::checkBool($var);
        $this->fairStopOut = $var;

        return $this;
    }

    /**
     *The Stop Out strategy that is used for this Trader. The Trader can change the value in the cTrader UI if this option is not disabled by the Broker
     *
     * Generated from protobuf field <code>.ProtoOAStopOutStrategy stopOutStrategy = 22;</code>
     * @return int
     */
    public function getStopOutStrategy()
    {
        return $this->stopOutStrategy;
    }

    /**
     *The Stop Out strategy that is used for this Trader. The Trader can change the value in the cTrader UI if this option is not disabled by the Broker
     *
     * Generated from protobuf field <code>.ProtoOAStopOutStrategy stopOutStrategy = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setStopOutStrategy($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAStopOutStrategy::class);
        $this->stopOutStrategy = $var;

        return $this;
    }

}

