<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Request for the authorizing an application to work with the cTrader platform Proxies. 
 *
 * Generated from protobuf message <code>ProtoOAApplicationAuthReq</code>
 */
class ProtoOAApplicationAuthReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     */
    protected $payloadType = 0;
    /**
     * The unique Client ID provided during the registration.
     *
     * Generated from protobuf field <code>string clientId = 2;</code>
     */
    protected $clientId = '';
    /**
     * The unique Client Secret provided during the registration.
     *
     * Generated from protobuf field <code>string clientSecret = 3;</code>
     */
    protected $clientSecret = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $payloadType
     *     @type string $clientId
     *           The unique Client ID provided during the registration.
     *     @type string $clientSecret
     *           The unique Client Secret provided during the registration.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @return int
     */
    public function getPayloadType()
    {
        return $this->payloadType;
    }

    /**
     * Generated from protobuf field <code>.ProtoOAPayloadType payloadType = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPayloadType($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOAPayloadType::class);
        $this->payloadType = $var;

        return $this;
    }

    /**
     * The unique Client ID provided during the registration.
     *
     * Generated from protobuf field <code>string clientId = 2;</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->clientId;
    }

    /**
     * The unique Client ID provided during the registration.
     *
     * Generated from protobuf field <code>string clientId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientId = $var;

        return $this;
    }

    /**
     * The unique Client Secret provided during the registration.
     *
     * Generated from protobuf field <code>string clientSecret = 3;</code>
     * @return string
     */
    public function getClientSecret()
    {
        return $this->clientSecret;
    }

    /**
     * The unique Client Secret provided during the registration.
     *
     * Generated from protobuf field <code>string clientSecret = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClientSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientSecret = $var;

        return $this;
    }

}

