<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Historical Trendbar entity. 
 *
 * Generated from protobuf message <code>ProtoOATrendbar</code>
 */
class ProtoOATrendbar extends \Google\Protobuf\Internal\Message
{
    /**
     * Bar volume in ticks.
     *
     * Generated from protobuf field <code>int64 volume = 3;</code>
     */
    protected $volume = 0;
    /**
     * Bar period.
     *
     * Generated from protobuf field <code>.ProtoOATrendbarPeriod period = 4;</code>
     */
    protected $period = 0;
    /**
     * Low price of the bar.
     *
     * Generated from protobuf field <code>int64 low = 5;</code>
     */
    protected $low = 0;
    /**
     * Delta between open and low price. open = low + deltaOpen.
     *
     * Generated from protobuf field <code>uint64 deltaOpen = 6;</code>
     */
    protected $deltaOpen = 0;
    /**
     * Delta between close and low price. close = low + deltaClose.
     *
     * Generated from protobuf field <code>uint64 deltaClose = 7;</code>
     */
    protected $deltaClose = 0;
    /**
     * Delta between high and low price. high = low + deltaHigh.
     *
     * Generated from protobuf field <code>uint64 deltaHigh = 8;</code>
     */
    protected $deltaHigh = 0;
    /**
     * The Unix time in minutes of the bar, equal to the timestamp of the open tick.
     *
     * Generated from protobuf field <code>uint32 utcTimestampInMinutes = 9;</code>
     */
    protected $utcTimestampInMinutes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $volume
     *           Bar volume in ticks.
     *     @type int $period
     *           Bar period.
     *     @type int|string $low
     *           Low price of the bar.
     *     @type int|string $deltaOpen
     *           Delta between open and low price. open = low + deltaOpen.
     *     @type int|string $deltaClose
     *           Delta between close and low price. close = low + deltaClose.
     *     @type int|string $deltaHigh
     *           Delta between high and low price. high = low + deltaHigh.
     *     @type int $utcTimestampInMinutes
     *           The Unix time in minutes of the bar, equal to the timestamp of the open tick.
     * }
     */
    public function __construct($data = NULL) {
        \SocialiteProviders\Ctrader\Protobuf\Internal\OpenApiModelMessages::initOnce();
        parent::__construct($data);
    }

    /**
     * Bar volume in ticks.
     *
     * Generated from protobuf field <code>int64 volume = 3;</code>
     * @return int|string
     */
    public function getVolume()
    {
        return $this->volume;
    }

    /**
     * Bar volume in ticks.
     *
     * Generated from protobuf field <code>int64 volume = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVolume($var)
    {
        GPBUtil::checkInt64($var);
        $this->volume = $var;

        return $this;
    }

    /**
     * Bar period.
     *
     * Generated from protobuf field <code>.ProtoOATrendbarPeriod period = 4;</code>
     * @return int
     */
    public function getPeriod()
    {
        return $this->period;
    }

    /**
     * Bar period.
     *
     * Generated from protobuf field <code>.ProtoOATrendbarPeriod period = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPeriod($var)
    {
        GPBUtil::checkEnum($var, \SocialiteProviders\Ctrader\Protobuf\ProtoOATrendbarPeriod::class);
        $this->period = $var;

        return $this;
    }

    /**
     * Low price of the bar.
     *
     * Generated from protobuf field <code>int64 low = 5;</code>
     * @return int|string
     */
    public function getLow()
    {
        return $this->low;
    }

    /**
     * Low price of the bar.
     *
     * Generated from protobuf field <code>int64 low = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLow($var)
    {
        GPBUtil::checkInt64($var);
        $this->low = $var;

        return $this;
    }

    /**
     * Delta between open and low price. open = low + deltaOpen.
     *
     * Generated from protobuf field <code>uint64 deltaOpen = 6;</code>
     * @return int|string
     */
    public function getDeltaOpen()
    {
        return $this->deltaOpen;
    }

    /**
     * Delta between open and low price. open = low + deltaOpen.
     *
     * Generated from protobuf field <code>uint64 deltaOpen = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeltaOpen($var)
    {
        GPBUtil::checkUint64($var);
        $this->deltaOpen = $var;

        return $this;
    }

    /**
     * Delta between close and low price. close = low + deltaClose.
     *
     * Generated from protobuf field <code>uint64 deltaClose = 7;</code>
     * @return int|string
     */
    public function getDeltaClose()
    {
        return $this->deltaClose;
    }

    /**
     * Delta between close and low price. close = low + deltaClose.
     *
     * Generated from protobuf field <code>uint64 deltaClose = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeltaClose($var)
    {
        GPBUtil::checkUint64($var);
        $this->deltaClose = $var;

        return $this;
    }

    /**
     * Delta between high and low price. high = low + deltaHigh.
     *
     * Generated from protobuf field <code>uint64 deltaHigh = 8;</code>
     * @return int|string
     */
    public function getDeltaHigh()
    {
        return $this->deltaHigh;
    }

    /**
     * Delta between high and low price. high = low + deltaHigh.
     *
     * Generated from protobuf field <code>uint64 deltaHigh = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeltaHigh($var)
    {
        GPBUtil::checkUint64($var);
        $this->deltaHigh = $var;

        return $this;
    }

    /**
     * The Unix time in minutes of the bar, equal to the timestamp of the open tick.
     *
     * Generated from protobuf field <code>uint32 utcTimestampInMinutes = 9;</code>
     * @return int
     */
    public function getUtcTimestampInMinutes()
    {
        return $this->utcTimestampInMinutes;
    }

    /**
     * The Unix time in minutes of the bar, equal to the timestamp of the open tick.
     *
     * Generated from protobuf field <code>uint32 utcTimestampInMinutes = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setUtcTimestampInMinutes($var)
    {
        GPBUtil::checkUint32($var);
        $this->utcTimestampInMinutes = $var;

        return $this;
    }

}

