<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenApiModelMessages.proto

namespace SocialiteProviders\Ctrader\Protobuf;

use UnexpectedValueException;

/**
 ** Enum for specifying stop loss and take profit distances. 
 *
 * Protobuf type <code>ProtoOASymbolDistanceType</code>
 */
class ProtoOASymbolDistanceType
{
    /**
     * Generated from protobuf enum <code>SYMBOL_DISTANCE_UNKNOWN = 0;</code>
     */
    const SYMBOL_DISTANCE_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>SYMBOL_DISTANCE_IN_POINTS = 1;</code>
     */
    const SYMBOL_DISTANCE_IN_POINTS = 1;
    /**
     * Generated from protobuf enum <code>SYMBOL_DISTANCE_IN_PERCENTAGE = 2;</code>
     */
    const SYMBOL_DISTANCE_IN_PERCENTAGE = 2;

    private static $valueToName = [
        self::SYMBOL_DISTANCE_UNKNOWN => 'SYMBOL_DISTANCE_UNKNOWN',
        self::SYMBOL_DISTANCE_IN_POINTS => 'SYMBOL_DISTANCE_IN_POINTS',
        self::SYMBOL_DISTANCE_IN_PERCENTAGE => 'SYMBOL_DISTANCE_IN_PERCENTAGE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

